@ Decompiled. Regenerate rather than edit.

	.align 2
DirectSoundWaveData_ai_ac_grand_piano_00::
	.incbin "sound/direct_sound_samples/ai_ac_grand_piano_00.bin"

	.align 2
DirectSoundWaveData_ai_ac_grand_piano_01::
	.incbin "sound/direct_sound_samples/ai_ac_grand_piano_01.bin"

	.align 2
DirectSoundWaveData_ai_ac_grand_piano_03::
	.incbin "sound/direct_sound_samples/ai_ac_grand_piano_03.bin"

	.align 2
DirectSoundWaveData_ai_ac_grand_piano_06::
	.incbin "sound/direct_sound_samples/ai_ac_grand_piano_06.bin"

	.align 2
DirectSoundWaveData_ai_ac_grand_piano_09::
	.incbin "sound/direct_sound_samples/ai_ac_grand_piano_09.bin"

	.align 2
DirectSoundWaveData_ai_ac_grand_piano_12::
	.incbin "sound/direct_sound_samples/ai_ac_grand_piano_12.bin"

	.align 2
DirectSoundWaveData_ai_ac_grand_piano_14::
	.incbin "sound/direct_sound_samples/ai_ac_grand_piano_14.bin"

	.align 2
DirectSoundWaveData_ai_ac_grand_piano_16::
	.incbin "sound/direct_sound_samples/ai_ac_grand_piano_16.bin"

	.align 2
DirectSoundWaveData_ai_ac_grand_piano_18::
	.incbin "sound/direct_sound_samples/ai_ac_grand_piano_18.bin"

	.align 2
DirectSoundWaveData_ai_ac_grand_piano_21::
	.incbin "sound/direct_sound_samples/ai_ac_grand_piano_21.bin"

	.align 2
DirectSoundWaveData_ai_accordion_00::
	.incbin "sound/direct_sound_samples/ai_accordion_00.bin"

	.align 2
DirectSoundWaveData_ai_accordion_05::
	.incbin "sound/direct_sound_samples/ai_accordion_05.bin"

	.align 2
DirectSoundWaveData_ai_accordion_06::
	.incbin "sound/direct_sound_samples/ai_accordion_06.bin"

	.align 2
DirectSoundWaveData_ai_acoustic_bass_00::
	.incbin "sound/direct_sound_samples/ai_acoustic_bass_00.bin"

	.align 2
DirectSoundWaveData_ai_acoustic_bass_01::
	.incbin "sound/direct_sound_samples/ai_acoustic_bass_01.bin"

	.align 2
DirectSoundWaveData_ai_acoustic_bass_02::
	.incbin "sound/direct_sound_samples/ai_acoustic_bass_02.bin"

	.align 2
DirectSoundWaveData_ai_acoustic_bass_10::
	.incbin "sound/direct_sound_samples/ai_acoustic_bass_10.bin"

	.align 2
DirectSoundWaveData_ai_acoustic_bass_11::
	.incbin "sound/direct_sound_samples/ai_acoustic_bass_11.bin"

	.align 2
DirectSoundWaveData_ai_agogo::
	.incbin "sound/direct_sound_samples/ai_agogo.bin"

	.align 2
DirectSoundWaveData_ai_alto_sax_00::
	.incbin "sound/direct_sound_samples/ai_alto_sax_00.bin"

	.align 2
DirectSoundWaveData_ai_alto_sax_04::
	.incbin "sound/direct_sound_samples/ai_alto_sax_04.bin"

	.align 2
DirectSoundWaveData_ai_alto_sax_07::
	.incbin "sound/direct_sound_samples/ai_alto_sax_07.bin"

	.align 2
DirectSoundWaveData_ai_alto_sax_08::
	.incbin "sound/direct_sound_samples/ai_alto_sax_08.bin"

	.align 2
DirectSoundWaveData_ai_alto_sax_11::
	.incbin "sound/direct_sound_samples/ai_alto_sax_11.bin"

	.align 2
DirectSoundWaveData_ai_alto_sax_15::
	.incbin "sound/direct_sound_samples/ai_alto_sax_15.bin"

	.align 2
DirectSoundWaveData_ai_alto_sax_17::
	.incbin "sound/direct_sound_samples/ai_alto_sax_17.bin"

	.align 2
DirectSoundWaveData_ai_alto_sax_21::
	.incbin "sound/direct_sound_samples/ai_alto_sax_21.bin"

	.align 2
DirectSoundWaveData_ai_applause_00::
	.incbin "sound/direct_sound_samples/ai_applause_00.bin"

	.align 2
DirectSoundWaveData_ai_bagpipe_00::
	.incbin "sound/direct_sound_samples/ai_bagpipe_00.bin"

	.align 2
DirectSoundWaveData_ai_bagpipe_04::
	.incbin "sound/direct_sound_samples/ai_bagpipe_04.bin"

	.align 2
DirectSoundWaveData_ai_bagpipe_06::
	.incbin "sound/direct_sound_samples/ai_bagpipe_06.bin"

	.align 2
DirectSoundWaveData_ai_bagpipe_10::
	.incbin "sound/direct_sound_samples/ai_bagpipe_10.bin"

	.align 2
DirectSoundWaveData_ai_bagpipe_11::
	.incbin "sound/direct_sound_samples/ai_bagpipe_11.bin"

	.align 2
DirectSoundWaveData_ai_banjo_00::
	.incbin "sound/direct_sound_samples/ai_banjo_00.bin"

	.align 2
DirectSoundWaveData_ai_banjo_02::
	.incbin "sound/direct_sound_samples/ai_banjo_02.bin"

	.align 2
DirectSoundWaveData_ai_banjo_05::
	.incbin "sound/direct_sound_samples/ai_banjo_05.bin"

	.align 2
DirectSoundWaveData_ai_baritone_sax_00::
	.incbin "sound/direct_sound_samples/ai_baritone_sax_00.bin"

	.align 2
DirectSoundWaveData_ai_baritone_sax_01::
	.incbin "sound/direct_sound_samples/ai_baritone_sax_01.bin"

	.align 2
DirectSoundWaveData_ai_baritone_sax_04::
	.incbin "sound/direct_sound_samples/ai_baritone_sax_04.bin"

	.align 2
DirectSoundWaveData_ai_baritone_sax_12::
	.incbin "sound/direct_sound_samples/ai_baritone_sax_12.bin"

	.align 2
DirectSoundWaveData_ai_baritone_sax_18::
	.incbin "sound/direct_sound_samples/ai_baritone_sax_18.bin"

	.align 2
DirectSoundWaveData_ai_bass_lead_00::
	.incbin "sound/direct_sound_samples/ai_bass_lead_00.bin"

	.align 2
DirectSoundWaveData_ai_bass_lead_02::
	.incbin "sound/direct_sound_samples/ai_bass_lead_02.bin"

	.align 2
DirectSoundWaveData_ai_bass_lead_06::
	.incbin "sound/direct_sound_samples/ai_bass_lead_06.bin"

	.align 2
DirectSoundWaveData_ai_bassoon_00::
	.incbin "sound/direct_sound_samples/ai_bassoon_00.bin"

	.align 2
DirectSoundWaveData_ai_bassoon_02::
	.incbin "sound/direct_sound_samples/ai_bassoon_02.bin"

	.align 2
DirectSoundWaveData_ai_bird_tweet::
	.incbin "sound/direct_sound_samples/ai_bird_tweet.bin"

	.align 2
DirectSoundWaveData_ai_blown_bottle_00::
	.incbin "sound/direct_sound_samples/ai_blown_bottle_00.bin"

	.align 2
DirectSoundWaveData_ai_blown_bottle_03::
	.incbin "sound/direct_sound_samples/ai_blown_bottle_03.bin"

	.align 2
DirectSoundWaveData_ai_brass_section_00::
	.incbin "sound/direct_sound_samples/ai_brass_section_00.bin"

	.align 2
DirectSoundWaveData_ai_brass_section_04::
	.incbin "sound/direct_sound_samples/ai_brass_section_04.bin"

	.align 2
DirectSoundWaveData_ai_brass_section_05::
	.incbin "sound/direct_sound_samples/ai_brass_section_05.bin"

	.align 2
DirectSoundWaveData_ai_breath_noise_00::
	.incbin "sound/direct_sound_samples/ai_breath_noise_00.bin"

	.align 2
DirectSoundWaveData_ai_breath_noise_03::
	.incbin "sound/direct_sound_samples/ai_breath_noise_03.bin"

	.align 2
DirectSoundWaveData_ai_breath_noise_05::
	.incbin "sound/direct_sound_samples/ai_breath_noise_05.bin"

	.align 2
DirectSoundWaveData_ai_calliope_lead_00::
	.incbin "sound/direct_sound_samples/ai_calliope_lead_00.bin"

	.align 2
DirectSoundWaveData_ai_calliope_lead_03::
	.incbin "sound/direct_sound_samples/ai_calliope_lead_03.bin"

	.align 2
DirectSoundWaveData_ai_celesta_00::
	.incbin "sound/direct_sound_samples/ai_celesta_00.bin"

	.align 2
DirectSoundWaveData_ai_celesta_04::
	.incbin "sound/direct_sound_samples/ai_celesta_04.bin"

	.align 2
DirectSoundWaveData_ai_celesta_05::
	.incbin "sound/direct_sound_samples/ai_celesta_05.bin"

	.align 2
DirectSoundWaveData_ai_cello_00::
	.incbin "sound/direct_sound_samples/ai_cello_00.bin"

	.align 2
DirectSoundWaveData_ai_cello_01::
	.incbin "sound/direct_sound_samples/ai_cello_01.bin"

	.align 2
DirectSoundWaveData_ai_cello_03::
	.incbin "sound/direct_sound_samples/ai_cello_03.bin"

	.align 2
DirectSoundWaveData_ai_cello_06::
	.incbin "sound/direct_sound_samples/ai_cello_06.bin"

	.align 2
DirectSoundWaveData_ai_cello_09::
	.incbin "sound/direct_sound_samples/ai_cello_09.bin"

	.align 2
DirectSoundWaveData_ai_charang_lead_00::
	.incbin "sound/direct_sound_samples/ai_charang_lead_00.bin"

	.align 2
DirectSoundWaveData_ai_charang_lead_01::
	.incbin "sound/direct_sound_samples/ai_charang_lead_01.bin"

	.align 2
DirectSoundWaveData_ai_chiff_lead_00::
	.incbin "sound/direct_sound_samples/ai_chiff_lead_00.bin"

	.align 2
DirectSoundWaveData_ai_chiff_lead_01::
	.incbin "sound/direct_sound_samples/ai_chiff_lead_01.bin"

	.align 2
DirectSoundWaveData_ai_choir_aahs_00::
	.incbin "sound/direct_sound_samples/ai_choir_aahs_00.bin"

	.align 2
DirectSoundWaveData_ai_church_organ_00::
	.incbin "sound/direct_sound_samples/ai_church_organ_00.bin"

	.align 2
DirectSoundWaveData_ai_church_organ_03::
	.incbin "sound/direct_sound_samples/ai_church_organ_03.bin"

	.align 2
DirectSoundWaveData_ai_church_organ_05::
	.incbin "sound/direct_sound_samples/ai_church_organ_05.bin"

	.align 2
DirectSoundWaveData_ai_church_organ_08::
	.incbin "sound/direct_sound_samples/ai_church_organ_08.bin"

	.align 2
DirectSoundWaveData_ai_church_organ_11::
	.incbin "sound/direct_sound_samples/ai_church_organ_11.bin"

	.align 2
DirectSoundWaveData_ai_clarinet_00::
	.incbin "sound/direct_sound_samples/ai_clarinet_00.bin"

	.align 2
DirectSoundWaveData_ai_clarinet_03::
	.incbin "sound/direct_sound_samples/ai_clarinet_03.bin"

	.align 2
DirectSoundWaveData_ai_clarinet_07::
	.incbin "sound/direct_sound_samples/ai_clarinet_07.bin"

	.align 2
DirectSoundWaveData_ai_clarinet_09::
	.incbin "sound/direct_sound_samples/ai_clarinet_09.bin"

	.align 2
DirectSoundWaveData_ai_clarinet_11::
	.incbin "sound/direct_sound_samples/ai_clarinet_11.bin"

	.align 2
DirectSoundWaveData_ai_clavi_00::
	.incbin "sound/direct_sound_samples/ai_clavi_00.bin"

	.align 2
DirectSoundWaveData_ai_clavi_01::
	.incbin "sound/direct_sound_samples/ai_clavi_01.bin"

	.align 2
DirectSoundWaveData_ai_clavi_06::
	.incbin "sound/direct_sound_samples/ai_clavi_06.bin"

	.align 2
DirectSoundWaveData_ai_clavi_08::
	.incbin "sound/direct_sound_samples/ai_clavi_08.bin"

	.align 2
DirectSoundWaveData_ai_clavi_12::
	.incbin "sound/direct_sound_samples/ai_clavi_12.bin"

	.align 2
DirectSoundWaveData_ai_clean_guitar_00::
	.incbin "sound/direct_sound_samples/ai_clean_guitar_00.bin"

	.align 2
DirectSoundWaveData_ai_clean_guitar_05::
	.incbin "sound/direct_sound_samples/ai_clean_guitar_05.bin"

	.align 2
DirectSoundWaveData_ai_clean_guitar_07::
	.incbin "sound/direct_sound_samples/ai_clean_guitar_07.bin"

	.align 2
DirectSoundWaveData_ai_clean_guitar_11::
	.incbin "sound/direct_sound_samples/ai_clean_guitar_11.bin"

	.align 2
DirectSoundWaveData_ai_clean_guitar_14::
	.incbin "sound/direct_sound_samples/ai_clean_guitar_14.bin"

	.align 2
DirectSoundWaveData_ai_contrabass_00::
	.incbin "sound/direct_sound_samples/ai_contrabass_00.bin"

	.align 2
DirectSoundWaveData_ai_contrabass_02::
	.incbin "sound/direct_sound_samples/ai_contrabass_02.bin"

	.align 2
DirectSoundWaveData_ai_contrabass_05::
	.incbin "sound/direct_sound_samples/ai_contrabass_05.bin"

	.align 2
DirectSoundWaveData_ai_distortion_guitar_00::
	.incbin "sound/direct_sound_samples/ai_distortion_guitar_00.bin"

	.align 2
DirectSoundWaveData_ai_distortion_guitar_01::
	.incbin "sound/direct_sound_samples/ai_distortion_guitar_01.bin"

	.align 2
DirectSoundWaveData_ai_distortion_guitar_02::
	.incbin "sound/direct_sound_samples/ai_distortion_guitar_02.bin"

	.align 2
DirectSoundWaveData_ai_distortion_guitar_03::
	.incbin "sound/direct_sound_samples/ai_distortion_guitar_03.bin"

	.align 2
DirectSoundWaveData_ai_distortion_guitar_06::
	.incbin "sound/direct_sound_samples/ai_distortion_guitar_06.bin"

	.align 2
DirectSoundWaveData_ai_distortion_guitar_09::
	.incbin "sound/direct_sound_samples/ai_distortion_guitar_09.bin"

	.align 2
DirectSoundWaveData_ai_distortion_guitar_12::
	.incbin "sound/direct_sound_samples/ai_distortion_guitar_12.bin"

	.align 2
DirectSoundWaveData_ai_distortion_guitar_17::
	.incbin "sound/direct_sound_samples/ai_distortion_guitar_17.bin"

	.align 2
DirectSoundWaveData_ai_distortion_guitar_19::
	.incbin "sound/direct_sound_samples/ai_distortion_guitar_19.bin"

	.align 2
DirectSoundWaveData_ai_drawbar_organ_00::
	.incbin "sound/direct_sound_samples/ai_drawbar_organ_00.bin"

	.align 2
DirectSoundWaveData_ai_drawbar_organ_05::
	.incbin "sound/direct_sound_samples/ai_drawbar_organ_05.bin"

	.align 2
DirectSoundWaveData_ai_drawbar_organ_07::
	.incbin "sound/direct_sound_samples/ai_drawbar_organ_07.bin"

	.align 2
DirectSoundWaveData_ai_dulcimer_00::
	.incbin "sound/direct_sound_samples/ai_dulcimer_00.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_1_00::
	.incbin "sound/direct_sound_samples/ai_el_piano_1_00.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_1_01::
	.incbin "sound/direct_sound_samples/ai_el_piano_1_01.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_1_04::
	.incbin "sound/direct_sound_samples/ai_el_piano_1_04.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_1_06::
	.incbin "sound/direct_sound_samples/ai_el_piano_1_06.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_1_09::
	.incbin "sound/direct_sound_samples/ai_el_piano_1_09.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_2_00::
	.incbin "sound/direct_sound_samples/ai_el_piano_2_00.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_2_03::
	.incbin "sound/direct_sound_samples/ai_el_piano_2_03.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_2_06::
	.incbin "sound/direct_sound_samples/ai_el_piano_2_06.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_2_08::
	.incbin "sound/direct_sound_samples/ai_el_piano_2_08.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_2_10::
	.incbin "sound/direct_sound_samples/ai_el_piano_2_10.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_2_14::
	.incbin "sound/direct_sound_samples/ai_el_piano_2_14.bin"

	.align 2
DirectSoundWaveData_ai_el_piano_2_17::
	.incbin "sound/direct_sound_samples/ai_el_piano_2_17.bin"

	.align 2
DirectSoundWaveData_ai_english_horn_00::
	.incbin "sound/direct_sound_samples/ai_english_horn_00.bin"

	.align 2
DirectSoundWaveData_ai_english_horn_01::
	.incbin "sound/direct_sound_samples/ai_english_horn_01.bin"

	.align 2
DirectSoundWaveData_ai_english_horn_02::
	.incbin "sound/direct_sound_samples/ai_english_horn_02.bin"

	.align 2
DirectSoundWaveData_ai_english_horn_07::
	.incbin "sound/direct_sound_samples/ai_english_horn_07.bin"

	.align 2
DirectSoundWaveData_ai_fifths_lead_00::
	.incbin "sound/direct_sound_samples/ai_fifths_lead_00.bin"

	.align 2
DirectSoundWaveData_ai_fifths_lead_03::
	.incbin "sound/direct_sound_samples/ai_fifths_lead_03.bin"

	.align 2
DirectSoundWaveData_ai_finger_bass_00::
	.incbin "sound/direct_sound_samples/ai_finger_bass_00.bin"

	.align 2
DirectSoundWaveData_ai_finger_bass_01::
	.incbin "sound/direct_sound_samples/ai_finger_bass_01.bin"

	.align 2
DirectSoundWaveData_ai_finger_bass_02::
	.incbin "sound/direct_sound_samples/ai_finger_bass_02.bin"

	.align 2
DirectSoundWaveData_ai_flute_00::
	.incbin "sound/direct_sound_samples/ai_flute_00.bin"

	.align 2
DirectSoundWaveData_ai_flute_04::
	.incbin "sound/direct_sound_samples/ai_flute_04.bin"

	.align 2
DirectSoundWaveData_ai_flute_09::
	.incbin "sound/direct_sound_samples/ai_flute_09.bin"

	.align 2
DirectSoundWaveData_ai_flute_12::
	.incbin "sound/direct_sound_samples/ai_flute_12.bin"

	.align 2
DirectSoundWaveData_ai_flute_16::
	.incbin "sound/direct_sound_samples/ai_flute_16.bin"

	.align 2
DirectSoundWaveData_ai_flute_19::
	.incbin "sound/direct_sound_samples/ai_flute_19.bin"

	.align 2
DirectSoundWaveData_ai_french_horn_00::
	.incbin "sound/direct_sound_samples/ai_french_horn_00.bin"

	.align 2
DirectSoundWaveData_ai_french_horn_01::
	.incbin "sound/direct_sound_samples/ai_french_horn_01.bin"

	.align 2
DirectSoundWaveData_ai_fretless_bass_00::
	.incbin "sound/direct_sound_samples/ai_fretless_bass_00.bin"

	.align 2
DirectSoundWaveData_ai_fretless_bass_02::
	.incbin "sound/direct_sound_samples/ai_fretless_bass_02.bin"

	.align 2
DirectSoundWaveData_ai_fretless_bass_05::
	.incbin "sound/direct_sound_samples/ai_fretless_bass_05.bin"

	.align 2
DirectSoundWaveData_ai_fx_atmosphere_00::
	.incbin "sound/direct_sound_samples/ai_fx_atmosphere_00.bin"

	.align 2
DirectSoundWaveData_ai_fx_atmosphere_01::
	.incbin "sound/direct_sound_samples/ai_fx_atmosphere_01.bin"

	.align 2
DirectSoundWaveData_ai_fx_crystal_00::
	.incbin "sound/direct_sound_samples/ai_fx_crystal_00.bin"

	.align 2
DirectSoundWaveData_ai_fx_goblins::
	.incbin "sound/direct_sound_samples/ai_fx_goblins.bin"

	.align 2
DirectSoundWaveData_ai_fx_rain_00::
	.incbin "sound/direct_sound_samples/ai_fx_rain_00.bin"

	.align 2
DirectSoundWaveData_ai_fx_sci_fi_00::
	.incbin "sound/direct_sound_samples/ai_fx_sci_fi_00.bin"

	.align 2
DirectSoundWaveData_ai_fx_sci_fi_02::
	.incbin "sound/direct_sound_samples/ai_fx_sci_fi_02.bin"

	.align 2
DirectSoundWaveData_ai_fx_soundtrack_00::
	.incbin "sound/direct_sound_samples/ai_fx_soundtrack_00.bin"

	.align 2
DirectSoundWaveData_ai_fx_soundtrack_02::
	.incbin "sound/direct_sound_samples/ai_fx_soundtrack_02.bin"

	.align 2
DirectSoundWaveData_ai_glockenspiel_00::
	.incbin "sound/direct_sound_samples/ai_glockenspiel_00.bin"

	.align 2
DirectSoundWaveData_ai_glockenspiel_03::
	.incbin "sound/direct_sound_samples/ai_glockenspiel_03.bin"

	.align 2
DirectSoundWaveData_ai_glockenspiel_04::
	.incbin "sound/direct_sound_samples/ai_glockenspiel_04.bin"

	.align 2
DirectSoundWaveData_ai_guitar_fret_noise::
	.incbin "sound/direct_sound_samples/ai_guitar_fret_noise.bin"

	.align 2
DirectSoundWaveData_ai_guitar_harmonics_00::
	.incbin "sound/direct_sound_samples/ai_guitar_harmonics_00.bin"

	.align 2
DirectSoundWaveData_ai_guitar_harmonics_01::
	.incbin "sound/direct_sound_samples/ai_guitar_harmonics_01.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_00::
	.incbin "sound/direct_sound_samples/ai_gunshot_00.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_30::
	.incbin "sound/direct_sound_samples/ai_gunshot_30.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_31::
	.incbin "sound/direct_sound_samples/ai_gunshot_31.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_32::
	.incbin "sound/direct_sound_samples/ai_gunshot_32.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_34::
	.incbin "sound/direct_sound_samples/ai_gunshot_34.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_35::
	.incbin "sound/direct_sound_samples/ai_gunshot_35.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_36::
	.incbin "sound/direct_sound_samples/ai_gunshot_36.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_37::
	.incbin "sound/direct_sound_samples/ai_gunshot_37.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_38::
	.incbin "sound/direct_sound_samples/ai_gunshot_38.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_39::
	.incbin "sound/direct_sound_samples/ai_gunshot_39.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_40::
	.incbin "sound/direct_sound_samples/ai_gunshot_40.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_41::
	.incbin "sound/direct_sound_samples/ai_gunshot_41.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_42::
	.incbin "sound/direct_sound_samples/ai_gunshot_42.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_43::
	.incbin "sound/direct_sound_samples/ai_gunshot_43.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_45::
	.incbin "sound/direct_sound_samples/ai_gunshot_45.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_46::
	.incbin "sound/direct_sound_samples/ai_gunshot_46.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_47::
	.incbin "sound/direct_sound_samples/ai_gunshot_47.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_48::
	.incbin "sound/direct_sound_samples/ai_gunshot_48.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_49::
	.incbin "sound/direct_sound_samples/ai_gunshot_49.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_52::
	.incbin "sound/direct_sound_samples/ai_gunshot_52.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_53::
	.incbin "sound/direct_sound_samples/ai_gunshot_53.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_54::
	.incbin "sound/direct_sound_samples/ai_gunshot_54.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_55::
	.incbin "sound/direct_sound_samples/ai_gunshot_55.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_56::
	.incbin "sound/direct_sound_samples/ai_gunshot_56.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_57::
	.incbin "sound/direct_sound_samples/ai_gunshot_57.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_59::
	.incbin "sound/direct_sound_samples/ai_gunshot_59.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_60::
	.incbin "sound/direct_sound_samples/ai_gunshot_60.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_61::
	.incbin "sound/direct_sound_samples/ai_gunshot_61.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_62::
	.incbin "sound/direct_sound_samples/ai_gunshot_62.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_63::
	.incbin "sound/direct_sound_samples/ai_gunshot_63.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_64::
	.incbin "sound/direct_sound_samples/ai_gunshot_64.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_68::
	.incbin "sound/direct_sound_samples/ai_gunshot_68.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_69::
	.incbin "sound/direct_sound_samples/ai_gunshot_69.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_76::
	.incbin "sound/direct_sound_samples/ai_gunshot_76.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_78::
	.incbin "sound/direct_sound_samples/ai_gunshot_78.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_80::
	.incbin "sound/direct_sound_samples/ai_gunshot_80.bin"

	.align 2
DirectSoundWaveData_ai_gunshot_81::
	.incbin "sound/direct_sound_samples/ai_gunshot_81.bin"

	.align 2
DirectSoundWaveData_ai_harmonica_00::
	.incbin "sound/direct_sound_samples/ai_harmonica_00.bin"

	.align 2
DirectSoundWaveData_ai_harmonica_09::
	.incbin "sound/direct_sound_samples/ai_harmonica_09.bin"

	.align 2
DirectSoundWaveData_ai_harmonica_13::
	.incbin "sound/direct_sound_samples/ai_harmonica_13.bin"

	.align 2
DirectSoundWaveData_ai_harmonica_16::
	.incbin "sound/direct_sound_samples/ai_harmonica_16.bin"

	.align 2
DirectSoundWaveData_ai_harmonica_19::
	.incbin "sound/direct_sound_samples/ai_harmonica_19.bin"

	.align 2
DirectSoundWaveData_ai_harmonica_23::
	.incbin "sound/direct_sound_samples/ai_harmonica_23.bin"

	.align 2
DirectSoundWaveData_ai_harpsichord_00::
	.incbin "sound/direct_sound_samples/ai_harpsichord_00.bin"

	.align 2
DirectSoundWaveData_ai_harpsichord_02::
	.incbin "sound/direct_sound_samples/ai_harpsichord_02.bin"

	.align 2
DirectSoundWaveData_ai_harpsichord_03::
	.incbin "sound/direct_sound_samples/ai_harpsichord_03.bin"

	.align 2
DirectSoundWaveData_ai_harpsichord_05::
	.incbin "sound/direct_sound_samples/ai_harpsichord_05.bin"

	.align 2
DirectSoundWaveData_ai_helicopter::
	.incbin "sound/direct_sound_samples/ai_helicopter.bin"

	.align 2
DirectSoundWaveData_ai_honky_tonk_00::
	.incbin "sound/direct_sound_samples/ai_honky_tonk_00.bin"

	.align 2
DirectSoundWaveData_ai_honky_tonk_02::
	.incbin "sound/direct_sound_samples/ai_honky_tonk_02.bin"

	.align 2
DirectSoundWaveData_ai_honky_tonk_07::
	.incbin "sound/direct_sound_samples/ai_honky_tonk_07.bin"

	.align 2
DirectSoundWaveData_ai_honky_tonk_08::
	.incbin "sound/direct_sound_samples/ai_honky_tonk_08.bin"

	.align 2
DirectSoundWaveData_ai_honky_tonk_11::
	.incbin "sound/direct_sound_samples/ai_honky_tonk_11.bin"

	.align 2
DirectSoundWaveData_ai_jazz_guitar_00::
	.incbin "sound/direct_sound_samples/ai_jazz_guitar_00.bin"

	.align 2
DirectSoundWaveData_ai_jazz_guitar_02::
	.incbin "sound/direct_sound_samples/ai_jazz_guitar_02.bin"

	.align 2
DirectSoundWaveData_ai_jazz_guitar_04::
	.incbin "sound/direct_sound_samples/ai_jazz_guitar_04.bin"

	.align 2
DirectSoundWaveData_ai_jazz_guitar_07::
	.incbin "sound/direct_sound_samples/ai_jazz_guitar_07.bin"

	.align 2
DirectSoundWaveData_ai_jazz_guitar_09::
	.incbin "sound/direct_sound_samples/ai_jazz_guitar_09.bin"

	.align 2
DirectSoundWaveData_ai_jazz_guitar_11::
	.incbin "sound/direct_sound_samples/ai_jazz_guitar_11.bin"

	.align 2
DirectSoundWaveData_ai_kalimba_00::
	.incbin "sound/direct_sound_samples/ai_kalimba_00.bin"

	.align 2
DirectSoundWaveData_ai_koto_00::
	.incbin "sound/direct_sound_samples/ai_koto_00.bin"

	.align 2
DirectSoundWaveData_ai_koto_04::
	.incbin "sound/direct_sound_samples/ai_koto_04.bin"

	.align 2
DirectSoundWaveData_ai_marimba_00::
	.incbin "sound/direct_sound_samples/ai_marimba_00.bin"

	.align 2
DirectSoundWaveData_ai_marimba_01::
	.incbin "sound/direct_sound_samples/ai_marimba_01.bin"

	.align 2
DirectSoundWaveData_ai_melodic_tom::
	.incbin "sound/direct_sound_samples/ai_melodic_tom.bin"

	.align 2
DirectSoundWaveData_ai_music_box_00::
	.incbin "sound/direct_sound_samples/ai_music_box_00.bin"

	.align 2
DirectSoundWaveData_ai_muted_guitar_00::
	.incbin "sound/direct_sound_samples/ai_muted_guitar_00.bin"

	.align 2
DirectSoundWaveData_ai_muted_guitar_06::
	.incbin "sound/direct_sound_samples/ai_muted_guitar_06.bin"

	.align 2
DirectSoundWaveData_ai_muted_guitar_07::
	.incbin "sound/direct_sound_samples/ai_muted_guitar_07.bin"

	.align 2
DirectSoundWaveData_ai_muted_trumpet_00::
	.incbin "sound/direct_sound_samples/ai_muted_trumpet_00.bin"

	.align 2
DirectSoundWaveData_ai_muted_trumpet_03::
	.incbin "sound/direct_sound_samples/ai_muted_trumpet_03.bin"

	.align 2
DirectSoundWaveData_ai_muted_trumpet_06::
	.incbin "sound/direct_sound_samples/ai_muted_trumpet_06.bin"

	.align 2
DirectSoundWaveData_ai_muted_trumpet_10::
	.incbin "sound/direct_sound_samples/ai_muted_trumpet_10.bin"

	.align 2
DirectSoundWaveData_ai_new_age_pad_00::
	.incbin "sound/direct_sound_samples/ai_new_age_pad_00.bin"

	.align 2
DirectSoundWaveData_ai_new_age_pad_03::
	.incbin "sound/direct_sound_samples/ai_new_age_pad_03.bin"

	.align 2
DirectSoundWaveData_ai_nylon_guitar_00::
	.incbin "sound/direct_sound_samples/ai_nylon_guitar_00.bin"

	.align 2
DirectSoundWaveData_ai_nylon_guitar_01::
	.incbin "sound/direct_sound_samples/ai_nylon_guitar_01.bin"

	.align 2
DirectSoundWaveData_ai_nylon_guitar_05::
	.incbin "sound/direct_sound_samples/ai_nylon_guitar_05.bin"

	.align 2
DirectSoundWaveData_ai_nylon_guitar_08::
	.incbin "sound/direct_sound_samples/ai_nylon_guitar_08.bin"

	.align 2
DirectSoundWaveData_ai_nylon_guitar_12::
	.incbin "sound/direct_sound_samples/ai_nylon_guitar_12.bin"

	.align 2
DirectSoundWaveData_ai_nylon_guitar_13::
	.incbin "sound/direct_sound_samples/ai_nylon_guitar_13.bin"

	.align 2
DirectSoundWaveData_ai_nylon_guitar_16::
	.incbin "sound/direct_sound_samples/ai_nylon_guitar_16.bin"

	.align 2
DirectSoundWaveData_ai_oboe_00::
	.incbin "sound/direct_sound_samples/ai_oboe_00.bin"

	.align 2
DirectSoundWaveData_ai_oboe_04::
	.incbin "sound/direct_sound_samples/ai_oboe_04.bin"

	.align 2
DirectSoundWaveData_ai_oboe_07::
	.incbin "sound/direct_sound_samples/ai_oboe_07.bin"

	.align 2
DirectSoundWaveData_ai_oboe_09::
	.incbin "sound/direct_sound_samples/ai_oboe_09.bin"

	.align 2
DirectSoundWaveData_ai_oboe_10::
	.incbin "sound/direct_sound_samples/ai_oboe_10.bin"

	.align 2
DirectSoundWaveData_ai_oboe_15::
	.incbin "sound/direct_sound_samples/ai_oboe_15.bin"

	.align 2
DirectSoundWaveData_ai_ocarina_00::
	.incbin "sound/direct_sound_samples/ai_ocarina_00.bin"

	.align 2
DirectSoundWaveData_ai_ocarina_04::
	.incbin "sound/direct_sound_samples/ai_ocarina_04.bin"

	.align 2
DirectSoundWaveData_ai_orch_harp_00::
	.incbin "sound/direct_sound_samples/ai_orch_harp_00.bin"

	.align 2
DirectSoundWaveData_ai_orch_harp_02::
	.incbin "sound/direct_sound_samples/ai_orch_harp_02.bin"

	.align 2
DirectSoundWaveData_ai_orchestra_hit::
	.incbin "sound/direct_sound_samples/ai_orchestra_hit.bin"

	.align 2
DirectSoundWaveData_ai_overdriven_guitar_00::
	.incbin "sound/direct_sound_samples/ai_overdriven_guitar_00.bin"

	.align 2
DirectSoundWaveData_ai_overdriven_guitar_02::
	.incbin "sound/direct_sound_samples/ai_overdriven_guitar_02.bin"

	.align 2
DirectSoundWaveData_ai_overdriven_guitar_03::
	.incbin "sound/direct_sound_samples/ai_overdriven_guitar_03.bin"

	.align 2
DirectSoundWaveData_ai_overdriven_guitar_05::
	.incbin "sound/direct_sound_samples/ai_overdriven_guitar_05.bin"

	.align 2
DirectSoundWaveData_ai_overdriven_guitar_06::
	.incbin "sound/direct_sound_samples/ai_overdriven_guitar_06.bin"

	.align 2
DirectSoundWaveData_ai_overdriven_guitar_09::
	.incbin "sound/direct_sound_samples/ai_overdriven_guitar_09.bin"

	.align 2
DirectSoundWaveData_ai_overdriven_guitar_11::
	.incbin "sound/direct_sound_samples/ai_overdriven_guitar_11.bin"

	.align 2
DirectSoundWaveData_ai_overdriven_guitar_12::
	.incbin "sound/direct_sound_samples/ai_overdriven_guitar_12.bin"

	.align 2
DirectSoundWaveData_ai_overdriven_guitar_16::
	.incbin "sound/direct_sound_samples/ai_overdriven_guitar_16.bin"

	.align 2
DirectSoundWaveData_ai_overdriven_guitar_18::
	.incbin "sound/direct_sound_samples/ai_overdriven_guitar_18.bin"

	.align 2
DirectSoundWaveData_ai_pan_flute_00::
	.incbin "sound/direct_sound_samples/ai_pan_flute_00.bin"

	.align 2
DirectSoundWaveData_ai_perc_organ_00::
	.incbin "sound/direct_sound_samples/ai_perc_organ_00.bin"

	.align 2
DirectSoundWaveData_ai_perc_organ_02::
	.incbin "sound/direct_sound_samples/ai_perc_organ_02.bin"

	.align 2
DirectSoundWaveData_ai_perc_organ_06::
	.incbin "sound/direct_sound_samples/ai_perc_organ_06.bin"

	.align 2
DirectSoundWaveData_ai_piccolo_00::
	.incbin "sound/direct_sound_samples/ai_piccolo_00.bin"

	.align 2
DirectSoundWaveData_ai_piccolo_01::
	.incbin "sound/direct_sound_samples/ai_piccolo_01.bin"

	.align 2
DirectSoundWaveData_ai_piccolo_05::
	.incbin "sound/direct_sound_samples/ai_piccolo_05.bin"

	.align 2
DirectSoundWaveData_ai_pick_bass_00::
	.incbin "sound/direct_sound_samples/ai_pick_bass_00.bin"

	.align 2
DirectSoundWaveData_ai_pick_bass_01::
	.incbin "sound/direct_sound_samples/ai_pick_bass_01.bin"

	.align 2
DirectSoundWaveData_ai_pick_bass_03::
	.incbin "sound/direct_sound_samples/ai_pick_bass_03.bin"

	.align 2
DirectSoundWaveData_ai_pizzicato_strings_00::
	.incbin "sound/direct_sound_samples/ai_pizzicato_strings_00.bin"

	.align 2
DirectSoundWaveData_ai_pizzicato_strings_04::
	.incbin "sound/direct_sound_samples/ai_pizzicato_strings_04.bin"

	.align 2
DirectSoundWaveData_ai_poly_synth_pad_00::
	.incbin "sound/direct_sound_samples/ai_poly_synth_pad_00.bin"

	.align 2
DirectSoundWaveData_ai_poly_synth_pad_02::
	.incbin "sound/direct_sound_samples/ai_poly_synth_pad_02.bin"

	.align 2
DirectSoundWaveData_ai_poly_synth_pad_04::
	.incbin "sound/direct_sound_samples/ai_poly_synth_pad_04.bin"

	.align 2
DirectSoundWaveData_ai_poly_synth_pad_05::
	.incbin "sound/direct_sound_samples/ai_poly_synth_pad_05.bin"

	.align 2
DirectSoundWaveData_ai_poly_synth_pad_07::
	.incbin "sound/direct_sound_samples/ai_poly_synth_pad_07.bin"

	.align 2
DirectSoundWaveData_ai_recorder_00::
	.incbin "sound/direct_sound_samples/ai_recorder_00.bin"

	.align 2
DirectSoundWaveData_ai_recorder_07::
	.incbin "sound/direct_sound_samples/ai_recorder_07.bin"

	.align 2
DirectSoundWaveData_ai_recorder_08::
	.incbin "sound/direct_sound_samples/ai_recorder_08.bin"

	.align 2
DirectSoundWaveData_ai_recorder_12::
	.incbin "sound/direct_sound_samples/ai_recorder_12.bin"

	.align 2
DirectSoundWaveData_ai_recorder_14::
	.incbin "sound/direct_sound_samples/ai_recorder_14.bin"

	.align 2
DirectSoundWaveData_ai_reed_organ_00::
	.incbin "sound/direct_sound_samples/ai_reed_organ_00.bin"

	.align 2
DirectSoundWaveData_ai_reed_organ_03::
	.incbin "sound/direct_sound_samples/ai_reed_organ_03.bin"

	.align 2
DirectSoundWaveData_ai_reed_organ_07::
	.incbin "sound/direct_sound_samples/ai_reed_organ_07.bin"

	.align 2
DirectSoundWaveData_ai_reverse_cymbal::
	.incbin "sound/direct_sound_samples/ai_reverse_cymbal.bin"

	.align 2
DirectSoundWaveData_ai_rock_organ_00::
	.incbin "sound/direct_sound_samples/ai_rock_organ_00.bin"

	.align 2
DirectSoundWaveData_ai_rock_organ_01::
	.incbin "sound/direct_sound_samples/ai_rock_organ_01.bin"

	.align 2
DirectSoundWaveData_ai_rock_organ_04::
	.incbin "sound/direct_sound_samples/ai_rock_organ_04.bin"

	.align 2
DirectSoundWaveData_ai_saw_lead_00::
	.incbin "sound/direct_sound_samples/ai_saw_lead_00.bin"

	.align 2
DirectSoundWaveData_ai_saw_lead_04::
	.incbin "sound/direct_sound_samples/ai_saw_lead_04.bin"

	.align 2
DirectSoundWaveData_ai_saw_lead_07::
	.incbin "sound/direct_sound_samples/ai_saw_lead_07.bin"

	.align 2
DirectSoundWaveData_ai_seashore::
	.incbin "sound/direct_sound_samples/ai_seashore.bin"

	.align 2
DirectSoundWaveData_ai_shakuhachi_00::
	.incbin "sound/direct_sound_samples/ai_shakuhachi_00.bin"

	.align 2
DirectSoundWaveData_ai_shakuhachi_06::
	.incbin "sound/direct_sound_samples/ai_shakuhachi_06.bin"

	.align 2
DirectSoundWaveData_ai_shakuhachi_08::
	.incbin "sound/direct_sound_samples/ai_shakuhachi_08.bin"

	.align 2
DirectSoundWaveData_ai_shamisen_00::
	.incbin "sound/direct_sound_samples/ai_shamisen_00.bin"

	.align 2
DirectSoundWaveData_ai_shamisen_01::
	.incbin "sound/direct_sound_samples/ai_shamisen_01.bin"

	.align 2
DirectSoundWaveData_ai_shamisen_04::
	.incbin "sound/direct_sound_samples/ai_shamisen_04.bin"

	.align 2
DirectSoundWaveData_ai_shamisen_06::
	.incbin "sound/direct_sound_samples/ai_shamisen_06.bin"

	.align 2
DirectSoundWaveData_ai_sitar_00::
	.incbin "sound/direct_sound_samples/ai_sitar_00.bin"

	.align 2
DirectSoundWaveData_ai_sitar_01::
	.incbin "sound/direct_sound_samples/ai_sitar_01.bin"

	.align 2
DirectSoundWaveData_ai_sitar_03::
	.incbin "sound/direct_sound_samples/ai_sitar_03.bin"

	.align 2
DirectSoundWaveData_ai_slap_bass_1_00::
	.incbin "sound/direct_sound_samples/ai_slap_bass_1_00.bin"

	.align 2
DirectSoundWaveData_ai_slap_bass_1_01::
	.incbin "sound/direct_sound_samples/ai_slap_bass_1_01.bin"

	.align 2
DirectSoundWaveData_ai_slap_bass_1_04::
	.incbin "sound/direct_sound_samples/ai_slap_bass_1_04.bin"

	.align 2
DirectSoundWaveData_ai_slap_bass_2_00::
	.incbin "sound/direct_sound_samples/ai_slap_bass_2_00.bin"

	.align 2
DirectSoundWaveData_ai_soprano_sax_00::
	.incbin "sound/direct_sound_samples/ai_soprano_sax_00.bin"

	.align 2
DirectSoundWaveData_ai_soprano_sax_05::
	.incbin "sound/direct_sound_samples/ai_soprano_sax_05.bin"

	.align 2
DirectSoundWaveData_ai_soprano_sax_08::
	.incbin "sound/direct_sound_samples/ai_soprano_sax_08.bin"

	.align 2
DirectSoundWaveData_ai_soprano_sax_11::
	.incbin "sound/direct_sound_samples/ai_soprano_sax_11.bin"

	.align 2
DirectSoundWaveData_ai_soprano_sax_15::
	.incbin "sound/direct_sound_samples/ai_soprano_sax_15.bin"

	.align 2
DirectSoundWaveData_ai_soprano_sax_18::
	.incbin "sound/direct_sound_samples/ai_soprano_sax_18.bin"

	.align 2
DirectSoundWaveData_ai_square_lead_00::
	.incbin "sound/direct_sound_samples/ai_square_lead_00.bin"

	.align 2
DirectSoundWaveData_ai_square_lead_01::
	.incbin "sound/direct_sound_samples/ai_square_lead_01.bin"

	.align 2
DirectSoundWaveData_ai_square_lead_02::
	.incbin "sound/direct_sound_samples/ai_square_lead_02.bin"

	.align 2
DirectSoundWaveData_ai_square_lead_05::
	.incbin "sound/direct_sound_samples/ai_square_lead_05.bin"

	.align 2
DirectSoundWaveData_ai_square_lead_08::
	.incbin "sound/direct_sound_samples/ai_square_lead_08.bin"

	.align 2
DirectSoundWaveData_ai_square_lead_15::
	.incbin "sound/direct_sound_samples/ai_square_lead_15.bin"

	.align 2
DirectSoundWaveData_ai_steel_drums_00::
	.incbin "sound/direct_sound_samples/ai_steel_drums_00.bin"

	.align 2
DirectSoundWaveData_ai_steel_guitar_00::
	.incbin "sound/direct_sound_samples/ai_steel_guitar_00.bin"

	.align 2
DirectSoundWaveData_ai_steel_guitar_02::
	.incbin "sound/direct_sound_samples/ai_steel_guitar_02.bin"

	.align 2
DirectSoundWaveData_ai_steel_guitar_03::
	.incbin "sound/direct_sound_samples/ai_steel_guitar_03.bin"

	.align 2
DirectSoundWaveData_ai_steel_guitar_06::
	.incbin "sound/direct_sound_samples/ai_steel_guitar_06.bin"

	.align 2
DirectSoundWaveData_ai_steel_guitar_10::
	.incbin "sound/direct_sound_samples/ai_steel_guitar_10.bin"

	.align 2
DirectSoundWaveData_ai_steel_guitar_15::
	.incbin "sound/direct_sound_samples/ai_steel_guitar_15.bin"

	.align 2
DirectSoundWaveData_ai_synth_bass_1_00::
	.incbin "sound/direct_sound_samples/ai_synth_bass_1_00.bin"

	.align 2
DirectSoundWaveData_ai_synth_bass_1_02::
	.incbin "sound/direct_sound_samples/ai_synth_bass_1_02.bin"

	.align 2
DirectSoundWaveData_ai_synth_bass_1_05::
	.incbin "sound/direct_sound_samples/ai_synth_bass_1_05.bin"

	.align 2
DirectSoundWaveData_ai_synth_bass_1_06::
	.incbin "sound/direct_sound_samples/ai_synth_bass_1_06.bin"

	.align 2
DirectSoundWaveData_ai_synth_bass_2_00::
	.incbin "sound/direct_sound_samples/ai_synth_bass_2_00.bin"

	.align 2
DirectSoundWaveData_ai_synth_bass_2_01::
	.incbin "sound/direct_sound_samples/ai_synth_bass_2_01.bin"

	.align 2
DirectSoundWaveData_ai_synth_bass_2_03::
	.incbin "sound/direct_sound_samples/ai_synth_bass_2_03.bin"

	.align 2
DirectSoundWaveData_ai_synth_brass_1_00::
	.incbin "sound/direct_sound_samples/ai_synth_brass_1_00.bin"

	.align 2
DirectSoundWaveData_ai_synth_brass_1_03::
	.incbin "sound/direct_sound_samples/ai_synth_brass_1_03.bin"

	.align 2
DirectSoundWaveData_ai_synth_brass_1_08::
	.incbin "sound/direct_sound_samples/ai_synth_brass_1_08.bin"

	.align 2
DirectSoundWaveData_ai_synth_brass_1_13::
	.incbin "sound/direct_sound_samples/ai_synth_brass_1_13.bin"

	.align 2
DirectSoundWaveData_ai_synth_brass_1_17::
	.incbin "sound/direct_sound_samples/ai_synth_brass_1_17.bin"

	.align 2
DirectSoundWaveData_ai_synth_brass_2_00::
	.incbin "sound/direct_sound_samples/ai_synth_brass_2_00.bin"

	.align 2
DirectSoundWaveData_ai_synth_brass_2_01::
	.incbin "sound/direct_sound_samples/ai_synth_brass_2_01.bin"

	.align 2
DirectSoundWaveData_ai_synth_brass_2_03::
	.incbin "sound/direct_sound_samples/ai_synth_brass_2_03.bin"

	.align 2
DirectSoundWaveData_ai_synth_drum::
	.incbin "sound/direct_sound_samples/ai_synth_drum.bin"

	.align 2
DirectSoundWaveData_ai_synth_strings_1_00::
	.incbin "sound/direct_sound_samples/ai_synth_strings_1_00.bin"

	.align 2
DirectSoundWaveData_ai_synth_strings_1_02::
	.incbin "sound/direct_sound_samples/ai_synth_strings_1_02.bin"

	.align 2
DirectSoundWaveData_ai_synth_strings_1_04::
	.incbin "sound/direct_sound_samples/ai_synth_strings_1_04.bin"

	.align 2
DirectSoundWaveData_ai_synth_voice_00::
	.incbin "sound/direct_sound_samples/ai_synth_voice_00.bin"

	.align 2
DirectSoundWaveData_ai_synth_voice_03::
	.incbin "sound/direct_sound_samples/ai_synth_voice_03.bin"

	.align 2
DirectSoundWaveData_ai_taiko_drum::
	.incbin "sound/direct_sound_samples/ai_taiko_drum.bin"

	.align 2
DirectSoundWaveData_ai_tango_accordion_00::
	.incbin "sound/direct_sound_samples/ai_tango_accordion_00.bin"

	.align 2
DirectSoundWaveData_ai_tango_accordion_04::
	.incbin "sound/direct_sound_samples/ai_tango_accordion_04.bin"

	.align 2
DirectSoundWaveData_ai_telephone_ring::
	.incbin "sound/direct_sound_samples/ai_telephone_ring.bin"

	.align 2
DirectSoundWaveData_ai_tenor_sax_00::
	.incbin "sound/direct_sound_samples/ai_tenor_sax_00.bin"

	.align 2
DirectSoundWaveData_ai_tenor_sax_02::
	.incbin "sound/direct_sound_samples/ai_tenor_sax_02.bin"

	.align 2
DirectSoundWaveData_ai_tenor_sax_03::
	.incbin "sound/direct_sound_samples/ai_tenor_sax_03.bin"

	.align 2
DirectSoundWaveData_ai_tenor_sax_05::
	.incbin "sound/direct_sound_samples/ai_tenor_sax_05.bin"

	.align 2
DirectSoundWaveData_ai_tenor_sax_07::
	.incbin "sound/direct_sound_samples/ai_tenor_sax_07.bin"

	.align 2
DirectSoundWaveData_ai_tenor_sax_08::
	.incbin "sound/direct_sound_samples/ai_tenor_sax_08.bin"

	.align 2
DirectSoundWaveData_ai_tenor_sax_10::
	.incbin "sound/direct_sound_samples/ai_tenor_sax_10.bin"

	.align 2
DirectSoundWaveData_ai_tenor_sax_12::
	.incbin "sound/direct_sound_samples/ai_tenor_sax_12.bin"

	.align 2
DirectSoundWaveData_ai_timpani::
	.incbin "sound/direct_sound_samples/ai_timpani.bin"

	.align 2
DirectSoundWaveData_ai_tinkle_bell::
	.incbin "sound/direct_sound_samples/ai_tinkle_bell.bin"

	.align 2
DirectSoundWaveData_ai_tremolo_strings_00::
	.incbin "sound/direct_sound_samples/ai_tremolo_strings_00.bin"

	.align 2
DirectSoundWaveData_ai_tremolo_strings_01::
	.incbin "sound/direct_sound_samples/ai_tremolo_strings_01.bin"

	.align 2
DirectSoundWaveData_ai_tremolo_strings_02::
	.incbin "sound/direct_sound_samples/ai_tremolo_strings_02.bin"

	.align 2
DirectSoundWaveData_ai_trombone_05::
	.incbin "sound/direct_sound_samples/ai_trombone_05.bin"

	.align 2
DirectSoundWaveData_ai_trombone_07::
	.incbin "sound/direct_sound_samples/ai_trombone_07.bin"

	.align 2
DirectSoundWaveData_ai_trombone_10::
	.incbin "sound/direct_sound_samples/ai_trombone_10.bin"

	.align 2
DirectSoundWaveData_ai_trombone_13::
	.incbin "sound/direct_sound_samples/ai_trombone_13.bin"

	.align 2
DirectSoundWaveData_ai_trombone_15::
	.incbin "sound/direct_sound_samples/ai_trombone_15.bin"

	.align 2
DirectSoundWaveData_ai_trumpet_00::
	.incbin "sound/direct_sound_samples/ai_trumpet_00.bin"

	.align 2
DirectSoundWaveData_ai_trumpet_01::
	.incbin "sound/direct_sound_samples/ai_trumpet_01.bin"

	.align 2
DirectSoundWaveData_ai_trumpet_04::
	.incbin "sound/direct_sound_samples/ai_trumpet_04.bin"

	.align 2
DirectSoundWaveData_ai_trumpet_05::
	.incbin "sound/direct_sound_samples/ai_trumpet_05.bin"

	.align 2
DirectSoundWaveData_ai_trumpet_08::
	.incbin "sound/direct_sound_samples/ai_trumpet_08.bin"

	.align 2
DirectSoundWaveData_ai_trumpet_11::
	.incbin "sound/direct_sound_samples/ai_trumpet_11.bin"

	.align 2
DirectSoundWaveData_ai_trumpet_13::
	.incbin "sound/direct_sound_samples/ai_trumpet_13.bin"

	.align 2
DirectSoundWaveData_ai_trumpet_14::
	.incbin "sound/direct_sound_samples/ai_trumpet_14.bin"

	.align 2
DirectSoundWaveData_ai_trumpet_17::
	.incbin "sound/direct_sound_samples/ai_trumpet_17.bin"

	.align 2
DirectSoundWaveData_ai_tuba_00::
	.incbin "sound/direct_sound_samples/ai_tuba_00.bin"

	.align 2
DirectSoundWaveData_ai_tuba_01::
	.incbin "sound/direct_sound_samples/ai_tuba_01.bin"

	.align 2
DirectSoundWaveData_ai_tubular_bells::
	.incbin "sound/direct_sound_samples/ai_tubular_bells.bin"

	.align 2
DirectSoundWaveData_ai_vibraphone_00::
	.incbin "sound/direct_sound_samples/ai_vibraphone_00.bin"

	.align 2
DirectSoundWaveData_ai_vibraphone_04::
	.incbin "sound/direct_sound_samples/ai_vibraphone_04.bin"

	.align 2
DirectSoundWaveData_ai_vibraphone_07::
	.incbin "sound/direct_sound_samples/ai_vibraphone_07.bin"

	.align 2
DirectSoundWaveData_ai_vibraphone_09::
	.incbin "sound/direct_sound_samples/ai_vibraphone_09.bin"

	.align 2
DirectSoundWaveData_ai_vibraphone_12::
	.incbin "sound/direct_sound_samples/ai_vibraphone_12.bin"

	.align 2
DirectSoundWaveData_ai_violin_00::
	.incbin "sound/direct_sound_samples/ai_violin_00.bin"

	.align 2
DirectSoundWaveData_ai_violin_07::
	.incbin "sound/direct_sound_samples/ai_violin_07.bin"

	.align 2
DirectSoundWaveData_ai_violin_08::
	.incbin "sound/direct_sound_samples/ai_violin_08.bin"

	.align 2
DirectSoundWaveData_ai_violin_11::
	.incbin "sound/direct_sound_samples/ai_violin_11.bin"

	.align 2
DirectSoundWaveData_ai_violin_13::
	.incbin "sound/direct_sound_samples/ai_violin_13.bin"

	.align 2
DirectSoundWaveData_ai_violin_15::
	.incbin "sound/direct_sound_samples/ai_violin_15.bin"

	.align 2
DirectSoundWaveData_ai_violin_18::
	.incbin "sound/direct_sound_samples/ai_violin_18.bin"

	.align 2
DirectSoundWaveData_ai_violin_20::
	.incbin "sound/direct_sound_samples/ai_violin_20.bin"

	.align 2
DirectSoundWaveData_ai_violin_21::
	.incbin "sound/direct_sound_samples/ai_violin_21.bin"

	.align 2
DirectSoundWaveData_ai_voice_lead_00::
	.incbin "sound/direct_sound_samples/ai_voice_lead_00.bin"

	.align 2
DirectSoundWaveData_ai_voice_lead_01::
	.incbin "sound/direct_sound_samples/ai_voice_lead_01.bin"

	.align 2
DirectSoundWaveData_ai_voice_oohs_00::
	.incbin "sound/direct_sound_samples/ai_voice_oohs_00.bin"

	.align 2
DirectSoundWaveData_ai_voice_oohs_04::
	.incbin "sound/direct_sound_samples/ai_voice_oohs_04.bin"

	.align 2
DirectSoundWaveData_ai_voice_oohs_06::
	.incbin "sound/direct_sound_samples/ai_voice_oohs_06.bin"

	.align 2
DirectSoundWaveData_ai_voice_oohs_09::
	.incbin "sound/direct_sound_samples/ai_voice_oohs_09.bin"

	.align 2
DirectSoundWaveData_ai_warm_pad_00::
	.incbin "sound/direct_sound_samples/ai_warm_pad_00.bin"

	.align 2
DirectSoundWaveData_ai_warm_pad_04::
	.incbin "sound/direct_sound_samples/ai_warm_pad_04.bin"

	.align 2
DirectSoundWaveData_ai_whistle_00::
	.incbin "sound/direct_sound_samples/ai_whistle_00.bin"

	.align 2
DirectSoundWaveData_ai_whistle_03::
	.incbin "sound/direct_sound_samples/ai_whistle_03.bin"

	.align 2
DirectSoundWaveData_ai_whistle_05::
	.incbin "sound/direct_sound_samples/ai_whistle_05.bin"

	.align 2
DirectSoundWaveData_ai_woodblock::
	.incbin "sound/direct_sound_samples/ai_woodblock.bin"

	.align 2
DirectSoundWaveData_ai_xylophone_00::
	.incbin "sound/direct_sound_samples/ai_xylophone_00.bin"

	.align 2
DirectSoundWaveData_ai_xylophone_03::
	.incbin "sound/direct_sound_samples/ai_xylophone_03.bin"
