@ Decompiled by tools/rogue/decompile_voicegroup.py.
@ Regenerate rather than edit.

voice_group ai_ac_grand_piano
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_12, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_12, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_14, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_14, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_16, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_16, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_18, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_18, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_18, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_21, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_21, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_21, 255, 254, 0, 235

voice_group ai_accordion
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 0, 255, 235

voice_group ai_acoustic_bass
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_00, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_01, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_02, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_02, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_02, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_02, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_02, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_02, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_02, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_02, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_10, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_11, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_11, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_11, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_11, 255, 254, 51, 235

voice_group ai_alto_sax
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_21, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_21, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_21, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_alto_sax_21, 255, 0, 255, 235

voice_group ai_applause
	voice_directsound 60, 0, DirectSoundWaveData_ai_applause_00, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_applause_00, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_applause_00, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_applause_00, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_applause_00, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_applause_00, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_applause_00, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_applause_00, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_applause_00, 255, 0, 255, 165

voice_group ai_bagpipe
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235

voice_group ai_banjo
	voice_directsound 60, 0, DirectSoundWaveData_ai_banjo_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_banjo_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_banjo_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_banjo_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_banjo_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_banjo_05, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_banjo_05, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harpsichord_05, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_07, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_07, 255, 254, 0, 235

voice_group ai_baritone_sax
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 0, 255, 235

voice_group ai_bass_lead
	voice_directsound 60, 0, DirectSoundWaveData_ai_bass_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bass_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bass_lead_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bass_lead_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bass_lead_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bass_lead_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bass_lead_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bass_lead_06, 255, 0, 255, 235

voice_group ai_bassoon
	voice_directsound 60, 0, DirectSoundWaveData_ai_bassoon_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bassoon_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bassoon_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bassoon_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bassoon_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_baritone_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 0, 255, 235

voice_group ai_blown_bottle
	voice_directsound 60, 0, DirectSoundWaveData_ai_blown_bottle_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_blown_bottle_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_blown_bottle_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_blown_bottle_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235

voice_group ai_bowed_pad
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_09, 255, 0, 255, 235

voice_group ai_brass_section
	voice_directsound 60, 0, DirectSoundWaveData_ai_brass_section_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_brass_section_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_brass_section_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_brass_section_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_brass_section_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_brass_section_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_brass_section_05, 255, 0, 255, 235

voice_group ai_breath_noise
	voice_directsound 60, 0, DirectSoundWaveData_ai_breath_noise_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_breath_noise_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_breath_noise_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_breath_noise_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_breath_noise_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_breath_noise_05, 255, 0, 255, 235

voice_group ai_bright_piano
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_12, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_12, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_14, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_14, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_16, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_16, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_18, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_18, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_18, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_21, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_21, 255, 254, 0, 235

voice_group ai_calliope_lead
	voice_directsound 60, 0, DirectSoundWaveData_ai_calliope_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_calliope_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_calliope_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_calliope_lead_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_calliope_lead_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_calliope_lead_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_calliope_lead_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235

voice_group ai_celesta
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_04, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_05, 255, 249, 0, 235

voice_group ai_cello
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_cello_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_20, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_23, 255, 0, 255, 235

voice_group ai_charang_lead
	voice_directsound 60, 0, DirectSoundWaveData_ai_charang_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_charang_lead_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_charang_lead_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_charang_lead_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_19, 255, 0, 255, 235

voice_group ai_chiff_lead
	voice_directsound 60, 0, DirectSoundWaveData_ai_chiff_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_chiff_lead_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_chiff_lead_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_chiff_lead_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_chiff_lead_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_chiff_lead_01, 255, 0, 255, 235

voice_group ai_choir_aahs
	voice_directsound 60, 0, DirectSoundWaveData_ai_choir_aahs_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_choir_aahs_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235

voice_group ai_church_organ
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_church_organ_11, 255, 0, 255, 235

voice_group ai_clarinet
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clarinet_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_21, 255, 0, 255, 235

voice_group ai_clavi
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_01, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_01, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_01, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_01, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_01, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_06, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_06, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_08, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_08, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_08, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_08, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_12, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_12, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_12, 255, 249, 0, 235

voice_group ai_clean_guitar
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_00, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_00, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_00, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_00, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_00, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_05, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_05, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_07, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_07, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_07, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_07, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_11, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_11, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_11, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_14, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_14, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_14, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_14, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_14, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_14, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_14, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clean_guitar_14, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 245, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 245, 0, 235

voice_group ai_contrabass
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_contrabass_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_16, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_16, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_19, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_19, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_23, 255, 0, 255, 235

voice_group ai_distortion_guitar
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_19, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_19, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_distortion_guitar_19, 255, 0, 255, 235

voice_group ai_drawbar_organ
	voice_directsound 60, 0, DirectSoundWaveData_ai_drawbar_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_drawbar_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_drawbar_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_drawbar_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_drawbar_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_drawbar_organ_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_drawbar_organ_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_drawbar_organ_07, 255, 0, 255, 235

voice_group ai_dulcimer
	voice_directsound 60, 0, DirectSoundWaveData_ai_dulcimer_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_dulcimer_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_dulcimer_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_12, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_clavi_12, 255, 249, 0, 235

voice_group ai_el_grand_piano
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_12, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_12, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_14, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_14, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_16, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_16, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_18, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_18, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_18, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ac_grand_piano_21, 255, 254, 0, 235

voice_group ai_el_piano_1
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_04, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_04, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_06, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_1_09, 255, 254, 0, 235

voice_group ai_el_piano_2
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_00, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_00, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_00, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_03, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_03, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_03, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_06, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_06, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_08, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_08, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_10, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_10, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_10, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_10, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_14, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_14, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_14, 255, 246, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_el_piano_2_17, 255, 246, 0, 235

voice_group ai_english_horn
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_english_horn_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_21, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_21, 255, 0, 255, 235

voice_group ai_fiddle
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235

voice_group ai_fifths_lead
	voice_directsound 60, 0, DirectSoundWaveData_ai_fifths_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fifths_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fifths_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fifths_lead_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fifths_lead_03, 255, 0, 255, 235

voice_group ai_finger_bass
	voice_directsound 60, 0, DirectSoundWaveData_ai_finger_bass_00, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_finger_bass_01, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_finger_bass_02, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_finger_bass_02, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_finger_bass_02, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_finger_bass_02, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_finger_bass_02, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_finger_bass_02, 255, 242, 103, 235

voice_group ai_flute
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_16, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_16, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_16, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_flute_19, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235

voice_group ai_french_horn
	voice_directsound 60, 0, DirectSoundWaveData_ai_french_horn_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_french_horn_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_french_horn_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_french_horn_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_french_horn_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_french_horn_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_21, 255, 0, 255, 235

voice_group ai_fretless_bass
	voice_directsound 60, 0, DirectSoundWaveData_ai_fretless_bass_00, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fretless_bass_00, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fretless_bass_02, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fretless_bass_02, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fretless_bass_02, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fretless_bass_05, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fretless_bass_05, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fretless_bass_05, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_09, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_09, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_09, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_11, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_11, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 254, 25, 235

voice_group ai_fx_atmosphere
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_atmosphere_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_atmosphere_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_atmosphere_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_atmosphere_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_atmosphere_01, 255, 0, 255, 235

voice_group ai_fx_brightness
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_lead_00, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_lead_00, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_warm_pad_04, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_warm_pad_04, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_warm_pad_04, 255, 254, 25, 235

voice_group ai_fx_crystal
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_crystal_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_crystal_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_crystal_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_new_age_pad_03, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_new_age_pad_03, 255, 252, 0, 235

voice_group ai_fx_echoes
	voice_directsound 60, 0, DirectSoundWaveData_ai_choir_aahs_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_choir_aahs_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_lead_01, 255, 0, 255, 235

voice_group ai_fx_rain
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_rain_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_rain_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fifths_lead_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fifths_lead_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fifths_lead_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fifths_lead_03, 255, 254, 0, 235

voice_group ai_fx_sci_fi
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_sci_fi_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_sci_fi_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_sci_fi_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_sci_fi_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235

voice_group ai_fx_soundtrack
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_soundtrack_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_soundtrack_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_soundtrack_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_soundtrack_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_soundtrack_02, 255, 0, 255, 235

voice_group ai_glockenspiel
	voice_directsound 60, 0, DirectSoundWaveData_ai_glockenspiel_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_glockenspiel_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_glockenspiel_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_glockenspiel_03, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_glockenspiel_04, 255, 249, 0, 235

voice_group ai_guitar_harmonics
	voice_directsound 60, 0, DirectSoundWaveData_ai_guitar_harmonics_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_guitar_harmonics_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_guitar_harmonics_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_guitar_harmonics_01, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_guitar_harmonics_01, 255, 254, 0, 235

voice_group ai_gunshot
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_00, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_30, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_31, 8, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_32, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_32, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_34, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_35, 255, 0, 255, 242
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_36, 255, 0, 255, 242
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_37, 255, 240, 0, 240
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_38, 255, 0, 255, 242
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_39, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_40, 255, 240, 0, 154
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_41, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_42, 255, 165, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_43, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_43, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_45, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_46, 255, 220, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_47, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_48, 255, 245, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_49, 255, 240, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_49, 255, 245, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_49, 255, 245, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_52, 255, 240, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_53, 255, 165, 0, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_54, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_55, 255, 231, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_56, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_57, 255, 245, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_57, 255, 245, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_59, 255, 240, 0, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_60, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_61, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_62, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_63, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_64, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_64, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_64, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_64, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_68, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_69, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_69, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_69, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_69, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_69, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_69, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_69, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_76, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_76, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_78, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_78, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_80, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165
	voice_directsound 60, 0, DirectSoundWaveData_ai_gunshot_81, 255, 230, 0, 165

voice_group ai_halo_pad
	voice_directsound 60, 0, DirectSoundWaveData_ai_choir_aahs_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_choir_aahs_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_lead_01, 255, 0, 255, 235

voice_group ai_harmonica
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_16, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_16, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_16, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_19, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_19, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_19, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_19, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_23, 255, 0, 255, 235

voice_group ai_harpsichord
	voice_directsound 60, 0, DirectSoundWaveData_ai_harpsichord_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harpsichord_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harpsichord_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harpsichord_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harpsichord_03, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harpsichord_05, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harpsichord_05, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harpsichord_05, 255, 254, 0, 235

voice_group ai_honky_tonk
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_07, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_08, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_08, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_08, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_11, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_11, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_11, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_11, 255, 254, 0, 235

voice_group ai_jazz_guitar
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_00, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_00, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_02, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_02, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_04, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_04, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_04, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_07, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_07, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_09, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_09, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_11, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_11, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_11, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_11, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 242, 0, 235

voice_group ai_kalimba
	voice_directsound 60, 0, DirectSoundWaveData_ai_kalimba_00, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_kalimba_00, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_kalimba_00, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_kalimba_00, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_kalimba_00, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_11, 255, 242, 0, 235

voice_group ai_koto
	voice_directsound 60, 0, DirectSoundWaveData_ai_koto_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_koto_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_koto_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_koto_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_koto_04, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_koto_04, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_koto_04, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_koto_04, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harpsichord_05, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_07, 255, 252, 0, 235

voice_group ai_marimba
	voice_directsound 60, 0, DirectSoundWaveData_ai_marimba_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_marimba_01, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_marimba_01, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_marimba_01, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_05, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_05, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_05, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_05, 255, 249, 0, 235

voice_group ai_metallic_pad
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_00, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_00, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_02, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_02, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_02, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_02, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_02, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_07, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_08, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_08, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_08, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_11, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_11, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_11, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_honky_tonk_11, 255, 254, 25, 235

voice_group ai_music_box
	voice_directsound 60, 0, DirectSoundWaveData_ai_music_box_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_music_box_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_04, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_04, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_04, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_05, 255, 249, 0, 235

voice_group ai_muted_guitar
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_guitar_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_guitar_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_guitar_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_guitar_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_guitar_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_guitar_00, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_guitar_06, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_guitar_07, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_guitar_07, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_guitar_07, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_12, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_12, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_13, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_13, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 249, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 249, 0, 235

voice_group ai_muted_trumpet
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_muted_trumpet_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_14, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_14, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_14, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_21, 255, 0, 255, 235

voice_group ai_new_age_pad
	voice_directsound 60, 0, DirectSoundWaveData_ai_new_age_pad_00, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_ai_new_age_pad_00, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_ai_new_age_pad_00, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_ai_new_age_pad_03, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_ai_new_age_pad_03, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_ai_new_age_pad_03, 255, 0, 255, 238
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_05, 255, 0, 255, 238

voice_group ai_nylon_guitar
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_00, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_01, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_01, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_01, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_01, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_05, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_05, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_05, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_08, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_08, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_08, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_08, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_12, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_13, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_13, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_13, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 253, 0, 235

voice_group ai_oboe
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_oboe_15, 255, 0, 255, 235

voice_group ai_ocarina
	voice_directsound 60, 0, DirectSoundWaveData_ai_ocarina_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ocarina_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ocarina_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ocarina_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_ocarina_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235

voice_group ai_orch_harp
	voice_directsound 60, 0, DirectSoundWaveData_ai_orch_harp_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_orch_harp_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_orch_harp_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_orch_harp_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_orch_harp_02, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_10, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_10, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_11, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_11, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_11, 255, 254, 0, 235

voice_group ai_overdriven_guitar
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_16, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_16, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_overdriven_guitar_18, 255, 0, 255, 235

voice_group ai_pan_flute
	voice_directsound 60, 0, DirectSoundWaveData_ai_pan_flute_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pan_flute_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pan_flute_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pan_flute_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235

voice_group ai_perc_organ
	voice_directsound 60, 0, DirectSoundWaveData_ai_perc_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_perc_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_perc_organ_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_perc_organ_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_perc_organ_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_perc_organ_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_perc_organ_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_perc_organ_06, 255, 0, 255, 235

voice_group ai_piccolo
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235

voice_group ai_pick_bass
	voice_directsound 60, 0, DirectSoundWaveData_ai_pick_bass_00, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pick_bass_01, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pick_bass_01, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pick_bass_03, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pick_bass_03, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pick_bass_03, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pick_bass_03, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pick_bass_03, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_09, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_09, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_09, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_11, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_jazz_guitar_11, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 242, 103, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_nylon_guitar_16, 255, 242, 103, 235

voice_group ai_pizzicato_strings
	voice_directsound 60, 0, DirectSoundWaveData_ai_pizzicato_strings_00, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pizzicato_strings_00, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pizzicato_strings_00, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pizzicato_strings_00, 255, 242, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_pizzicato_strings_04, 255, 242, 0, 235

voice_group ai_poly_synth_pad
	voice_directsound 60, 0, DirectSoundWaveData_ai_poly_synth_pad_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_poly_synth_pad_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_poly_synth_pad_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_poly_synth_pad_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_poly_synth_pad_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_poly_synth_pad_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_poly_synth_pad_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_poly_synth_pad_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_poly_synth_pad_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_poly_synth_pad_07, 255, 0, 255, 235

voice_group ai_recorder
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_recorder_14, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235

voice_group ai_reed_organ
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_07, 255, 0, 255, 235

voice_group ai_rock_organ
	voice_directsound 60, 0, DirectSoundWaveData_ai_rock_organ_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_rock_organ_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_rock_organ_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_rock_organ_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_rock_organ_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_rock_organ_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_rock_organ_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_rock_organ_04, 255, 0, 255, 235

voice_group ai_saw_lead
	voice_directsound 60, 0, DirectSoundWaveData_ai_saw_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_saw_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_saw_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_saw_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_saw_lead_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_saw_lead_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_saw_lead_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_saw_lead_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_saw_lead_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_saw_lead_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_09, 255, 0, 255, 235

voice_group ai_shakuhachi
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shakuhachi_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235

voice_group ai_shamisen
	voice_directsound 60, 0, DirectSoundWaveData_ai_shamisen_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shamisen_01, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shamisen_01, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shamisen_01, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shamisen_04, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shamisen_04, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shamisen_06, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shamisen_06, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_shamisen_06, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_07, 255, 252, 0, 235

voice_group ai_shanai
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bagpipe_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_23, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_23, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_23, 255, 0, 255, 235

voice_group ai_sitar
	voice_directsound 60, 0, DirectSoundWaveData_ai_sitar_00, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_sitar_01, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_sitar_01, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_sitar_03, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 254, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 254, 25, 235

voice_group ai_slap_bass_1
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_1_00, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_1_01, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_1_01, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_1_01, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_1_04, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_1_04, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_1_04, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 252, 51, 235

voice_group ai_slap_bass_2
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_2_00, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_2_00, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_2_00, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_1_01, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_1_01, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_1_04, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_slap_bass_1_04, 255, 252, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 252, 51, 235

voice_group ai_soprano_sax
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_soprano_sax_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_21, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_21, 255, 0, 255, 235

voice_group ai_square_lead
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_square_lead_15, 255, 0, 255, 235

voice_group ai_steel_drums
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_drums_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_drums_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_drums_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_drums_00, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_acoustic_bass_11, 255, 252, 0, 235

voice_group ai_steel_guitar
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_00, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_00, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_02, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_03, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_03, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_03, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_06, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_06, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_06, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_06, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_10, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_10, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_10, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_10, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_10, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 253, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 253, 0, 235

voice_group ai_string_ens_1
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_00, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_01, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_02, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_02, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_02, 128, 0, 255, 235

voice_group ai_string_ens_2
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_00, 9, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_01, 9, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_02, 9, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_02, 9, 0, 255, 249
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_02, 9, 0, 255, 249

voice_group ai_sweep_pad
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235

voice_group ai_synth_bass_1
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_1_00, 255, 249, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_1_00, 255, 249, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_1_02, 255, 249, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_1_02, 255, 249, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_1_02, 255, 249, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_1_05, 255, 249, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_1_06, 255, 249, 25, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_1_06, 255, 249, 25, 235

voice_group ai_synth_bass_2
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_2_00, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_2_01, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_2_01, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_2_03, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_2_03, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_2_03, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_2_03, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_bass_2_03, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 254, 51, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_steel_guitar_15, 255, 254, 51, 235

voice_group ai_synth_brass_1
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_1_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 255, 0, 255, 235

voice_group ai_synth_brass_2
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_2_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_2_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_2_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_2_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_2_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_brass_2_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_09, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_09, 255, 0, 255, 235

voice_group ai_synth_strings_1
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_00, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_00, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_02, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_02, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 128, 0, 255, 235

voice_group ai_synth_strings_2
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_00, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_02, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_02, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 128, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_strings_1_04, 128, 0, 255, 235

voice_group ai_synth_voice
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_voice_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_voice_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_voice_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_voice_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_voice_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_harmonica_23, 255, 0, 255, 235

voice_group ai_tango_accordion
	voice_directsound 60, 0, DirectSoundWaveData_ai_tango_accordion_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tango_accordion_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tango_accordion_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tango_accordion_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tango_accordion_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tango_accordion_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reed_organ_07, 255, 0, 255, 235

voice_group ai_tenor_sax
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tenor_sax_12, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_accordion_06, 255, 0, 255, 235

voice_group ai_tremolo_strings
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_02, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tremolo_strings_02, 255, 0, 255, 235

voice_group ai_trombone
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_21, 255, 0, 255, 235

voice_group ai_trumpet
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_14, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_14, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_14, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_21, 255, 0, 255, 235

voice_group ai_tuba
	voice_directsound 60, 0, DirectSoundWaveData_ai_tuba_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tuba_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tuba_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_tuba_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_10, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trombone_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_trumpet_17, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_21, 255, 0, 255, 235

voice_group ai_vibraphone
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_00, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_04, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_04, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_04, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_07, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_07, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_09, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_12, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_12, 255, 254, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_vibraphone_12, 255, 254, 0, 235

voice_group ai_viola
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235

voice_group ai_violin
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_07, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_08, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_11, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_13, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_15, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_18, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_20, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_violin_21, 255, 0, 255, 235

voice_group ai_voice_lead
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_lead_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_lead_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_lead_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_lead_01, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_lead_01, 255, 0, 255, 235

voice_group ai_voice_oohs
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_04, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_06, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_oohs_09, 255, 0, 255, 235

voice_group ai_warm_pad
	voice_directsound 60, 0, DirectSoundWaveData_ai_warm_pad_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_warm_pad_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_warm_pad_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_warm_pad_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_warm_pad_04, 255, 0, 255, 235

voice_group ai_whistle
	voice_directsound 60, 0, DirectSoundWaveData_ai_whistle_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_whistle_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_whistle_00, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_whistle_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_whistle_03, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_whistle_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_whistle_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_whistle_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_piccolo_05, 255, 0, 255, 235

voice_group ai_xylophone
	voice_directsound 60, 0, DirectSoundWaveData_ai_xylophone_00, 255, 235, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_xylophone_00, 255, 235, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_xylophone_00, 255, 235, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_xylophone_03, 255, 235, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_celesta_05, 255, 235, 0, 235

voice_group all_instruments
	voice_keysplit voicegroup_ai_ac_grand_piano, keysplit_ai_ac_grand_piano
	voice_keysplit voicegroup_ai_bright_piano, keysplit_ai_ac_grand_piano
	voice_keysplit voicegroup_ai_el_grand_piano, keysplit_ai_ac_grand_piano
	voice_keysplit voicegroup_ai_honky_tonk, keysplit_ai_honky_tonk
	voice_keysplit voicegroup_ai_el_piano_1, keysplit_ai_el_piano_1
	voice_keysplit voicegroup_ai_el_piano_2, keysplit_ai_el_piano_2
	voice_keysplit voicegroup_ai_harpsichord, keysplit_ai_harpsichord
	voice_keysplit voicegroup_ai_clavi, keysplit_ai_honky_tonk
	voice_keysplit voicegroup_ai_celesta, keysplit_ai_celesta
	voice_keysplit voicegroup_ai_glockenspiel, keysplit_ai_glockenspiel
	voice_keysplit voicegroup_ai_music_box, keysplit_ai_celesta
	voice_keysplit voicegroup_ai_vibraphone, keysplit_ai_vibraphone
	voice_keysplit voicegroup_ai_marimba, keysplit_ai_marimba
	@ Slot 13 is the xylophone, exactly as decompiled from the patch. Songs whose
	@ program 13 is really a DRUM track use voicegroup_all_instruments_drums
	@ instead -- see sound/voicegroups/all_instruments_drums.inc. Do not put a kit
	@ here: ten imported songs use this slot as a genuine xylophone.
	voice_keysplit voicegroup_ai_xylophone, keysplit_ai_xylophone
	voice_directsound 60, 0, DirectSoundWaveData_ai_tubular_bells, 255, 249, 0, 235
	voice_keysplit voicegroup_ai_dulcimer, keysplit_ai_dulcimer
	voice_keysplit voicegroup_ai_drawbar_organ, keysplit_ai_drawbar_organ
	voice_keysplit voicegroup_ai_perc_organ, keysplit_ai_drawbar_organ
	voice_keysplit voicegroup_ai_rock_organ, keysplit_ai_drawbar_organ
	voice_keysplit voicegroup_ai_church_organ, keysplit_ai_vibraphone
	voice_keysplit voicegroup_ai_reed_organ, keysplit_ai_drawbar_organ
	voice_keysplit voicegroup_ai_accordion, keysplit_ai_accordion
	voice_keysplit voicegroup_ai_harmonica, keysplit_ai_harmonica
	voice_keysplit voicegroup_ai_tango_accordion, keysplit_ai_harpsichord
	voice_keysplit voicegroup_ai_nylon_guitar, keysplit_ai_el_piano_2
	voice_keysplit voicegroup_ai_steel_guitar, keysplit_ai_harmonica
	voice_keysplit voicegroup_ai_jazz_guitar, keysplit_ai_el_piano_2
	voice_keysplit voicegroup_ai_clean_guitar, keysplit_ai_harmonica
	voice_keysplit voicegroup_ai_muted_guitar, keysplit_ai_muted_guitar
	voice_keysplit voicegroup_ai_overdriven_guitar, keysplit_ai_overdriven_guitar
	voice_keysplit voicegroup_ai_distortion_guitar, keysplit_ai_distortion_guitar
	voice_keysplit voicegroup_ai_guitar_harmonics, keysplit_ai_dulcimer
	voice_keysplit voicegroup_ai_acoustic_bass, keysplit_ai_vibraphone
	voice_keysplit voicegroup_ai_finger_bass, keysplit_ai_harpsichord
	voice_keysplit voicegroup_ai_pick_bass, keysplit_ai_muted_guitar
	voice_keysplit voicegroup_ai_fretless_bass, keysplit_ai_muted_guitar
	voice_keysplit voicegroup_ai_slap_bass_1, keysplit_ai_slap_bass_1
	voice_keysplit voicegroup_ai_slap_bass_2, keysplit_ai_slap_bass_1
	voice_keysplit voicegroup_ai_synth_bass_1, keysplit_ai_slap_bass_1
	voice_keysplit voicegroup_ai_synth_bass_2, keysplit_ai_synth_bass_2
	voice_keysplit voicegroup_ai_violin, keysplit_ai_distortion_guitar
	voice_keysplit voicegroup_ai_viola, keysplit_ai_distortion_guitar
	voice_keysplit voicegroup_ai_cello, keysplit_ai_cello
	voice_keysplit voicegroup_ai_contrabass, keysplit_ai_cello
	voice_keysplit voicegroup_ai_tremolo_strings, keysplit_ai_glockenspiel
	voice_keysplit voicegroup_ai_pizzicato_strings, keysplit_ai_dulcimer
	voice_keysplit voicegroup_ai_orch_harp, keysplit_ai_synth_bass_2
	voice_directsound 60, 0, DirectSoundWaveData_ai_timpani, 255, 0, 255, 235
	voice_keysplit voicegroup_ai_string_ens_1, keysplit_ai_glockenspiel
	voice_keysplit voicegroup_ai_string_ens_2, keysplit_ai_glockenspiel
	voice_keysplit voicegroup_ai_synth_strings_1, keysplit_ai_accordion
	voice_keysplit voicegroup_ai_synth_strings_2, keysplit_ai_accordion
	voice_keysplit voicegroup_ai_choir_aahs, keysplit_ai_dulcimer
	voice_keysplit voicegroup_ai_voice_oohs, keysplit_ai_synth_bass_2
	voice_keysplit voicegroup_ai_synth_voice, keysplit_ai_celesta
	voice_directsound 60, 0, DirectSoundWaveData_ai_orchestra_hit, 255, 253, 0, 235
	voice_keysplit voicegroup_ai_trumpet, keysplit_ai_overdriven_guitar
	voice_keysplit voicegroup_ai_trombone, keysplit_ai_overdriven_guitar
	voice_keysplit voicegroup_ai_tuba, keysplit_ai_tuba
	voice_keysplit voicegroup_ai_muted_trumpet, keysplit_ai_muted_trumpet
	voice_keysplit voicegroup_ai_french_horn, keysplit_ai_french_horn
	voice_keysplit voicegroup_ai_brass_section, keysplit_ai_french_horn
	voice_keysplit voicegroup_ai_synth_brass_1, keysplit_ai_harmonica
	voice_keysplit voicegroup_ai_synth_brass_2, keysplit_ai_synth_brass_2
	voice_keysplit voicegroup_ai_soprano_sax, keysplit_ai_muted_trumpet
	voice_keysplit voicegroup_ai_alto_sax, keysplit_ai_cello
	voice_keysplit voicegroup_ai_tenor_sax, keysplit_ai_tuba
	voice_keysplit voicegroup_ai_baritone_sax, keysplit_ai_harmonica
	voice_keysplit voicegroup_ai_oboe, keysplit_ai_muted_guitar
	voice_keysplit voicegroup_ai_english_horn, keysplit_ai_muted_trumpet
	voice_keysplit voicegroup_ai_bassoon, keysplit_ai_synth_brass_2
	voice_keysplit voicegroup_ai_clarinet, keysplit_ai_clarinet
	voice_keysplit voicegroup_ai_piccolo, keysplit_ai_celesta
	voice_keysplit voicegroup_ai_flute, keysplit_ai_muted_trumpet
	voice_keysplit voicegroup_ai_recorder, keysplit_ai_clarinet
	voice_keysplit voicegroup_ai_pan_flute, keysplit_ai_pan_flute
	voice_keysplit voicegroup_ai_blown_bottle, keysplit_ai_pan_flute
	voice_keysplit voicegroup_ai_shakuhachi, keysplit_ai_vibraphone
	voice_keysplit voicegroup_ai_whistle, keysplit_ai_honky_tonk
	voice_keysplit voicegroup_ai_ocarina, keysplit_ai_marimba
	voice_keysplit voicegroup_ai_square_lead, keysplit_ai_clarinet
	voice_keysplit voicegroup_ai_saw_lead, keysplit_ai_honky_tonk
	voice_keysplit voicegroup_ai_calliope_lead, keysplit_ai_marimba
	voice_keysplit voicegroup_ai_chiff_lead, keysplit_ai_chiff_lead
	voice_keysplit voicegroup_ai_charang_lead, keysplit_ai_xylophone
	voice_keysplit voicegroup_ai_voice_lead, keysplit_ai_voice_lead
	voice_keysplit voicegroup_ai_fifths_lead, keysplit_ai_fifths_lead
	voice_keysplit voicegroup_ai_bass_lead, keysplit_ai_marimba
	voice_keysplit voicegroup_ai_new_age_pad, keysplit_ai_french_horn
	voice_keysplit voicegroup_ai_warm_pad, keysplit_ai_voice_lead
	voice_keysplit voicegroup_ai_poly_synth_pad, keysplit_ai_el_piano_1
	voice_directsound 60, 0, DirectSoundWaveData_ai_voice_lead_01, 255, 0, 255, 235
	voice_keysplit voicegroup_ai_bowed_pad, keysplit_ai_el_piano_1
	voice_keysplit voicegroup_ai_metallic_pad, keysplit_ai_honky_tonk
	voice_keysplit voicegroup_ai_halo_pad, keysplit_ai_xylophone
	voice_keysplit voicegroup_ai_sweep_pad, keysplit_ai_accordion
	voice_keysplit voicegroup_ai_fx_rain, keysplit_ai_pan_flute
	voice_keysplit voicegroup_ai_fx_soundtrack, keysplit_ai_voice_lead
	voice_keysplit voicegroup_ai_fx_crystal, keysplit_ai_voice_lead
	voice_keysplit voicegroup_ai_fx_atmosphere, keysplit_ai_fifths_lead
	voice_keysplit voicegroup_ai_fx_brightness, keysplit_ai_fifths_lead
	voice_directsound 60, 0, DirectSoundWaveData_ai_fx_goblins, 255, 0, 255, 235
	voice_keysplit voicegroup_ai_fx_echoes, keysplit_ai_xylophone
	voice_keysplit voicegroup_ai_fx_sci_fi, keysplit_ai_chiff_lead
	voice_keysplit voicegroup_ai_sitar, keysplit_ai_pan_flute
	voice_keysplit voicegroup_ai_banjo, keysplit_ai_banjo
	voice_keysplit voicegroup_ai_shamisen, keysplit_ai_banjo
	voice_keysplit voicegroup_ai_koto, keysplit_ai_synth_brass_2
	voice_keysplit voicegroup_ai_kalimba, keysplit_ai_pan_flute
	voice_keysplit voicegroup_ai_bagpipe, keysplit_ai_clarinet
	voice_keysplit voicegroup_ai_fiddle, keysplit_ai_cello
	voice_keysplit voicegroup_ai_shanai, keysplit_ai_banjo
	voice_directsound 60, 0, DirectSoundWaveData_ai_tinkle_bell, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_agogo, 255, 242, 0, 235
	voice_keysplit voicegroup_ai_steel_drums, keysplit_ai_fifths_lead
	voice_directsound 60, 0, DirectSoundWaveData_ai_woodblock, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_taiko_drum, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_melodic_tom, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_synth_drum, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_reverse_cymbal, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_guitar_fret_noise, 255, 0, 255, 235
	voice_keysplit voicegroup_ai_breath_noise, keysplit_ai_chiff_lead
	voice_directsound 60, 0, DirectSoundWaveData_ai_seashore, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_bird_tweet, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_telephone_ring, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_ai_helicopter, 255, 0, 255, 235
	voice_keysplit_all voicegroup_ai_applause
	voice_keysplit_all voicegroup_ai_gunshot
