"""
Emit checked-in BW animation assets for TRAINER front pics.

The sister tool to emit_bw_anim.py, which does the same job for species. It is a
SEPARATE SCRIPT rather than a mode of that one because the two share almost
nothing above the downscaler: a different key (TRAINER_PIC_* rather than
SPECIES_*), a different asset directory, a different alignment oracle, and no
shiny path at all. What they do share - the downscale, the resample, the u8
retry - is imported rather than copied.

Per trainer this writes:
  graphics/trainers/front_pics/<name>_bw_anim.png   indexed frame sheet
and rewrites two generated files:
  src/data/rogue_bw_trainer_anim.h        declarations, sequences, lookup table
  graphics/trainers/bw_trainer_anim_rules.mk   one container rule per trainer

ALIGNMENT IS MATCHED TO THE SHIPPED 64x64 PIC, centre-X and bottom-Y. Trainer
front pics carry NO coordinates: struct TrainerFrontPicInfo has an imageData, a
palette, anims and mugshot fields, and unlike struct TrainerBackPicInfo it has
no `coordinates` member at all. So the engine draws every front pic at one
fixed position and where the trainer stands inside the 64x64 canvas is the only
thing that positions them. Censused rather than assumed: all ten Hoenn leader
pics bottom out at y=62 or y=63, so bottom-Y is the rule the art already
follows, and a centred emit would visibly float them.

THE 64x64 CEILING IS NOT NEGOTIABLE HERE and the downscale is not a compromise
against what is on screen today. The BW2 rips are 40-75 x 65-87, so every one
is scaled by 0.74-0.94 - but the shipped pics they replace have ink only 54-64
px tall inside their canvas, so the emitted sprite is the same size or larger
than the one it replaces. The loss is against the DS original, which this game
has never shown.

Run:  python emit_bw_trainer_anim.py --gifs "D:/PokemonTest/BW2 Trainer Sprites"
      python emit_bw_trainer_anim.py --gifs ... --only roxanne,steven
Needs Pillow. Run `make` afterwards - gbagfx and compresSmol run from the build.
"""
import argparse
import re
import sys
from pathlib import Path

from PIL import Image, ImageSequence

sys.path.insert(0, str(Path(__file__).resolve().parent))
import downscale_bw as D
from emit_bw_anim import (VIDEO_FRAME_MS, MAX_FRAMES, U8_OVERFLOW, MAX_MIN_HOLD,
                          DEFAULT_MIN_HOLD, MON_PIC_WIDTH, MON_PIC_HEIGHT,
                          c_name, resample, prune_frames)

# gif stem -> (TRAINER_PIC constant, stock front pic stem)
#
# WRITTEN OUT RATHER THAN DERIVED, and it has to be. Three of the eleven cannot
# be reached by any rule: the rip spells Brawly "Brawley"; Wallace is a
# CHAMPION_ pic rather than a LEADER_ one because his boss slot is the champion
# fight; and Steven's pic has no class prefix at all. A rule that got two of
# those right would emit the third under a name that is in no enum, and the
# roster would silently come up one short - the failure emit_bw_anim.py's own
# skip summary exists to make visible.
#
# TATE AND LIZA ARE ABSENT ON PURPOSE. The rip has them as two separate gifs and
# the engine has ONE TRAINER_PIC_LEADER_TATE_AND_LIZA, so they need a composite
# rather than a mapping - see --pair, which is not implemented yet. Emitting
# either one alone would replace the pair's pic with a single trainer.
#
# The third field is the SOURCE, and it decides how the frames are read:
#
#   'bw2'  - a ripped gif from --gifs, at its own size and its own colours. It
#            is downscaled to fit 64x64 and then placed against the shipped pic.
#   'idle' - frames generated by make_idle_anim.py into --idle-gifs from the
#            SHIPPED pic itself, for a character the dump does not cover. They
#            are already 64x64 and already in the stock position, so they are
#            passed through untouched.
#
# THE PASSTHROUGH IS NOT AN OPTIMISATION. Running generated frames through the
# rip path would re-place them: the union box across frames is wider than the
# shipped pic wherever the cloth swings out, and centring that wider box on the
# stock centre shifts the whole body a pixel sideways. The body must not move at
# all - that is the entire premise of the generated animations.
BW2, IDLE = 'bw2', 'idle'

TRAINERS = {
    'Roxanne':  ('TRAINER_PIC_LEADER_ROXANNE',  'leader_roxanne', BW2),
    'Brawley':  ('TRAINER_PIC_LEADER_BRAWLY',   'leader_brawly', BW2),
    'Wattson':  ('TRAINER_PIC_LEADER_WATTSON',  'leader_wattson', BW2),
    'Flannery': ('TRAINER_PIC_LEADER_FLANNERY', 'leader_flannery', BW2),
    'Norman':   ('TRAINER_PIC_LEADER_NORMAN',   'leader_norman', BW2),
    'Winona':   ('TRAINER_PIC_LEADER_WINONA',   'leader_winona', BW2),
    'Juan':     ('TRAINER_PIC_LEADER_JUAN',     'leader_juan', BW2),
    'Wallace':  ('TRAINER_PIC_CHAMPION_WALLACE', 'champion_wallace', BW2),
    'Steven':   ('TRAINER_PIC_STEVEN',          'steven', BW2),

    # The Elite Four are a genuine gap in B2W2 - they never appeared in it - so
    # these are generated from the shipped pics rather than ripped.
    'sidney':   ('TRAINER_PIC_ELITE_FOUR_SIDNEY', 'elite_four_sidney', IDLE),
    'phoebe':   ('TRAINER_PIC_ELITE_FOUR_PHOEBE', 'elite_four_phoebe', IDLE),
    'glacia':   ('TRAINER_PIC_ELITE_FOUR_GLACIA', 'elite_four_glacia', IDLE),
    'drake':    ('TRAINER_PIC_ELITE_FOUR_DRAKE',  'elite_four_drake', IDLE),
}


def trainer_pic_ids(repo):
    """TRAINER_PIC_X -> numeric id, read from the enum.

    Needed because the lookup table is bisected at runtime and therefore has to
    be in TRAINER_PIC order. The enum is contiguous with no explicit values, but
    it is parsed rather than counted from a listing so that an id inserted
    upstream moves this table with it.
    """
    out = {}
    text = (repo / 'include/constants/trainers.h').read_text(
        encoding='utf-8', errors='replace')
    m = re.search(r'enum\s+__attribute__\(\(packed\)\)\s+TrainerPicID\s*\{(.*?)\}',
                  text, re.S)
    if not m:
        raise SystemExit('could not find enum TrainerPicID in '
                         'include/constants/trainers.h')
    n = 0
    for e in re.finditer(r'(TRAINER_PIC_[A-Z0-9_]+)\s*(?:=\s*(\d+))?\s*,', m.group(1)):
        if e.group(2) is not None:
            n = int(e.group(2))
        out.setdefault(e.group(1), n)
        n += 1
    return out


def stock_bbox(repo, stem):
    """Bounding box of the shipped 64x64 trainer front pic.

    Read as INDEXED with palette entry 0 as the transparent one, which is the
    GBA's rule and what these PNGs actually encode. Converting to RGBA and
    taking the alpha channel looks equivalent and is not: the files carry no
    tRNS chunk, so every pixel comes back opaque and the box is the whole 64x64
    - which centres every trainer and is only visible in game as a leader
    standing slightly wrong.
    """
    p = repo / 'graphics/trainers/front_pics' / f'{stem}.png'
    if not p.exists():
        return None
    im = Image.open(p)
    if im.mode != 'P':
        return None
    px = im.load()
    x0, y0, x1, y1 = im.width, im.height, 0, 0
    for y in range(min(MON_PIC_HEIGHT, im.height)):
        for x in range(min(MON_PIC_WIDTH, im.width)):
            if px[x, y] != 0:
                x0, y0 = min(x0, x), min(y0, y)
                x1, y1 = max(x1, x + 1), max(y1, y + 1)
    return None if x1 <= x0 else (x0, y0, x1, y1)


def stock_placement(repo, stem, w, h):
    """Where in the 64x64 box to put a w x h frame: centre X, bottom Y.

    Bottom rather than centre for the same reason a battler is placed by its
    feet - see the module docstring's census. Falling back to a centred
    horizontal placement standing on the bottom keeps a trainer with no shipped
    pic (there is no such case today) plausible rather than floating.
    """
    box = stock_bbox(repo, stem)
    if box is None:
        return (MON_PIC_WIDTH - w) // 2, MON_PIC_HEIGHT - h
    x0, _y0, x1, y1 = box
    ox = round((x0 + x1) / 2 - w / 2)
    oy = y1 - h
    return (max(0, min(MON_PIC_WIDTH - w, ox)),
            max(0, min(MON_PIC_HEIGHT - h, oy)))


def read_native(gif_path):
    """Frames of an already-64x64, already-placed gif, read without touching them.

    Deliberately not D.build_species: that crops to the union box across frames
    and rescales, which is right for a rip of unknown size and wrong here. It
    does keep build_species' dedupe, because identical frames cost ROM and the
    hop generates only four distinct images across sixteen steps.
    """
    src = Image.open(gif_path)
    frames, seq, durs, seen = [], [], [], {}
    for fr in ImageSequence.Iterator(src):
        rgba = fr.convert('RGBA')
        if rgba.size != (MON_PIC_WIDTH, MON_PIC_HEIGHT):
            raise SystemExit(f'{gif_path} is {rgba.size}, native frames must be '
                             f'{MON_PIC_WIDTH}x{MON_PIC_HEIGHT}')
        key = rgba.tobytes()
        if key not in seen:
            seen[key] = len(frames)
            frames.append(rgba)
        seq.append(seen[key])
        durs.append(fr.info.get('duration', 0) or 0)
    cols = set()
    for f in frames:
        cols |= {c[:3] for c in f.getdata() if c[3] > 0}
    return frames, seq, durs, cols


def emit_trainer(repo, gif_path, stem, pic, stock_stem, source=BW2,
                 min_hold=DEFAULT_MIN_HOLD):
    built = (read_native(gif_path) if source == IDLE
             else D.build_species(str(gif_path)))
    if not built:
        return None, 'no frames'
    frames, seq, durs, cols = built
    if len(cols) > 15:
        return None, f'{len(cols)} colours (4bpp allows 15)'

    before = len(frames)
    if min_hold > 1:
        seq, durs = resample(seq, durs, min_hold)
        frames, seq = prune_frames(frames, seq)
    dropped = before - len(frames)

    if len(frames) > MAX_FRAMES:
        keep = set(range(MAX_FRAMES))
        seq = [s for s in seq if s in keep] or [0]
        frames = frames[:MAX_FRAMES]

    w, h = frames[0].size
    if w > MON_PIC_WIDTH or h > MON_PIC_HEIGHT:
        return None, f'{w}x{h} exceeds the {MON_PIC_WIDTH}x{MON_PIC_HEIGHT} OBJ limit'

    # EVERY frame is padded to the full 64x64 for the same reason the species
    # sheets are: the engine tiles a battle sprite as 8 tiles across, so a
    # narrower sheet shifts every tile row and smears diagonally rather than
    # drawing small. It is also what keeps frameSize a constant 2048, which is
    # what lets one chunk buffer size serve every trainer.
    tw, th = MON_PIC_WIDTH, MON_PIC_HEIGHT
    # A native frame IS the 64x64 canvas, so there is nothing to place.
    ox, oy = ((0, 0) if source == IDLE
              else stock_placement(repo, stock_stem, w, h))

    sheet = Image.new('RGBA', (tw, th * len(frames)), (0, 0, 0, 0))
    for i, f in enumerate(frames):
        sheet.paste(f, (ox, i * th + oy), f)

    got = sheet.getcolors(300000) or []
    palette = [(255, 0, 255)] + sorted({c[1][:3] for c in got if c[1][3] > 0})
    if len(palette) > 16:
        return None, f'{len(palette)-1} colours after packing'

    px = sheet.load()
    data = []
    for y in range(sheet.height):
        for x in range(sheet.width):
            c = px[x, y]
            data.append(0 if c[3] == 0 else palette.index(c[:3]))
    idx = Image.new('P', sheet.size, 0)
    idx.putdata(data)
    flat = []
    for c in palette + [(0, 0, 0)] * (16 - len(palette)):
        flat.extend(c)
    idx.putpalette(flat)

    asset = f'{stock_stem}_bw_anim.png'
    outdir = repo / 'graphics/trainers/front_pics'
    outdir.mkdir(parents=True, exist_ok=True)
    idx.save(outdir / asset)

    steps = []
    for i, s in enumerate(seq):
        hold = max(1, round((durs[i] if i < len(durs) else 100) / VIDEO_FRAME_MS))
        if steps and steps[-1][0] == s:
            steps[-1][1] = min(255, steps[-1][1] + hold)
        else:
            steps.append([s, min(255, hold)])

    if len(steps) > 255 or len(frames) > 255:
        return None, (f'{U8_OVERFLOW}: {len(frames)} frames / {len(steps)} '
                      f'steps exceeds the u8 table fields')

    return dict(stem=stem, pic=pic, sym=c_name(stock_stem), asset=asset,
                w=tw, h=th, frames=len(frames), steps=steps,
                dropped=dropped, scale=(w, h)), None


HEADER_DOC = """\
#ifndef GUARD_DATA_ROGUE_BW_TRAINER_ANIM_H
#define GUARD_DATA_ROGUE_BW_TRAINER_ANIM_H

// GENERATED by tools/rogue/emit_bw_trainer_anim.py - do not edit by hand.
//
// BW-style animated trainer front pics. A TRAINER_PIC listed here plays a
// frame sequence in place of its single static pic; one absent keeps the stock
// pic, so a partial roster is always a valid build.
//
// hold is in VIDEO FRAMES, converted from the source gif's milliseconds at
// emit time so nothing divides at runtime.
//
// ONE TABLE, NOT TWO. The species side needs a front and a back table because a
// species can have both and one species-sorted table would then hold duplicate
// keys. A trainer BACK pic is the player's own and is never one of these, so
// there is exactly one table here and it is keyed on TRAINER_PIC.
"""


def write_header(repo, built):
    built = sorted(built, key=lambda b: b['id'])
    L = HEADER_DOC.rstrip('\n').split('\n')
    L.append('')
    for b in built:
        L.append(f'const u32 gBwTrainerGfx_{b["sym"]}[] = INCGFX_U32('
                 f'"graphics/trainers/front_pics/{b["asset"]}", ".4bpp.fsmol");')
        L.append(f'const u16 gBwTrainerPal_{b["sym"]}[] = INCGFX_U16('
                 f'"graphics/trainers/front_pics/{b["asset"]}", ".gbapal");')
    L.append('')
    for b in built:
        L.append(f'static const struct BwAnimStep sBwTrainerSeq_{b["sym"]}[] =')
        L.append('{')
        for f, hold in b['steps']:
            L.append(f'    {{ {f}, {hold} }},')
        L.append('};')
        L.append('')

    L.append('// Sorted by TRAINER_PIC id - GetBwTrainerAnim bisects this.')
    L.append('static const struct BwTrainerAnim sBwTrainerAnims[] =')
    L.append('{')
    for b in built:
        L.append('    {')
        L.append(f'        .trainerPic = {b["pic"]},   // {b["id"]}')
        L.append(f'        .frames = gBwTrainerGfx_{b["sym"]},')
        L.append(f'        .palette = gBwTrainerPal_{b["sym"]},')
        L.append(f'        .seq = sBwTrainerSeq_{b["sym"]},')
        L.append(f'        .frameCount = {b["frames"]},')
        L.append(f'        .seqLength = {len(b["steps"])},')
        L.append(f'        .width = {b["w"]},')
        L.append(f'        .height = {b["h"]},')
        L.append('    },')
    if not built:
        L.append('    { .trainerPic = TRAINER_PIC_NONE },')
    L.append('};')
    L.append('')
    L.append('#endif // GUARD_DATA_ROGUE_BW_TRAINER_ANIM_H')

    p = repo / 'src/data/rogue_bw_trainer_anim.h'
    p.write_text('\n'.join(L) + '\n', encoding='utf-8', newline='\n')
    return p


def write_rules(repo, built, chunk):
    """One container rule per trainer.

    Explicit and per asset for the same reason the species rules are: the
    container needs the frame size in bytes and a flat 4bpp file does not carry
    one. A generic pattern rule that guessed would build a container whose
    frames were offset by a tile row, which is a garbled sprite rather than an
    error. A missing entry here fails the build with "no rule to make target",
    which is the failure worth having.
    """
    L = [
        '# GENERATED by tools/rogue/emit_bw_trainer_anim.py - do not edit by hand.',
        '#',
        '# BW animated trainer front pics. One rule per trainer, because -fw',
        '# takes the frame size in bytes and the frames per chunk, and neither',
        '# is recoverable from the 4bpp file.',
        '#',
        f'# Chunk size is {chunk}, matching the species containers so one chunk',
        '# buffer size serves both. See graphics/pokemon/bw_anim_rules.mk.',
        '',
    ]
    for b in sorted(built, key=lambda b: b['asset']):
        asset = f'$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/{b["asset"]}.4bpp'
        L.append(f'{asset}.fsmol: {asset}')
        L.append(f'\t$(SMOL) -fw $< $@ {b["w"] * b["h"] // 2} {chunk}')
        L.append('')

    p = repo / 'graphics/trainers/bw_trainer_anim_rules.mk'
    p.write_text('\n'.join(L), encoding='utf-8', newline='\n')
    return p


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--gifs', required=True,
                    help='directory of ripped B2W2 gifs')
    ap.add_argument('--idle-gifs',
                    help='directory of make_idle_anim.py output, for the '
                         'trainers the dump does not cover')
    ap.add_argument('--repo', default=str(Path(__file__).resolve().parents[2]))
    ap.add_argument('--only', help='comma-separated gif stems, default all')
    ap.add_argument('--chunk', type=int, default=2)
    ap.add_argument('--min-hold', type=int, default=DEFAULT_MIN_HOLD)
    args = ap.parse_args()

    repo = Path(args.repo)
    gifs = Path(args.gifs)
    ids = trainer_pic_ids(repo)

    want = TRAINERS
    if args.only:
        pick = [s.strip() for s in args.only.split(',') if s.strip()]
        missing = [p for p in pick if p not in TRAINERS]
        if missing:
            raise SystemExit(f'unknown trainer(s): {", ".join(missing)}. '
                             f'Known: {", ".join(sorted(TRAINERS))}')
        want = {k: TRAINERS[k] for k in pick}

    built, skipped = [], []
    for stem, (pic, stock_stem, source) in sorted(want.items()):
        if pic not in ids:
            # Fatal rather than skipped: a pic constant that is in no enum means
            # the map above is stale, and every other row is suspect with it.
            raise SystemExit(f'{stem}: {pic} is not in enum TrainerPicID')
        if source == IDLE:
            if not args.idle_gifs:
                # Skipped rather than fatal, so a run with only --gifs still
                # emits the nine ripped ones - but named in the summary, because
                # a roster that silently comes up short is this tool's own worst
                # failure mode.
                print(f'{stem:10s} SKIPPED: needs --idle-gifs')
                skipped.append((stem, 'needs --idle-gifs'))
                continue
            gp = Path(args.idle_gifs) / f'{stem}.gif'
        else:
            gp = gifs / f'{stem}.gif'
        if not gp.exists():
            print(f'{stem:10s} MISSING {gp}')
            skipped.append((stem, f'no gif at {gp}'))
            continue
        hold = args.min_hold
        info, err = emit_trainer(repo, gp, stem, pic, stock_stem, source, hold)
        # A sequence too long for the u8 fields means the rip is finer than the
        # runtime can address, not that the trainer should be dropped. Holding
        # each step longer merges steps until it fits.
        while err and err.startswith(U8_OVERFLOW) and hold < MAX_MIN_HOLD:
            hold += 1
            info, err = emit_trainer(repo, gp, stem, pic, stock_stem, source, hold)
        if err:
            print(f'{stem:10s} SKIPPED: {err}')
            skipped.append((stem, err))
            continue
        info['id'] = ids[pic]
        built.append(info)
        total = sum(h for _f, h in info['steps'])
        fps = 60.0 * len(info['steps']) / total if total else 0
        note = f'  min-hold raised to {hold}' if hold != args.min_hold else ''
        print(f'{stem:10s} {info["scale"][0]:2d}x{info["scale"][1]:<2d} in 64x64  '
              f'{info["frames"]:3d} frames  {len(info["steps"]):3d} steps  '
              f'{fps:4.1f} fps{note}')

    if skipped:
        print(f'\n{len(skipped)} of {len(want)} trainers were NOT emitted:')
        for stem, why in skipped:
            print(f'  {stem:10s} {why}')

    if built:
        print(f'\nwrote {write_header(repo, built)}')
        print(f'wrote {write_rules(repo, built, args.chunk)}')
        print(f'wrote {len(built)} assets under graphics/trainers/front_pics/')


if __name__ == '__main__':
    main()
