#!/usr/bin/env python3
"""Emit include/constants/rogue_evolution_levels.h -- one step down each chain.

Takes the repo POSITIONALLY. --write to emit, otherwise it prints a report.

WHY A GENERATED TABLE. The engine carries evolution data FORWARD only:
gSpeciesInfo[s].evolutions says what s becomes, never what became s. Devolving
a dealt encounter needs the reverse, and deriving it at run time means scanning
every species for one whose evolutions name the target -- per slot, per floor.
A table is smaller than the code that would avoid it and it can be checked.

The parser is IMPORTED from check_pool_evolutions rather than copied. Eleven
scripts are already duplicated between here and scripts/ and are drifting (gap
12); this is the one pair where a drift would be silent, because a min level
that disagreed with the check would make the check pass on a ROM that is still
wrong.

minLevel is CHAIN-AWARE and not just the last hop: Golem needs 25 because
Graveler does, even though Graveler -> Golem is a trade with no level at all.
Where a species has several routes in, the cheapest wins -- the player only
needs one of them.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from check_pool_evolutions import (  # noqa: E402
    build_prevo, min_level, read_babies, read_evolutions,
)

HEADER = """#ifndef GUARD_CONSTANTS_ROGUE_EVOLUTION_LEVELS_H
#define GUARD_CONSTANTS_ROGUE_EVOLUTION_LEVELS_H

// GENERATED by tools/rogue/gen_evolution_levels.py -- do not edit by hand.
//
// One entry per species that HAS a pre-evolution, sorted by species id so the
// lookup can bisect. minLevel is the lowest level at which that species could
// legitimately exist, walking the whole chain: Golem is 25 because Graveler is,
// even though Graveler -> Golem is a trade and carries no level of its own.
//
// Used by DevolveForLevel in rogue_dungeon.c, which walks preEvo down until the
// species is one the floor's level could actually have produced. See the
// encounter section of the architecture note.

struct RogueEvoStep
{
    u16 species;
    u16 preEvo;
    u8 minLevel;
};

static const struct RogueEvoStep sRogueEvoSteps[] =
{
"""

FOOTER = """};

#endif // GUARD_CONSTANTS_ROGUE_EVOLUTION_LEVELS_H
"""

OUT = "include/constants/rogue_evolution_levels.h"


def die(msg):
    print("gen_evolution_levels: %s" % msg, file=sys.stderr)
    sys.exit(2)


def in_rom(repo):
    """Species whose front pic survived the generation toggles.

    THE LINK MAP IS THE ONLY PROOF, which is the rule gen_safari_pool.py
    already follows and the one the diver parties were written without --
    eleven of fourteen slots named species that were not in the ROM, and a
    disabled family still compiles to a zeroed species_info row, so nothing
    said so. Without this filter the table would carry Aegislash, Appletun and
    Amoonguss: real enum constants, absent sprites, and 200-odd wasted entries.
    """
    import re
    path = repo / "pokeemerald.map"
    if not path.is_file():
        die("no pokeemerald.map -- build first; the link map is the only proof "
            "a species survived the generation toggles")
    text = path.read_text(encoding="utf-8", errors="replace")
    return {"SPECIES_" + m.upper()
            for m in re.findall(r"gMonFrontPic_([A-Za-z0-9_]+)", text)}


def build(repo):
    evo = read_evolutions(repo)

    # BABIES ARE EXCLUDED AS DEVOLVE TARGETS, and this is not tidiness. A baby
    # comes only from breeding and a run has no access to it -- the same reason
    # Cleffa is deliberately unreachable while Clefairy is a starter pick. Left
    # in, DevolveForLevel would put a Wynaut in the grass on an early floor,
    # which is a species the run is built never to hand out. Every other route
    # in stays available because build_prevo drops only the baby as a PARENT.
    prevo = build_prevo(evo, read_babies(repo))
    rom = in_rom(repo)

    rows = []
    for species in sorted(prevo):
        if species not in rom:
            continue
        parents = prevo[species]

        # The cheapest route in, matching min_level's own choice. Picking a
        # different parent here than min_level picked would give a species a
        # level from one chain and a step from another, and devolving would
        # walk a route the level was never computed for.
        best = None
        for src, method, param in parents:
            need = min_level(src, prevo)
            if method.startswith("EVO_LEVEL"):
                try:
                    need = max(need, int(param))
                except ValueError:
                    pass
            if best is None or need < best[0]:
                best = (need, src)

        need, src = best
        if need > 100:
            need = 100
        rows.append((species, src, need))
    return rows


def species_order(repo):
    """Enum order, so the emitted table is sorted the way the runtime bisects."""
    text = (repo / "include/constants/species.h").read_text(encoding="utf-8")
    order = {}
    idx = 0
    import re
    for m in re.finditer(r"^\s*(SPECIES_[A-Z0-9_]+)\s*(?:=|,)", text, re.M):
        name = m.group(1)
        if name not in order:
            order[name] = idx
            idx += 1
    return order


def emit(repo, rows):
    order = species_order(repo)
    unknown = [s for s, _, _ in rows if s not in order]
    if unknown:
        die("species not found in the enum, so they cannot be sorted: %s"
            % ", ".join(sorted(unknown)[:5]))

    rows = sorted(rows, key=lambda r: order[r[0]])

    body = []
    for species, pre, need in rows:
        body.append("    { %s, %s, %d },\n" % (species, pre, need))
    return HEADER + "".join(body) + FOOTER


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("-")]
    write = "--write" in argv[1:]
    if len(args) != 1:
        print(__doc__)
        die("usage: gen_evolution_levels.py <repo> [--write]")

    repo = Path(args[0])
    if not repo.is_dir():
        die("not a directory: %s" % repo)

    rows = build(repo)
    text = emit(repo, rows)

    levelled = sum(1 for _, _, n in rows if n > 0)
    print("gen_evolution_levels: %d species have a pre-evolution, %d of them "
          "carry a level requirement" % (len(rows), levelled))
    print("  table is %d bytes of ROM at 6 bytes an entry" % (len(rows) * 6))

    if write:
        (repo / OUT).write_text(text, encoding="utf-8", newline="\n")
        print("  wrote %s" % OUT)
    else:
        print("  --write to emit %s" % OUT)
        for species, pre, need in rows[:8]:
            print("    %-24s <- %-24s %3d" % (species, pre, need))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
