"""
Generate the starter selection data: a C table and the matching script text.

27 starters, Gen 1 through 9, each with the elemental attack of its type so a
pick is immediately usable rather than four turns of Tackle.

That move is a FALLBACK, not something forced into the moveset. Under Gen 9
learnsets at DUNGEON_STARTER_LEVEL, 21 of the 27 already know it from levelling,
so RogueDungeon_GiveChosenStarter skips it when it is already there and never
displaces an existing move to add it. Run check_starter_moves.py after changing
the starter level or P_LVL_UP_LEARNSETS.
"""
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

GRASS, FIRE, WATER = 'MOVE_VINE_WHIP', 'MOVE_EMBER', 'MOVE_WATER_GUN'
STARTERS = [
    ('BULBASAUR', 'Bulbasaur', GRASS), ('CHARMANDER', 'Charmander', FIRE), ('SQUIRTLE', 'Squirtle', WATER),
    ('CHIKORITA', 'Chikorita', GRASS), ('CYNDAQUIL', 'Cyndaquil', FIRE), ('TOTODILE', 'Totodile', WATER),
    ('TREECKO', 'Treecko', GRASS), ('TORCHIC', 'Torchic', FIRE), ('MUDKIP', 'Mudkip', WATER),
    ('TURTWIG', 'Turtwig', GRASS), ('CHIMCHAR', 'Chimchar', FIRE), ('PIPLUP', 'Piplup', WATER),
    ('SNIVY', 'Snivy', GRASS), ('TEPIG', 'Tepig', FIRE), ('OSHAWOTT', 'Oshawott', WATER),
    ('CHESPIN', 'Chespin', GRASS), ('FENNEKIN', 'Fennekin', FIRE), ('FROAKIE', 'Froakie', WATER),
    ('ROWLET', 'Rowlet', GRASS), ('LITTEN', 'Litten', FIRE), ('POPPLIO', 'Popplio', WATER),
    ('GROOKEY', 'Grookey', GRASS), ('SCORBUNNY', 'Scorbunny', FIRE), ('SOBBLE', 'Sobble', WATER),
    ('SPRIGATITO', 'Sprigatito', GRASS), ('FUECOCO', 'Fuecoco', FIRE), ('QUAXLY', 'Quaxly', WATER),
]

HDR = REPO / 'include/constants/rogue_dungeon_starters.h'
INC = REPO / 'data/maps/RogueDungeonFloor/starters.inc'


def main():
    lines = [
        '#ifndef GUARD_CONSTANTS_ROGUE_DUNGEON_STARTERS_H',
        '#define GUARD_CONSTANTS_ROGUE_DUNGEON_STARTERS_H',
        '',
        '// GENERATED by scratchpad/gen_starters.py - do not edit by hand.',
        '//',
        '// Every starter, Gen 1 through 9, in national order. Each carries the',
        '// elemental attack of its type so a fresh pick can actually fight.',
        '// Index order must match RogueDungeonFloor_Starters in starters.inc,',
        '// because the multichoice returns an index into this table.',
        '',
        'struct RogueDungeonStarter',
        '{',
        '    u16 species;',
        '    u16 move;',
        '};',
        '',
        'static const struct RogueDungeonStarter sRogueDungeonStarters[] =',
        '{',
    ]
    for i, (spec, name, move) in enumerate(STARTERS):
        lines.append(f'    {{ SPECIES_{spec}, {move} }},'.ljust(48) + f'// {i:>2} {name}')
    lines += ['};', '', '#endif // GUARD_CONSTANTS_ROGUE_DUNGEON_STARTERS_H', '']
    HDR.write_text('\n'.join(lines), encoding='utf-8', newline='\n')

    # script side: one label per name, plus the argv list for dynmultichoice
    s = ['@ GENERATED by scratchpad/gen_starters.py - do not edit by hand.',
         '@ Order must match sRogueDungeonStarters.', '']
    for spec, name, _ in STARTERS:
        s.append(f'RogueText_Starter{name}:')
        s.append(f'\t.string "{name}$"')
    # A callable routine rather than a .macro: inside a macro body GNU as reads
    # a trailing backslash as parameter syntax, not line continuation, so the
    # argument list cannot be wrapped. One long line it is.
    argv = ', '.join(f'RogueText_Starter{n}' for _, n, _ in STARTERS)
    s += [
        '',
        '@ Shows the full list and adds the choice to the party. Called once per',
        '@ starter the player gets to pick.',
        'RogueDungeonFloor_EventScript_PickStarter::',
        f'\tdynmultichoice 0, 0, TRUE, 6, 0, DYN_MULTICHOICE_CB_NONE, {argv}',
        '\tspecial RogueDungeon_GiveChosenStarter',
        '\treturn',
        '',
    ]
    INC.write_text('\n'.join(s), encoding='utf-8', newline='\n')

    print(f'wrote {HDR.name}: {len(STARTERS)} starters')
    print(f'wrote {INC.relative_to(REPO)}')


if __name__ == '__main__':
    main()
