"""Derive a PSG-only voicegroup from an existing one, by slot.

WHAT THIS IS FOR. m4a can already drive the GBA's four legacy PSG channels --
asm/macros/music_voice.inc defines voice_square_1/2, voice_programmable_wave and
voice_noise, and most stock voicegroups already use them. So a song can be made
to play "in Game Boy voice" without transcribing a single note: point it at a
voicegroup whose entries are all CGB voices. No demixing required.

WHAT IT CANNOT DO, AND WHY THE MAPPING IS HAND-WRITTEN. There are four PSG
channels and m4a assigns them by voice TYPE -- every square_1 voice wants
hardware channel 1. Two tracks holding square_1 voices at once contend, and m4a
resolves that by priority stealing, which sounds like dropouts rather than like
an arrangement. mus_petalburg_woods has NINE note-carrying tracks and is sounding
five or more of them 27% of the time, so parts have to be dropped, and choosing
which is a musical decision no heuristic makes reliably. That is the same wall a
hand demix hits; this tool just makes the decision cheap to express and revert.

Dropping a part is spelled as a silent voice: attack/decay/sustain/release all
zero never reaches an audible level.

Usage:  python3 tools/rogue/make_gb_voicegroup.py [--repo PATH]
"""
import argparse
import re
import sys
from pathlib import Path

SRC = 'sound/voicegroups/petalburg_woods.inc'
OUT = 'sound/voicegroups/gb_woods.inc'
NAME = 'gb_woods'

SILENT = 'voice_square_1_alt 60, 0, 0, 3, 0, 0, 0, 0'

# Slot -> replacement, derived from a census of mus_petalburg_woods.mid
# (track/slot/range/notes). Slots not listed are left exactly as they were --
# most of the group is unused filler, and four slots are already CGB voices
# doing the right thing.
MAPPING = {
    # slot: (replacement, why)
    0:  ('voice_noise_alt 60, 0, 0, 0, 1, 0, 1',
         'track 9, drumset keysplit -> a short noise hit. Shares the noise '
         'channel with track 8, but both are percussive and brief.'),
    1:  (SILENT,
         'track 2, piano keysplit, range 38-86, 42 notes. DROPPED - it doubles '
         'harmony the square parts already carry, and there is no channel free.'),
    45: (SILENT,
         'track 1, pizzicato strings, 56 notes. DROPPED for the same reason.'),
    48: (SILENT,
         'track 7, strings keysplit, 42 notes. DROPPED - a sustained pad would '
         'want the wave channel, which the bass on track 6 is already using.'),
    73: ('voice_square_1_alt 60, 0, 0, 2, 0, 0, 15, 1',
         'track 3, flute, range 74-99, 271 notes - FOUR TIMES any other part. '
         'This is the melody, so it takes square 1 at 50% duty with full '
         'sustain, the standard GB lead voice.'),
    82: (SILENT,
         'track 5, square_1_alt, range 50-82, 57 notes. DROPPED, and this is '
         'the non-obvious one: it was ALREADY a PSG part, but it holds square 1 '
         '- the channel the melody now needs. Keeping both would make the two '
         'steal the channel from each other.'),
    # 80 (track 4, square_2_alt) and 81 (track 6, programmable_wave_alt, the
    # bass) and 127 (track 8, noise_alt) are already correct and untouched.
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--repo', default='.', type=Path)
    args = ap.parse_args()

    src = (args.repo / SRC).read_text(encoding='utf-8').split('\n')

    header = src[0]
    if not header.startswith('voice_group '):
        sys.exit('%s does not start with a voice_group line' % SRC)

    out = ['@ GENERATED by tools/rogue/make_gb_voicegroup.py -- do not hand-edit.',
           '@',
           '@ A PSG-only rendering of voicegroup_petalburg_woods, so the same MIDI',
           '@ can play through the Game Boy sound channels with no transcription.',
           '@ See the tool for why four parts are dropped rather than remapped.',
           '',
           'voice_group %s' % NAME]

    slot = 0
    changed = 0
    for line in src[1:]:
        if not line.strip():
            continue
        if slot in MAPPING:
            repl, why = MAPPING[slot]
            for chunk in ('@ slot %d: %s' % (slot, why)).split('\n'):
                # wrap the reason at a sane width
                words, cur = chunk.split(), ''
                for w in words:
                    if len(cur) + len(w) + 1 > 76:
                        out.append('\t' + cur)
                        cur = '@ ' + w
                    else:
                        cur = (cur + ' ' + w).strip()
                out.append('\t' + cur)
            out.append('\t' + repl)
            changed += 1
        else:
            out.append(line.rstrip())
        slot += 1

    if changed != len(MAPPING):
        sys.exit('expected to replace %d slots but replaced %d -- the source '
                 'voicegroup changed shape' % (len(MAPPING), changed))

    out.append('')
    (args.repo / OUT).write_text('\n'.join(out), encoding='utf-8', newline='\n')
    print('wrote %s  (%d slots, %d replaced)' % (OUT, slot, changed))
    for s in sorted(MAPPING):
        kind = 'SILENT' if MAPPING[s][0] == SILENT else MAPPING[s][0].split()[0]
        print('  slot %3d -> %s' % (s, kind))
    return 0


if __name__ == '__main__':
    sys.exit(main())
