"""Wire a song's PSG rendering into the build, end to end and idempotently.

Converting one song by hand touches EIGHT files: the voicegroup, its include, a
duplicated MIDI, midi.cfg, gbs_songs.h, gbs_song_table.h, gbs_song_table.c and
song_table.inc. Doing that twelve times by hand is where a silent mistake gets
in -- a missed song_table row means the toggle simply does nothing for that
track, with no build error.

Re-running is safe: every edit checks for itself first, so adding a song later
does not disturb the ones already wired.

WHAT IT DOES NOT DO. It does not decide the arrangement. That comes from
plan_gb_arrangement.py, or from HAND_TUNED below for songs that were adjusted by
ear -- the woods track is one, and its mapping must not be regenerated from the
heuristic, which makes different (defensible, but not chosen) picks.

Usage:
  python3 tools/rogue/wire_gb_song.py --repo . --plans plans.json --songs a,b,c
  python3 tools/rogue/wire_gb_song.py --repo . --plans plans.json --all
"""
import argparse
import json
import re
import shutil
import sys
from pathlib import Path

SILENT = 'voice_square_1_alt 60, 0, 0, 3, 0, 0, 0, 0'

# Songs whose arrangement was tuned by ear. Never regenerate these from a plan.
HAND_TUNED = {'mus_petalburg_woods'}

VOICE_FOR = {
    'square1': 'voice_square_1_alt 60, 0, 0, %(duty)d, %(a)d, %(d)d, %(s)d, %(r)d',
    'square2': 'voice_square_2_alt 60, 0, %(duty)d, %(a)d, %(d)d, %(s)d, %(r)d',
    'wave':    'voice_programmable_wave_alt 60, 0, ProgrammableWaveData_6, '
               '%(a)d, %(d)d, %(s)d, %(r)d',
    'noise':   'voice_noise_alt 60, 0, 1, %(a)d, %(d)d, %(s)d, %(r)d',
}


def log(msg):
    print('    ' + msg)


def source_voicegroup(repo, song):
    cfg = (repo / 'sound/songs/midi/midi.cfg').read_text(encoding='utf-8')
    m = re.search(r'^%s\.mid:\s*(.*)$' % re.escape(song), cfg, re.M)
    if not m:
        return None, None
    g = re.search(r'-G(\S+)', m.group(1))
    if not g:
        return None, None
    stem = g.group(1).lstrip('_')
    return stem, repo / 'sound/voicegroups' / (stem + '.inc')


def write_voicegroup(repo, song, voices, out_stem):
    src_stem, src = source_voicegroup(repo, song)
    if src is None or not src.exists():
        return 'no source voicegroup for %s' % song
    lines = src.read_text(encoding='utf-8').split('\n')

    out = ['@ GENERATED by tools/rogue/wire_gb_song.py -- do not hand-edit.',
           '@',
           '@ PSG-only rendering of voicegroup_%s, so mus_%s can play through the'
           % (src_stem, song.replace('mus_', '')),
           '@ Game Boy sound channels with no transcription. Slots not listed in',
           '@ the arrangement are silenced: there are four channels and these',
           '@ songs have more parts than that.',
           '',
           'voice_group gb_%s' % out_stem]

    slot, replaced = 0, 0
    for line in lines[1:]:
        if not line.strip():
            continue
        v = voices.get(str(slot))
        if v is None:
            out.append(line.rstrip())
        else:
            kind = v['kind']
            if kind == 'drop':
                out.append('\t@ slot %d: %s' % (slot, v.get('name', 'dropped')))
                out.append('\t' + SILENT)
            else:
                out.append('\t@ slot %d: %s -> %s' % (slot, v.get('name', ''), kind))
                out.append('\t' + VOICE_FOR[kind] % v)
            replaced += 1
        slot += 1

    if replaced != len(voices):
        return ('plan names %d slots but the voicegroup only has %d of them'
                % (len(voices), replaced))

    out.append('')
    dest = repo / 'sound/voicegroups' / ('gb_%s.inc' % out_stem)
    dest.write_text('\n'.join(out), encoding='utf-8', newline='\n')
    log('voicegroup gb_%s.inc (%d slots, %d set)' % (out_stem, slot, replaced))
    return None


def ensure_line(path, needle, addition, after=None):
    """Insert `addition` once. Returns True if it changed the file."""
    txt = path.read_text(encoding='utf-8')
    if needle in txt:
        return False
    if after:
        idx = txt.rindex(after) + len(after)
        # Leading newline: the anchor is a whole line, so appending directly
        # ran the new declaration onto the end of it.
        txt = txt[:idx] + '\n' + addition.rstrip('\n') + txt[idx:]
    else:
        txt = txt.rstrip('\n') + '\n' + addition.lstrip('\n')
    path.write_text(txt, encoding='utf-8', newline='\n')
    return True


def wire(repo, song, spec, const):
    stem = song.replace('mus_', '')
    voices = spec['voices']

    if song not in HAND_TUNED:
        err = write_voicegroup(repo, song, voices, stem)
        if err:
            return err
    else:
        log('voicegroup left alone (hand tuned)')

    # The include.
    vg_inc = repo / 'sound/voice_groups.inc'
    if ensure_line(vg_inc, 'gb_%s.inc' % stem,
                   '.include "sound/voicegroups/gb_%s.inc"\n' % stem):
        log('include added')

    # The duplicated MIDI and its build line.
    mid = repo / 'sound/songs/midi' / (song + '.mid')
    gb_mid = repo / 'sound/songs/midi' / (song + '_gb.mid')
    if not gb_mid.exists():
        shutil.copyfile(mid, gb_mid)
        log('copied %s_gb.mid' % song)
    cfg = repo / 'sound/songs/midi/midi.cfg'
    if ensure_line(cfg, '%s_gb.mid:' % song,
                   '%s_gb.mid: -E -R50 -G_gb_%s -V080\n' % (song, stem)):
        log('midi.cfg entry added')

    # The GBS constant, inserted before the COUNT which then increments.
    songs_h = repo / 'include/constants/gbs_songs.h'
    txt = songs_h.read_text(encoding='utf-8')
    if const not in txt:
        m = re.search(r'#define GBS_MUSIC_COUNT (\d+)', txt)
        n = int(m.group(1))
        txt = txt.replace(m.group(0),
                          '#define %s %d\n\n#define GBS_MUSIC_COUNT %d'
                          % (const, n, n + 1))
        songs_h.write_text(txt, encoding='utf-8', newline='\n')
        log('%s = %d' % (const, n))

    # extern + table row.
    if ensure_line(repo / 'include/gbs_song_table.h', '%s_gb;' % song,
                   'extern const struct SongHeader %s_gb;\n' % song,
                   after='extern const struct SongHeader mus_petalburg_woods_gb;'):
        log('extern added')

    tbl = repo / 'src/gbs_song_table.c'
    txt = tbl.read_text(encoding='utf-8')
    if '%s_gb' % song not in txt:
        row = '    [%s] = SONG(%s_gb, 0),\n' % (const, song)
        idx = txt.rindex('};')
        txt = txt[:idx] + row + txt[idx:]
        tbl.write_text(txt, encoding='utf-8', newline='\n')
        log('song table row added')

    # The mapping that actually makes the toggle do something. Easiest thing to
    # forget, and it fails silently.
    st = repo / 'sound/song_table.inc'
    txt = st.read_text(encoding='utf-8')
    pat = re.compile(r'^(\tsong %s, [A-Z_0-9]+, )(\S+)$' % re.escape(song), re.M)
    m = pat.search(txt)
    if not m:
        return 'no song_table.inc row for %s' % song
    if m.group(2) != const:
        txt = pat.sub(lambda mm: mm.group(1) + const, txt, count=1)
        st.write_text(txt, encoding='utf-8', newline='\n')
        log('song_table row -> %s' % const)
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--repo', default='.', type=Path)
    ap.add_argument('--plans', required=True, type=Path)
    ap.add_argument('--songs', help='comma-separated plan names')
    ap.add_argument('--all', action='store_true')
    args = ap.parse_args()

    plans = json.loads(args.plans.read_text(encoding='utf-8'))
    if args.all:
        names = sorted(plans)
    elif args.songs:
        names = [s.strip() for s in args.songs.split(',') if s.strip()]
    else:
        sys.exit('need --songs or --all')

    bad = [n for n in names if n not in plans]
    if bad:
        sys.exit('not in %s: %s' % (args.plans, ', '.join(bad)))

    fails = 0
    for name in names:
        spec = plans[name]
        song = spec['song']
        const = 'GBS_MUSIC_%s_PSG' % name.upper()
        print('%s:' % song)
        err = wire(args.repo, song, spec, const)
        if err:
            print('    FAILED: %s' % err)
            fails += 1
    print('\n%d wired, %d failed' % (len(names) - fails, fails))
    return 1 if fails else 0


if __name__ == '__main__':
    sys.exit(main())
