#include "global.h"
#include "test/battle.h"
#include "data.h"
#include "decompress.h"
#include "rogue_bw_trainer_anim.h"
#include "constants/trainers.h"

// The nine emitted trainer pics: the eight Hoenn gym leaders this branch fights
// as dungeon bosses, minus Tate and Liza who share one pic and need a composite
// the rip does not provide, plus Wallace and Steven who are the last two bosses.
//
// WHAT A TEST CAN REACH HERE IS THE DATA, NOT THE SCREEN. Every runtime entry
// point is driven by the battle controllers during the intro, and the intro is
// exactly the part the headless runner skips - B_FAST_INTRO_NO_SLIDE and
// gTestRunnerHeadless both route the trainer sprite straight to
// SpriteCB_TrainerSpawn. So this asserts that every table row agrees with the
// container it names, which is the failure that is silent and out of bounds;
// whether the leader actually animates is a screen question.

TEST("BW trainer anim: every emitted pic resolves and agrees with its container")
{
    static const u16 pics[] = {
        TRAINER_PIC_LEADER_ROXANNE, TRAINER_PIC_LEADER_BRAWLY,
        TRAINER_PIC_LEADER_WATTSON, TRAINER_PIC_LEADER_FLANNERY,
        TRAINER_PIC_LEADER_NORMAN,  TRAINER_PIC_LEADER_WINONA,
        TRAINER_PIC_LEADER_JUAN,    TRAINER_PIC_CHAMPION_WALLACE,
        TRAINER_PIC_STEVEN,
        // The Elite Four are generated by tools/rogue/make_idle_anim.py rather
        // than ripped - B2W2 never had them - but they are the same containers
        // in the same table, so they are asserted the same way.
        TRAINER_PIC_ELITE_FOUR_SIDNEY, TRAINER_PIC_ELITE_FOUR_PHOEBE,
        TRAINER_PIC_ELITE_FOUR_GLACIA, TRAINER_PIC_ELITE_FOUR_DRAKE,
    };

    for (u32 i = 0; i < ARRAY_COUNT(pics); i++)
    {
        const struct BwTrainerAnim *anim = GetBwTrainerAnim(pics[i]);

        EXPECT(anim != NULL);
        if (anim == NULL)
            continue;

        EXPECT_EQ(anim->trainerPic, pics[i]);
        EXPECT_EQ(IsSmolFrameContainer(anim->frames), TRUE);

        // A trainer front pic is 64x64 like a battle sprite, and the frames are
        // padded to it. A pic emitted at its own bounding box instead would
        // still tile into VRAM eight tiles to a row and draw a diagonal smear.
        EXPECT_EQ(GetSmolFrameSize(anim->frames), MON_PIC_SIZE);
        EXPECT_EQ(anim->width, MON_PIC_WIDTH);
        EXPECT_EQ(anim->height, MON_PIC_HEIGHT);

        // The table bounds the sequence; the container is what gets indexed.
        // They have to agree or the runtime reads past the blob.
        EXPECT_EQ(GetSmolFrameCount(anim->frames), anim->frameCount);

        for (u32 s = 0; s < anim->seqLength; s++)
        {
            EXPECT(anim->seq[s].frame < anim->frameCount);
            // A hold of zero underflows the tick, which stores hold - 1 into a
            // u8 and would sit on one pose for 255 video frames.
            EXPECT(anim->seq[s].hold >= 1);
        }
    }
}

TEST("BW trainer anim: an unanimated pic misses rather than aliasing")
{
    // The bisect's failure mode is not an error, it is a WRONG ROW - which
    // would dress one leader in another's frames. Checked against a pic that
    // sits between two emitted ids rather than outside them all, because a
    // probe past the end of the table passes a broken bisect just as easily.
    EXPECT(GetBwTrainerAnim(TRAINER_PIC_LEADER_TATE_AND_LIZA) == NULL);
    EXPECT(GetBwTrainerAnim(TRAINER_PIC_NONE) == NULL);
    EXPECT(GetBwTrainerAnim(TRAINER_PIC_COUNT) == NULL);
}

TEST("BW trainer anim: a trainer sprite can only draw image frame 0")
{
    // PublishFrame writes ONE image slot, unlike the species path which fills
    // both because a mon's frontAnimFrames cycles frames 0 and 1. That is only
    // safe while every entry of gAnims_Trainer starts at frame 0. If this ever
    // fails, the trainer does not crash - it draws a stale pose.
    for (u32 i = 0; i < 2; i++)
    {
        // Copied out of the bitfield first: EXPECT_EQ takes a typeof of its
        // arguments, and typeof cannot be applied to a bit-field.
        u32 imageValue = gAnims_Trainer[i][0].frame.imageValue;

        EXPECT_EQ(imageValue, 0);
    }
}
