#ifndef GUARD_CONSTANTS_GBS_SONGS_H
#define GUARD_CONSTANTS_GBS_SONGS_H

#define GBS_MUSIC_NONE 0
#define GBS_MUSIC_VIRIDIAN_CITY 1
#define GBS_MUSIC_AZALEA_TOWN 2
#define GBS_MUSIC_VIOLET_CITY 3
#define GBS_MUSIC_LAKE_OF_RAGE 4
#define GBS_MUSIC_ROUTE_37 5

#define GBS_MUSIC_SUICUNE_BATTLE 6
#define GBS_MUSIC_MOBILE_CENTER 7

#define GBS_SFX_ITEM 8
#define GBS_SFX_LEVEL_UP 9
#define GBS_SFX_GET_TM 10
#define GBS_SFX_GET_BADGE 11

#define GBS_MUSIC_LAVENDER 12
#define GBS_MUSIC_TRAINER_BATTLE 13
#define GBS_MUSIC_BIKE_RIDING 14
#define GBS_MUSIC_RBY_TITLE_SCREEN 15
#define GBS_MUSIC_DUNGEON2 16
#define GBS_MUSIC_CINNABAR_MANSION 17
#define GBS_MUSIC_POKEMON_TOWER 18

#define GBS_MUSIC_ROUTE_101_RSE 19
#define GBS_MUSIC_ABANDONED_SHIP_RSE 20
#define GBS_MUSIC_OCEANIC_MUSEUM_RSE 21
#define GBS_MUSIC_MEW_BATTLE_RSE 22

// NOT a GBS-format track. This one is the ordinary m4a song built against a
// PSG-only voicegroup, so it plays through the Game Boy channels without being
// transcribed. gGBSSongTable only needs a song header, and an m4a header is one
// -- see the entry in gbs_song_table.c.
#define GBS_MUSIC_WOODS_M4A_PSG 23

#define GBS_MUSIC_VS_TRAINER_PSG 24

#define GBS_MUSIC_ENCOUNTER_AQUA_PSG 25

#define GBS_MUSIC_ENCOUNTER_COOL_PSG 26

#define GBS_MUSIC_ENCOUNTER_ELITE_FOUR_PSG 27

#define GBS_MUSIC_ENCOUNTER_FEMALE_PSG 28

#define GBS_MUSIC_ENCOUNTER_GIRL_PSG 29

#define GBS_MUSIC_ENCOUNTER_INTENSE_PSG 30

#define GBS_MUSIC_ENCOUNTER_MAGMA_PSG 31

#define GBS_MUSIC_ENCOUNTER_MALE_PSG 32

#define GBS_MUSIC_ENCOUNTER_MAY_PSG 33

#define GBS_MUSIC_ENCOUNTER_SUSPICIOUS_PSG 34

#define GBS_MUSIC_ENCOUNTER_TWINS_PSG 35

#define GBS_MUSIC_ENCOUNTER_BRENDAN_PSG 36

#define GBS_MUSIC_ENCOUNTER_CHAMPION_PSG 37

#define GBS_MUSIC_ENCOUNTER_HIKER_PSG 38

#define GBS_MUSIC_VS_CHAMPION_PSG 39

#define GBS_MUSIC_VS_ELITE_FOUR_PSG 40

#define GBS_MUSIC_VS_FRONTIER_BRAIN_PSG 41

#define GBS_MUSIC_VS_GYM_LEADER_PSG 42

#define GBS_MUSIC_UNDERWATER_PSG 43

#define GBS_MUSIC_SURF_PSG 44

#define GBS_MUSIC_ENCOUNTER_INTERVIEWER_PSG 45

#define GBS_MUSIC_ENCOUNTER_SWIMMER_PSG 46

#define GBS_MUSIC_COUNT 47

#endif  // GUARD_CONSTANTS_GBS_SONGS_H
