#ifndef GUARD_CONSTANTS_GBS_SONGS_H
#define GUARD_CONSTANTS_GBS_SONGS_H

#define GBS_MUSIC_NONE 0
#define GBS_MUSIC_VIRIDIAN_CITY 1
#define GBS_MUSIC_AZALEA_TOWN 2
#define GBS_MUSIC_VIOLET_CITY 3
#define GBS_MUSIC_LAKE_OF_RAGE 4
#define GBS_MUSIC_ROUTE_37 5

#define GBS_MUSIC_SUICUNE_BATTLE 6
#define GBS_MUSIC_MOBILE_CENTER 7

#define GBS_SFX_ITEM 8
#define GBS_SFX_LEVEL_UP 9
#define GBS_SFX_GET_TM 10
#define GBS_SFX_GET_BADGE 11

#define GBS_MUSIC_LAVENDER 12
#define GBS_MUSIC_TRAINER_BATTLE 13
#define GBS_MUSIC_BIKE_RIDING 14
#define GBS_MUSIC_RBY_TITLE_SCREEN 15
#define GBS_MUSIC_DUNGEON2 16
#define GBS_MUSIC_CINNABAR_MANSION 17
#define GBS_MUSIC_POKEMON_TOWER 18

#define GBS_MUSIC_ROUTE_101_RSE 19
#define GBS_MUSIC_ABANDONED_SHIP_RSE 20
#define GBS_MUSIC_OCEANIC_MUSEUM_RSE 21

#define GBS_MUSIC_COUNT 22

#endif  // GUARD_CONSTANTS_GBS_SONGS_H
