#ifndef GUARD_CONSTANTS_ROGUE_DUNGEON_STARTERS_H
#define GUARD_CONSTANTS_ROGUE_DUNGEON_STARTERS_H

// GENERATED by scratchpad/gen_starters.py - do not edit by hand.
//
// Every starter, Gen 1 through 9, in national order. Each carries the
// elemental attack of its type so a fresh pick can actually fight.
// Index order must match RogueDungeonFloor_Starters in starters.inc,
// because the multichoice returns an index into this table.

struct RogueDungeonStarter
{
    u16 species;
    u16 move;
};

static const struct RogueDungeonStarter sRogueDungeonStarters[] =
{
    { SPECIES_BULBASAUR, MOVE_VINE_WHIP },      //  0 Bulbasaur
    { SPECIES_CHARMANDER, MOVE_EMBER },         //  1 Charmander
    { SPECIES_SQUIRTLE, MOVE_WATER_GUN },       //  2 Squirtle
    { SPECIES_CHIKORITA, MOVE_VINE_WHIP },      //  3 Chikorita
    { SPECIES_CYNDAQUIL, MOVE_EMBER },          //  4 Cyndaquil
    { SPECIES_TOTODILE, MOVE_WATER_GUN },       //  5 Totodile
    { SPECIES_TREECKO, MOVE_VINE_WHIP },        //  6 Treecko
    { SPECIES_TORCHIC, MOVE_EMBER },            //  7 Torchic
    { SPECIES_MUDKIP, MOVE_WATER_GUN },         //  8 Mudkip
    { SPECIES_TURTWIG, MOVE_VINE_WHIP },        //  9 Turtwig
    { SPECIES_CHIMCHAR, MOVE_EMBER },           // 10 Chimchar
    { SPECIES_PIPLUP, MOVE_WATER_GUN },         // 11 Piplup
    { SPECIES_SNIVY, MOVE_VINE_WHIP },          // 12 Snivy
    { SPECIES_TEPIG, MOVE_EMBER },              // 13 Tepig
    { SPECIES_OSHAWOTT, MOVE_WATER_GUN },       // 14 Oshawott
    { SPECIES_CHESPIN, MOVE_VINE_WHIP },        // 15 Chespin
    { SPECIES_FENNEKIN, MOVE_EMBER },           // 16 Fennekin
    { SPECIES_FROAKIE, MOVE_WATER_GUN },        // 17 Froakie
    { SPECIES_ROWLET, MOVE_VINE_WHIP },         // 18 Rowlet
    { SPECIES_LITTEN, MOVE_EMBER },             // 19 Litten
    { SPECIES_POPPLIO, MOVE_WATER_GUN },        // 20 Popplio
    { SPECIES_GROOKEY, MOVE_VINE_WHIP },        // 21 Grookey
    { SPECIES_SCORBUNNY, MOVE_EMBER },          // 22 Scorbunny
    { SPECIES_SOBBLE, MOVE_WATER_GUN },         // 23 Sobble
    { SPECIES_SPRIGATITO, MOVE_VINE_WHIP },     // 24 Sprigatito
    { SPECIES_FUECOCO, MOVE_EMBER },            // 25 Fuecoco
    { SPECIES_QUAXLY, MOVE_WATER_GUN },         // 26 Quaxly
};

#endif // GUARD_CONSTANTS_ROGUE_DUNGEON_STARTERS_H
