#ifndef GUARD_CONSTANTS_ROGUE_DUNGEON_TRAINERS_H
#define GUARD_CONSTANTS_ROGUE_DUNGEON_TRAINERS_H

// GENERATED by tools/rogue/gen_trainer_table.py - do not edit by hand.
//
// Stock trainers usable as random dungeon opponents, sorted by average
// party level so a floor can pick one matching its target. Gym leaders,
// the Elite Four, rivals, admins and frontier brains are excluded: they
// are reserved for boss floors. 707 entries, levels 3-49.

struct RogueDungeonTrainer
{
    u16 trainerId;
    u8 avgLevel;
};

static const struct RogueDungeonTrainer sRogueDungeonTrainers[] =
{
    { TRAINER_LYLE, 3 },  // Bug Catcher, 4 mons
    { TRAINER_ALLEN, 4 },  // Youngster, 2 mons
    { TRAINER_RICK, 4 },  // Bug Catcher, 2 mons
    { TRAINER_TIANA, 4 },  // Lass, 2 mons
    { TRAINER_CALVIN_1, 5 },  // Youngster, 1 mon
    { TRAINER_BILLY, 6 },  // Youngster, 2 mons
    { TRAINER_HALEY_1, 6 },  // Lass, 2 mons
    { TRAINER_IVAN, 6 },  // Fisherman, 3 mons
    { TRAINER_JAMES_1, 6 },  // Bug Catcher, 2 mons
    { TRAINER_CINDY_1, 7 },  // Lady, 1 mon
    { TRAINER_WINSTON_1, 7 },  // Rich Boy, 1 mon
    { TRAINER_CLARK, 8 },  // Hiker, 1 mon
    { TRAINER_DAWSON, 8 },  // Rich Boy, 2 mons
    { TRAINER_DEVAN, 8 },  // Hiker, 2 mons
    { TRAINER_JOHNSON, 8 },  // Youngster, 2 mons
    { TRAINER_JOSE, 8 },  // Bug Catcher, 2 mons
    { TRAINER_MARC, 8 },  // Hiker, 2 mons
    { TRAINER_SARAH, 8 },  // Lady, 2 mons
    { TRAINER_TOMMY, 8 },  // Youngster, 2 mons
    { TRAINER_DARIAN, 9 },  // Fisherman, 1 mon
    { TRAINER_ELLIOT_1, 9 },  // Fisherman, 3 mons
    { TRAINER_GRUNT_PETALBURG_WOODS, 9 },  // Team Aqua, 1 mon
    { TRAINER_JACOB, 9 },  // Triathlete, 3 mons
    { TRAINER_JANICE, 9 },  // Lass, 1 mon
    { TRAINER_JERRY_1, 9 },  // School Kid, 1 mon
    { TRAINER_JOEY, 9 },  // Youngster, 1 mon
    { TRAINER_KAREN_1, 9 },  // School Kid, 1 mon
    { TRAINER_LUCAS_2, 9 },  // Hiker, 1 mon
    { TRAINER_ANDREW, 10 },  // Fisherman, 3 mons
    { TRAINER_JOSH, 10 },  // Youngster, 1 mon
    { TRAINER_MIKE_1, 10 },  // Hiker, 2 mons
    { TRAINER_CINDY_2, 11 },  // Lady, 1 mon
    { TRAINER_DWAYNE, 11 },  // Sailor, 3 mons
    { TRAINER_GRUNT_RUSTURF_TUNNEL, 11 },  // Team Aqua, 1 mon
    { TRAINER_ISAAC_1, 11 },  // Pkmn Breeder, 6 mons
    { TRAINER_JASMINE, 11 },  // Triathlete, 3 mons
    { TRAINER_LYDIA_1, 11 },  // Pkmn Breeder, 6 mons
    { TRAINER_NED, 11 },  // Fisherman, 1 mon
    { TRAINER_CHANDLER, 12 },  // Tuber M, 2 mons
    { TRAINER_DALE, 12 },  // Fisherman, 4 mons
    { TRAINER_HUEY, 12 },  // Sailor, 2 mons
    { TRAINER_LOLA_1, 12 },  // Tuber F, 2 mons
    { TRAINER_SIMON, 12 },  // Tuber M, 2 mons
    { TRAINER_BRENDEN, 13 },  // Sailor, 1 mon
    { TRAINER_CRISTIAN, 13 },  // Black Belt, 1 mon
    { TRAINER_EDMOND, 13 },  // Sailor, 1 mon
    { TRAINER_HAILEY, 13 },  // Tuber F, 1 mon
    { TRAINER_JOCELYN, 13 },  // Battle Girl, 1 mon
    { TRAINER_JOHANNA, 13 },  // Beauty, 1 mon
    { TRAINER_LAURA, 13 },  // Battle Girl, 1 mon
    { TRAINER_LILITH, 13 },  // Battle Girl, 1 mon
    { TRAINER_RICKY_1, 13 },  // Tuber M, 1 mon
    { TRAINER_TAKAO, 13 },  // Black Belt, 1 mon
    { TRAINER_ANTHONY, 14 },  // Triathlete, 2 mons
    { TRAINER_DAISY, 14 },  // Aroma Lady, 2 mons
    { TRAINER_DEANDRE, 14 },  // Youngster, 3 mons
    { TRAINER_EDWIN_1, 14 },  // Collector, 2 mons
    { TRAINER_GRUNT_MUSEUM_2, 14 },  // Team Aqua, 2 mons
    { TRAINER_ISABEL_1, 14 },  // Pokefan, 2 mons
    { TRAINER_JOSEPH, 14 },  // Guitarist, 2 mons
    { TRAINER_KALEB, 14 },  // Pokefan, 2 mons
    { TRAINER_ROBIN, 14 },  // Lass, 3 mons
    { TRAINER_ROSE_1, 14 },  // Aroma Lady, 3 mons
    { TRAINER_TIMMY, 14 },  // Youngster, 2 mons
    { TRAINER_ALYSSA, 15 },  // Triathlete, 1 mon
    { TRAINER_DALTON_1, 15 },  // Guitarist, 2 mons
    { TRAINER_EDDIE, 15 },  // Youngster, 2 mons
    { TRAINER_EDWARD, 15 },  // Psychic, 1 mon
    { TRAINER_GRUNT_MUSEUM_1, 15 },  // Team Aqua, 1 mon
    { TRAINER_ISABELLE, 15 },  // Swimmer F, 1 mon
    { TRAINER_MARCOS, 15 },  // Guitarist, 1 mon
    { TRAINER_MIGUEL_1, 15 },  // Pokefan, 1 mon
    { TRAINER_PAUL, 15 },  // School Kid, 3 mons
    { TRAINER_PETE, 15 },  // Swimmer M, 1 mon
    { TRAINER_RHETT, 15 },  // Black Belt, 1 mon
    { TRAINER_VIVI, 15 },  // Winstrate, 3 mons
    { TRAINER_ABIGAIL_1, 16 },  // Triathlete, 1 mon
    { TRAINER_BENJAMIN_1, 16 },  // Triathlete, 1 mon
    { TRAINER_DEREK, 16 },  // Bug Maniac, 2 mons
    { TRAINER_GEORGIA, 16 },  // School Kid, 2 mons
    { TRAINER_JACLYN, 16 },  // Psychic, 1 mon
    { TRAINER_MIKE_2, 16 },  // Hiker, 3 mons
    { TRAINER_SALLY, 16 },  // Lass, 1 mon
    { TRAINER_TRENT_1, 16 },  // Hiker, 3 mons
    { TRAINER_VICTOR, 16 },  // Winstrate, 2 mons
    { TRAINER_WADE, 16 },  // Fisherman, 1 mon
    { TRAINER_AISHA, 17 },  // Battle Girl, 1 mon
    { TRAINER_ANGELO, 17 },  // Bug Maniac, 2 mons
    { TRAINER_BEN, 17 },  // Youngster, 2 mons
    { TRAINER_BRANDI, 17 },  // Psychic, 1 mon
    { TRAINER_BRICE, 17 },  // Hiker, 2 mons
    { TRAINER_BROOKE_1, 17 },  // Cooltrainer, 3 mons
    { TRAINER_CAROL, 17 },  // Picnicker, 2 mons
    { TRAINER_CLAUDE, 17 },  // Fisherman, 3 mons
    { TRAINER_DYLAN_1, 17 },  // Triathlete, 1 mon
    { TRAINER_IRENE, 17 },  // Picnicker, 2 mons
    { TRAINER_KIRK, 17 },  // Guitarist, 2 mons
    { TRAINER_LAO_1, 17 },  // Ninja Boy, 3 mons
    { TRAINER_MARIA_1, 17 },  // Triathlete, 1 mon
    { TRAINER_MELINA, 17 },  // Triathlete, 1 mon
    { TRAINER_SHAWN, 17 },  // Guitarist, 2 mons
    { TRAINER_TED, 17 },  // School Kid, 1 mon
    { TRAINER_VICTORIA, 17 },  // Winstrate, 1 mon
    { TRAINER_VIVIAN, 17 },  // Battle Girl, 2 mons
    { TRAINER_WILTON_1, 17 },  // Cooltrainer, 3 mons
    { TRAINER_ANGELINA, 18 },  // Picnicker, 2 mons
    { TRAINER_BERNIE_1, 18 },  // Kindler, 2 mons
    { TRAINER_BIANCA, 18 },  // Picnicker, 1 mon
    { TRAINER_BRYANT, 18 },  // Kindler, 2 mons
    { TRAINER_CELINA, 18 },  // Aroma Lady, 1 mon
    { TRAINER_COBY, 18 },  // Bird Keeper, 2 mons
    { TRAINER_CYNDY_1, 18 },  // Battle Girl, 2 mons
    { TRAINER_HAYDEN, 18 },  // Kindler, 1 mon
    { TRAINER_HECTOR, 18 },  // Collector, 2 mons
    { TRAINER_LARRY, 18 },  // Camper, 1 mon
    { TRAINER_LAWRENCE, 18 },  // Camper, 2 mons
    { TRAINER_LENNY, 18 },  // Hiker, 2 mons
    { TRAINER_LUCAS_1, 18 },  // Hiker, 2 mons
    { TRAINER_LUNG, 18 },  // Ninja Boy, 2 mons
    { TRAINER_MARLENE, 18 },  // Psychic, 2 mons
    { TRAINER_NANCY, 18 },  // Picnicker, 2 mons
    { TRAINER_SHANE, 18 },  // Camper, 2 mons
    { TRAINER_SHAYLA, 18 },  // Aroma Lady, 2 mons
    { TRAINER_SOPHIE, 18 },  // Picnicker, 2 mons
    { TRAINER_TRAVIS, 18 },  // Camper, 1 mon
    { TRAINER_VICKY, 18 },  // Winstrate, 1 mon
    { TRAINER_WYATT, 18 },  // Pokemaniac, 2 mons
    { TRAINER_CHARLOTTE, 19 },  // Picnicker, 1 mon
    { TRAINER_DAISUKE, 19 },  // Black Belt, 1 mon
    { TRAINER_DIANA_1, 19 },  // Picnicker, 3 mons
    { TRAINER_DILLON, 19 },  // Youngster, 1 mon
    { TRAINER_JAYLEN, 19 },  // Youngster, 1 mon
    { TRAINER_KAI, 19 },  // Fisherman, 1 mon
    { TRAINER_MADELINE_1, 19 },  // Parasol Lady, 1 mon
    { TRAINER_NOB_1, 19 },  // Black Belt, 1 mon
    { TRAINER_NOLAN, 19 },  // Fisherman, 1 mon
    { TRAINER_STEVE_1, 19 },  // Pokemaniac, 1 mon
    { TRAINER_TYRON, 19 },  // Camper, 1 mon
    { TRAINER_ERIC, 20 },  // Hiker, 2 mons
    { TRAINER_ETHAN_1, 20 },  // Camper, 2 mons
    { TRAINER_GRUNT_MT_CHIMNEY_1, 20 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MT_CHIMNEY_2, 20 },  // Team Magma, 1 mon
    { TRAINER_AUTUMN, 21 },  // Picnicker, 1 mon
    { TRAINER_BEAU, 21 },  // Camper, 3 mons
    { TRAINER_JULIO, 21 },  // Triathlete, 1 mon
    { TRAINER_MELISSA, 21 },  // Beauty, 1 mon
    { TRAINER_SAWYER_1, 21 },  // Hiker, 1 mon
    { TRAINER_SHEILA, 21 },  // Beauty, 1 mon
    { TRAINER_SHELBY_1, 21 },  // Expert, 2 mons
    { TRAINER_SHIRLEY, 21 },  // Beauty, 1 mon
    { TRAINER_ALAN, 22 },  // Hiker, 3 mons
    { TRAINER_BECKY, 22 },  // Picnicker, 2 mons
    { TRAINER_BRANDEN, 22 },  // Camper, 2 mons
    { TRAINER_BRYAN, 22 },  // Ruin Maniac, 2 mons
    { TRAINER_CELIA, 22 },  // Picnicker, 2 mons
    { TRAINER_GRUNT_JAGGED_PASS, 22 },  // Team Magma, 2 mons
    { TRAINER_HEIDI, 22 },  // Picnicker, 2 mons
    { TRAINER_ISAAC_2, 22 },  // Pkmn Breeder, 6 mons
    { TRAINER_JEFF, 22 },  // Kindler, 2 mons
    { TRAINER_LYDIA_2, 22 },  // Pkmn Breeder, 6 mons
    { TRAINER_AXLE, 23 },  // Kindler, 1 mon
    { TRAINER_COLE, 23 },  // Kindler, 1 mon
    { TRAINER_DANIELLE, 23 },  // Battle Girl, 1 mon
    { TRAINER_DREW, 23 },  // Camper, 1 mon
    { TRAINER_DUSTY_1, 23 },  // Ruin Maniac, 1 mon
    { TRAINER_ELI, 23 },  // Hiker, 1 mon
    { TRAINER_GERALD, 23 },  // Cooltrainer, 1 mon
    { TRAINER_JACE, 23 },  // Kindler, 1 mon
    { TRAINER_KEEGAN, 23 },  // Kindler, 1 mon
    { TRAINER_MARTHA, 23 },  // Picnicker, 2 mons
    { TRAINER_ALICE, 24 },  // Swimmer F, 3 mons
    { TRAINER_CAROLINA, 24 },  // Cooltrainer, 3 mons
    { TRAINER_CHRIS, 24 },  // Fisherman, 4 mons
    { TRAINER_CORY_1, 24 },  // Sailor, 3 mons
    { TRAINER_DARRIN, 24 },  // Swimmer M, 3 mons
    { TRAINER_DONALD, 24 },  // Bug Maniac, 3 mons
    { TRAINER_DOUGLAS, 24 },  // Swimmer M, 2 mons
    { TRAINER_JUSTIN, 24 },  // Camper, 1 mon
    { TRAINER_LAO_2, 24 },  // Ninja Boy, 4 mons
    { TRAINER_TRENT_2, 24 },  // Hiker, 4 mons
    { TRAINER_ANDRES_1, 25 },  // Ruin Maniac, 2 mons
    { TRAINER_BARNY, 25 },  // Fisherman, 2 mons
    { TRAINER_BEVERLY, 25 },  // Swimmer F, 2 mons
    { TRAINER_CARTER, 25 },  // Fisherman, 2 mons
    { TRAINER_CHESTER, 25 },  // Bird Keeper, 2 mons
    { TRAINER_DALTON_2, 25 },  // Guitarist, 3 mons
    { TRAINER_DAVID, 25 },  // Swimmer M, 2 mons
    { TRAINER_DAYTON, 25 },  // Kindler, 2 mons
    { TRAINER_DEMETRIUS, 25 },  // Youngster, 2 mons
    { TRAINER_DENISE, 25 },  // Swimmer F, 2 mons
    { TRAINER_DIANA_2, 25 },  // Picnicker, 3 mons
    { TRAINER_DUNCAN, 25 },  // Sailor, 2 mons
    { TRAINER_ELIJAH, 25 },  // Bird Keeper, 2 mons
    { TRAINER_FOSTER, 25 },  // Ruin Maniac, 2 mons
    { TRAINER_GREG, 25 },  // Bug Catcher, 2 mons
    { TRAINER_HIDEO, 25 },  // Ninja Boy, 2 mons
    { TRAINER_HUGH, 25 },  // Bird Keeper, 2 mons
    { TRAINER_ISAAC_3, 25 },  // Pkmn Breeder, 6 mons
    { TRAINER_JOSUE, 25 },  // Bird Keeper, 2 mons
    { TRAINER_KENT, 25 },  // Bug Catcher, 1 mon
    { TRAINER_LYDIA_3, 25 },  // Pkmn Breeder, 6 mons
    { TRAINER_MYLES, 25 },  // Pkmn Breeder, 6 mons
    { TRAINER_PAT, 25 },  // Pkmn Breeder, 6 mons
    { TRAINER_ROGER, 25 },  // Fisherman, 3 mons
    { TRAINER_TAKASHI, 25 },  // Ninja Boy, 2 mons
    { TRAINER_TARA, 25 },  // Swimmer F, 2 mons
    { TRAINER_THALIA_1, 25 },  // Beauty, 2 mons
    { TRAINER_ALEXIA, 26 },  // Cooltrainer, 1 mon
    { TRAINER_ALIX, 26 },  // Psychic, 2 mons
    { TRAINER_AUSTINA, 26 },  // Tuber F, 1 mon
    { TRAINER_BERKE, 26 },  // Cooltrainer, 1 mon
    { TRAINER_BERNIE_2, 26 },  // Kindler, 2 mons
    { TRAINER_BETH, 26 },  // Swimmer F, 1 mon
    { TRAINER_BRENT, 26 },  // Bug Maniac, 1 mon
    { TRAINER_BROOKE_2, 26 },  // Cooltrainer, 3 mons
    { TRAINER_CAMRON, 26 },  // Triathlete, 1 mon
    { TRAINER_CATHERINE_1, 26 },  // Pkmn Ranger, 2 mons
    { TRAINER_CHARLIE, 26 },  // Tuber M, 1 mon
    { TRAINER_CYNDY_2, 26 },  // Battle Girl, 2 mons
    { TRAINER_DOMINIK, 26 },  // Swimmer M, 1 mon
    { TRAINER_EDWIN_2, 26 },  // Collector, 2 mons
    { TRAINER_ELLIOT_2, 26 },  // Fisherman, 3 mons
    { TRAINER_ETHAN_2, 26 },  // Camper, 2 mons
    { TRAINER_FABIAN, 26 },  // Guitarist, 1 mon
    { TRAINER_GABRIELLE_1, 26 },  // Pkmn Breeder, 6 mons
    { TRAINER_GARRISON, 26 },  // Ruin Maniac, 1 mon
    { TRAINER_GEORGE, 26 },  // Cooltrainer, 1 mon
    { TRAINER_GRUNT_WEATHER_INST_3, 26 },  // Team Aqua, 3 mons
    { TRAINER_GWEN, 26 },  // Tuber F, 1 mon
    { TRAINER_HALEY_2, 26 },  // Lass, 2 mons
    { TRAINER_HELENE, 26 },  // Battle Girl, 2 mons
    { TRAINER_IMANI, 26 },  // Swimmer F, 1 mon
    { TRAINER_ISABEL_2, 26 },  // Pokefan, 2 mons
    { TRAINER_JAIDEN, 26 },  // Ninja Boy, 2 mons
    { TRAINER_JANI, 26 },  // Tuber F, 1 mon
    { TRAINER_JEROME, 26 },  // Swimmer M, 1 mon
    { TRAINER_JERRY_2, 26 },  // School Kid, 2 mons
    { TRAINER_JODY, 26 },  // Cooltrainer, 1 mon
    { TRAINER_KAREN_2, 26 },  // School Kid, 2 mons
    { TRAINER_KAYLA, 26 },  // Psychic, 3 mons
    { TRAINER_KOICHI, 26 },  // Black Belt, 2 mons
    { TRAINER_KYLA, 26 },  // Swimmer F, 1 mon
    { TRAINER_KYRA, 26 },  // Triathlete, 2 mons
    { TRAINER_LOLA_2, 26 },  // Tuber F, 2 mons
    { TRAINER_LUIS, 26 },  // Swimmer M, 1 mon
    { TRAINER_MARY, 26 },  // Cooltrainer, 1 mon
    { TRAINER_MATTHEW, 26 },  // Swimmer M, 1 mon
    { TRAINER_MISSY, 26 },  // Swimmer F, 1 mon
    { TRAINER_PARKER, 26 },  // Cooltrainer, 1 mon
    { TRAINER_PERRY, 26 },  // Bird Keeper, 1 mon
    { TRAINER_PHIL, 26 },  // Bird Keeper, 1 mon
    { TRAINER_RACHEL, 26 },  // Parasol Lady, 1 mon
    { TRAINER_RANDALL, 26 },  // Cooltrainer, 1 mon
    { TRAINER_RONALD, 26 },  // Fisherman, 6 mons
    { TRAINER_ROSE_2, 26 },  // Aroma Lady, 2 mons
    { TRAINER_SAWYER_2, 26 },  // Hiker, 2 mons
    { TRAINER_TONY_1, 26 },  // Swimmer M, 1 mon
    { TRAINER_VIOLET, 26 },  // Aroma Lady, 2 mons
    { TRAINER_WILLIAM, 26 },  // Psychic, 3 mons
    { TRAINER_WILTON_2, 26 },  // Cooltrainer, 3 mons
    { TRAINER_YASU, 26 },  // Ninja Boy, 1 mon
    { TRAINER_YUJI, 26 },  // Black Belt, 2 mons
    { TRAINER_ASHLEY, 27 },  // Picnicker, 3 mons
    { TRAINER_CALVIN_2, 27 },  // Youngster, 1 mon
    { TRAINER_CHIP, 27 },  // Ruin Maniac, 3 mons
    { TRAINER_CINDY_3, 27 },  // Lady, 1 mon
    { TRAINER_CORA, 27 },  // Battle Girl, 1 mon
    { TRAINER_DAVIS, 27 },  // Bug Catcher, 1 mon
    { TRAINER_DUSTY_2, 27 },  // Ruin Maniac, 1 mon
    { TRAINER_GRUNT_WEATHER_INST_1, 27 },  // Team Aqua, 2 mons
    { TRAINER_GRUNT_WEATHER_INST_2, 27 },  // Team Aqua, 2 mons
    { TRAINER_GRUNT_WEATHER_INST_5, 27 },  // Team Aqua, 2 mons
    { TRAINER_JACKSON_1, 27 },  // Pkmn Ranger, 1 mon
    { TRAINER_JAMES_2, 27 },  // Bug Catcher, 1 mon
    { TRAINER_JARED, 27 },  // Bird Keeper, 3 mons
    { TRAINER_JAZMYN, 27 },  // Cooltrainer 2, 1 mon
    { TRAINER_JEFFREY_1, 27 },  // Bug Maniac, 3 mons
    { TRAINER_NOB_2, 27 },  // Black Belt, 1 mon
    { TRAINER_PAULA, 27 },  // Battle Girl, 1 mon
    { TRAINER_RICKY_2, 27 },  // Tuber M, 1 mon
    { TRAINER_STEVE_2, 27 },  // Pokemaniac, 1 mon
    { TRAINER_TAYLOR, 27 },  // Bug Maniac, 3 mons
    { TRAINER_TIMOTHY_1, 27 },  // Expert, 1 mon
    { TRAINER_TRENT_3, 27 },  // Hiker, 4 mons
    { TRAINER_WINSTON_2, 27 },  // Rich Boy, 1 mon
    { TRAINER_ABIGAIL_2, 28 },  // Triathlete, 1 mon
    { TRAINER_BRAXTON, 28 },  // Cooltrainer, 5 mons
    { TRAINER_CALLIE, 28 },  // Battle Girl, 2 mons
    { TRAINER_CLARISSA, 28 },  // Parasol Lady, 2 mons
    { TRAINER_COLIN, 28 },  // Bird Keeper, 2 mons
    { TRAINER_DALTON_3, 28 },  // Guitarist, 3 mons
    { TRAINER_DIANA_3, 28 },  // Picnicker, 3 mons
    { TRAINER_DOUG, 28 },  // Bug Catcher, 2 mons
    { TRAINER_DYLAN_2, 28 },  // Triathlete, 1 mon
    { TRAINER_ELLIOT_3, 28 },  // Fisherman, 4 mons
    { TRAINER_GRUNT_MAGMA_HIDEOUT_4, 28 },  // Team Magma, 2 mons
    { TRAINER_GRUNT_MAGMA_HIDEOUT_5, 28 },  // Team Magma, 2 mons
    { TRAINER_GRUNT_SPACE_CENTER_2, 28 },  // Team Magma, 3 mons
    { TRAINER_GRUNT_WEATHER_INST_4, 28 },  // Team Aqua, 1 mon
    { TRAINER_ISAAC_4, 28 },  // Pkmn Breeder, 6 mons
    { TRAINER_JENNA, 28 },  // Pkmn Ranger, 3 mons
    { TRAINER_KEIGO, 28 },  // Ninja Boy, 2 mons
    { TRAINER_LAO_3, 28 },  // Ninja Boy, 4 mons
    { TRAINER_LORENZO, 28 },  // Pkmn Ranger, 3 mons
    { TRAINER_LYDIA_4, 28 },  // Pkmn Breeder, 6 mons
    { TRAINER_MARIA_2, 28 },  // Triathlete, 1 mon
    { TRAINER_RILEY, 28 },  // Ninja Boy, 2 mons
    { TRAINER_ROSE_3, 28 },  // Aroma Lady, 3 mons
    { TRAINER_SAWYER_3, 28 },  // Hiker, 3 mons
    { TRAINER_BERNIE_3, 29 },  // Kindler, 2 mons
    { TRAINER_BROOKE_3, 29 },  // Cooltrainer, 3 mons
    { TRAINER_CALE, 29 },  // Bug Maniac, 2 mons
    { TRAINER_CALVIN_3, 29 },  // Youngster, 2 mons
    { TRAINER_CRISTIN_1, 29 },  // Cooltrainer, 2 mons
    { TRAINER_CYNDY_3, 29 },  // Battle Girl, 2 mons
    { TRAINER_EDWARDO, 29 },  // Bird Keeper, 2 mons
    { TRAINER_EDWIN_3, 29 },  // Collector, 2 mons
    { TRAINER_ETHAN_3, 29 },  // Camper, 2 mons
    { TRAINER_FLINT, 29 },  // Camper, 2 mons
    { TRAINER_GRUNT_MAGMA_HIDEOUT_1, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_10, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_11, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_12, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_13, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_14, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_15, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_16, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_2, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_3, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_6, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_7, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_8, 29 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_MAGMA_HIDEOUT_9, 29 },  // Team Magma, 1 mon
    { TRAINER_HALEY_3, 29 },  // Lass, 2 mons
    { TRAINER_ISABEL_3, 29 },  // Pokefan, 2 mons
    { TRAINER_JAMES_3, 29 },  // Bug Catcher, 2 mons
    { TRAINER_JERRY_3, 29 },  // School Kid, 2 mons
    { TRAINER_JESSICA_1, 29 },  // Beauty, 2 mons
    { TRAINER_KAREN_3, 29 },  // School Kid, 2 mons
    { TRAINER_LOLA_3, 29 },  // Tuber F, 2 mons
    { TRAINER_MADELINE_2, 29 },  // Parasol Lady, 1 mon
    { TRAINER_MARCEL, 29 },  // Cooltrainer, 2 mons
    { TRAINER_MIGUEL_2, 29 },  // Pokefan, 1 mon
    { TRAINER_NOB_3, 29 },  // Black Belt, 2 mons
    { TRAINER_ROBERT_1, 29 },  // Bird Keeper, 1 mon
    { TRAINER_STEVE_3, 29 },  // Pokemaniac, 2 mons
    { TRAINER_TAMMY, 29 },  // Hex Maniac, 2 mons
    { TRAINER_WALTER_1, 29 },  // Gentleman, 1 mon
    { TRAINER_WENDY, 29 },  // Cooltrainer, 3 mons
    { TRAINER_WILTON_3, 29 },  // Cooltrainer, 3 mons
    { TRAINER_ALBERTO, 30 },  // Bird Keeper, 2 mons
    { TRAINER_ALLISON, 30 },  // Triathlete, 2 mons
    { TRAINER_ANGELICA, 30 },  // Parasol Lady, 1 mon
    { TRAINER_BENJAMIN_2, 30 },  // Triathlete, 1 mon
    { TRAINER_CATHERINE_2, 30 },  // Pkmn Ranger, 2 mons
    { TRAINER_CHASE, 30 },  // Triathlete, 2 mons
    { TRAINER_CINDY_4, 30 },  // Lady, 1 mon
    { TRAINER_COLTON, 30 },  // Pokefan, 6 mons
    { TRAINER_CORY_2, 30 },  // Sailor, 3 mons
    { TRAINER_DARIUS, 30 },  // Bird Keeper, 1 mon
    { TRAINER_DONNY, 30 },  // Triathlete, 2 mons
    { TRAINER_DUSTY_3, 30 },  // Ruin Maniac, 1 mon
    { TRAINER_ED, 30 },  // Collector, 2 mons
    { TRAINER_ELLIOT_4, 30 },  // Fisherman, 4 mons
    { TRAINER_FERNANDO_1, 30 },  // Guitarist, 2 mons
    { TRAINER_FREDRICK, 30 },  // Expert, 2 mons
    { TRAINER_GRUNT_MT_PYRE_3, 30 },  // Team Aqua, 2 mons
    { TRAINER_GRUNT_MT_PYRE_4, 30 },  // Team Aqua, 2 mons
    { TRAINER_HUMBERTO, 30 },  // Bird Keeper, 1 mon
    { TRAINER_JACKI_1, 30 },  // Psychic, 2 mons
    { TRAINER_JENNIFER, 30 },  // Cooltrainer, 1 mon
    { TRAINER_KINDRA, 30 },  // Hex Maniac, 2 mons
    { TRAINER_LAO_4, 30 },  // Ninja Boy, 4 mons
    { TRAINER_LEONEL, 30 },  // Cooltrainer, 1 mon
    { TRAINER_RICKY_3, 30 },  // Tuber M, 1 mon
    { TRAINER_SAWYER_4, 30 },  // Hiker, 3 mons
    { TRAINER_SHELBY_2, 30 },  // Expert, 2 mons
    { TRAINER_TONY_2, 30 },  // Swimmer M, 1 mon
    { TRAINER_TRENT_4, 30 },  // Hiker, 4 mons
    { TRAINER_VANESSA, 30 },  // Pokefan, 1 mon
    { TRAINER_WINSTON_3, 30 },  // Rich Boy, 1 mon
    { TRAINER_ABIGAIL_3, 31 },  // Triathlete, 1 mon
    { TRAINER_ANDRES_2, 31 },  // Ruin Maniac, 2 mons
    { TRAINER_CALVIN_4, 31 },  // Youngster, 3 mons
    { TRAINER_CAMERON_1, 31 },  // Psychic, 1 mon
    { TRAINER_DALTON_4, 31 },  // Guitarist, 3 mons
    { TRAINER_DEAN, 31 },  // Swimmer M, 3 mons
    { TRAINER_DIANA_4, 31 },  // Picnicker, 3 mons
    { TRAINER_DYLAN_3, 31 },  // Triathlete, 1 mon
    { TRAINER_ETHAN_4, 31 },  // Camper, 3 mons
    { TRAINER_GABRIELLE_2, 31 },  // Pkmn Breeder, 6 mons
    { TRAINER_GRUNT_AQUA_HIDEOUT_2, 31 },  // Team Aqua, 2 mons
    { TRAINER_GRUNT_AQUA_HIDEOUT_7, 31 },  // Team Aqua, 2 mons
    { TRAINER_GRUNT_SPACE_CENTER_3, 31 },  // Team Magma, 2 mons
    { TRAINER_GRUNT_UNUSED, 31 },  // Team Magma, 2 mons
    { TRAINER_ISAAC_5, 31 },  // Pkmn Breeder, 6 mons
    { TRAINER_JACKSON_2, 31 },  // Pkmn Ranger, 1 mon
    { TRAINER_JAMES_4, 31 },  // Bug Catcher, 3 mons
    { TRAINER_JEFFREY_2, 31 },  // Bug Maniac, 3 mons
    { TRAINER_JONAH, 31 },  // Fisherman, 3 mons
    { TRAINER_JONAS, 31 },  // Ninja Boy, 1 mon
    { TRAINER_KAYLEY, 31 },  // Parasol Lady, 1 mon
    { TRAINER_LEAH, 31 },  // Hex Maniac, 1 mon
    { TRAINER_LYDIA_5, 31 },  // Pkmn Breeder, 6 mons
    { TRAINER_MARIA_3, 31 },  // Triathlete, 1 mon
    { TRAINER_MARK, 31 },  // Pokemaniac, 1 mon
    { TRAINER_NOB_4, 31 },  // Black Belt, 3 mons
    { TRAINER_ROSE_4, 31 },  // Aroma Lady, 3 mons
    { TRAINER_VALERIE_2, 31 },  // Hex Maniac, 2 mons
    { TRAINER_ZANDER, 31 },  // Black Belt, 1 mon
    { TRAINER_AIDAN, 32 },  // Bird Keeper, 2 mons
    { TRAINER_ATHENA, 32 },  // Cooltrainer, 2 mons
    { TRAINER_ATSUSHI, 32 },  // Black Belt, 1 mon
    { TRAINER_BERNIE_4, 32 },  // Kindler, 2 mons
    { TRAINER_BROOKE_4, 32 },  // Cooltrainer, 3 mons
    { TRAINER_CEDRIC, 32 },  // Psychic, 1 mon
    { TRAINER_CORY_3, 32 },  // Sailor, 3 mons
    { TRAINER_CYNDY_4, 32 },  // Battle Girl, 2 mons
    { TRAINER_EDWIN_4, 32 },  // Collector, 2 mons
    { TRAINER_GRUNT_AQUA_HIDEOUT_1, 32 },  // Team Aqua, 1 mon
    { TRAINER_GRUNT_AQUA_HIDEOUT_3, 32 },  // Team Aqua, 1 mon
    { TRAINER_GRUNT_AQUA_HIDEOUT_4, 32 },  // Team Aqua, 1 mon
    { TRAINER_GRUNT_AQUA_HIDEOUT_5, 32 },  // Team Aqua, 1 mon
    { TRAINER_GRUNT_AQUA_HIDEOUT_6, 32 },  // Team Aqua, 1 mon
    { TRAINER_GRUNT_AQUA_HIDEOUT_8, 32 },  // Team Aqua, 1 mon
    { TRAINER_GRUNT_MT_PYRE_1, 32 },  // Team Aqua, 1 mon
    { TRAINER_GRUNT_MT_PYRE_2, 32 },  // Team Aqua, 1 mon
    { TRAINER_GRUNT_SPACE_CENTER_1, 32 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_SPACE_CENTER_4, 32 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_SPACE_CENTER_5, 32 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_SPACE_CENTER_6, 32 },  // Team Magma, 1 mon
    { TRAINER_GRUNT_SPACE_CENTER_7, 32 },  // Team Magma, 1 mon
    { TRAINER_HALEY_4, 32 },  // Lass, 2 mons
    { TRAINER_HENRY, 32 },  // Fisherman, 2 mons
    { TRAINER_HITOSHI, 32 },  // Black Belt, 2 mons
    { TRAINER_ISABEL_4, 32 },  // Pokefan, 2 mons
    { TRAINER_JERRY_4, 32 },  // School Kid, 2 mons
    { TRAINER_KAREN_4, 32 },  // School Kid, 2 mons
    { TRAINER_LOLA_4, 32 },  // Tuber F, 2 mons
    { TRAINER_MADELINE_3, 32 },  // Parasol Lady, 1 mon
    { TRAINER_MIGUEL_3, 32 },  // Pokefan, 1 mon
    { TRAINER_ROBERT_2, 32 },  // Bird Keeper, 2 mons
    { TRAINER_STEVE_4, 32 },  // Pokemaniac, 2 mons
    { TRAINER_TASHA, 32 },  // Hex Maniac, 1 mon
    { TRAINER_VALERIE_1, 32 },  // Hex Maniac, 1 mon
    { TRAINER_WILTON_4, 32 },  // Cooltrainer, 3 mons
    { TRAINER_ALEX, 33 },  // Bird Keeper, 2 mons
    { TRAINER_ANDRES_3, 33 },  // Ruin Maniac, 3 mons
    { TRAINER_AURON, 33 },  // Expert, 2 mons
    { TRAINER_BENJAMIN_3, 33 },  // Triathlete, 1 mon
    { TRAINER_CAMDEN, 33 },  // Triathlete, 2 mons
    { TRAINER_CAMERON_2, 33 },  // Psychic, 2 mons
    { TRAINER_CATHERINE_3, 33 },  // Pkmn Ranger, 2 mons
    { TRAINER_CHAD, 33 },  // Swimmer M, 2 mons
    { TRAINER_CINDY_5, 33 },  // Lady, 1 mon
    { TRAINER_CONOR, 33 },  // Expert, 2 mons
    { TRAINER_DARCY, 33 },  // Cooltrainer, 2 mons
    { TRAINER_DUDLEY, 33 },  // Swimmer M, 3 mons
    { TRAINER_DUSTY_4, 33 },  // Ruin Maniac, 1 mon
    { TRAINER_ERNEST_1, 33 },  // Sailor, 2 mons
    { TRAINER_GABRIELLE_3, 33 },  // Pkmn Breeder, 6 mons
    { TRAINER_HERMAN, 33 },  // Swimmer M, 2 mons
    { TRAINER_JAMES_5, 33 },  // Bug Catcher, 4 mons
    { TRAINER_JONATHAN, 33 },  // Cooltrainer, 2 mons
    { TRAINER_KATIE, 33 },  // Swimmer F, 2 mons
    { TRAINER_KELVIN, 33 },  // Sailor, 2 mons
    { TRAINER_LAUREL, 33 },  // Swimmer F, 2 mons
    { TRAINER_LINDA, 33 },  // Swimmer F, 2 mons
    { TRAINER_MAKAYLA, 33 },  // Expert, 2 mons
    { TRAINER_MOLLIE, 33 },  // Expert, 2 mons
    { TRAINER_NIKKI, 33 },  // Swimmer F, 2 mons
    { TRAINER_NOB_5, 33 },  // Black Belt, 4 mons
    { TRAINER_PABLO_1, 33 },  // Triathlete, 2 mons
    { TRAINER_PAXTON, 33 },  // Expert, 2 mons
    { TRAINER_PRESLEY, 33 },  // Bird Keeper, 2 mons
    { TRAINER_REED, 33 },  // Swimmer M, 2 mons
    { TRAINER_REYNA, 33 },  // Battle Girl, 2 mons
    { TRAINER_RICKY_4, 33 },  // Tuber M, 1 mon
    { TRAINER_SANTIAGO, 33 },  // Swimmer M, 2 mons
    { TRAINER_SAWYER_5, 33 },  // Hiker, 3 mons
    { TRAINER_SHELBY_3, 33 },  // Expert, 2 mons
    { TRAINER_SIENNA, 33 },  // Swimmer F, 2 mons
    { TRAINER_SPENCER, 33 },  // Swimmer M, 2 mons
    { TRAINER_TIMOTHY_2, 33 },  // Expert, 1 mon
    { TRAINER_TONY_3, 33 },  // Swimmer M, 1 mon
    { TRAINER_TRENT_5, 33 },  // Hiker, 4 mons
    { TRAINER_WARREN, 33 },  // Cooltrainer, 2 mons
    { TRAINER_WAYNE, 33 },  // Fisherman, 3 mons
    { TRAINER_WINSTON_4, 33 },  // Rich Boy, 1 mon
    { TRAINER_AARON, 34 },  // Dragon Tamer, 1 mon
    { TRAINER_ABIGAIL_4, 34 },  // Triathlete, 1 mon
    { TRAINER_ALEXA, 34 },  // Cooltrainer, 2 mons
    { TRAINER_BARRY, 34 },  // Swimmer M, 1 mon
    { TRAINER_BECK, 34 },  // Bird Keeper, 1 mon
    { TRAINER_BRENDA, 34 },  // Swimmer F, 1 mon
    { TRAINER_BROOKE_5, 34 },  // Cooltrainer, 3 mons
    { TRAINER_CALVIN_5, 34 },  // Youngster, 3 mons
    { TRAINER_CLARENCE, 34 },  // Swimmer M, 1 mon
    { TRAINER_CORY_4, 34 },  // Sailor, 3 mons
    { TRAINER_DALTON_5, 34 },  // Guitarist, 3 mons
    { TRAINER_DANA, 34 },  // Swimmer F, 1 mon
    { TRAINER_DEBRA, 34 },  // Swimmer F, 1 mon
    { TRAINER_DECLAN, 34 },  // Swimmer M, 1 mon
    { TRAINER_DYLAN_4, 34 },  // Triathlete, 1 mon
    { TRAINER_ELLIOT_5, 34 },  // Fisherman, 4 mons
    { TRAINER_ETHAN_5, 34 },  // Camper, 3 mons
    { TRAINER_FRANKLIN, 34 },  // Swimmer M, 1 mon
    { TRAINER_GILBERT, 34 },  // Swimmer M, 1 mon
    { TRAINER_GRACE, 34 },  // Swimmer F, 1 mon
    { TRAINER_HALEY_5, 34 },  // Lass, 3 mons
    { TRAINER_HUDSON, 34 },  // Sailor, 1 mon
    { TRAINER_ISABELLA, 34 },  // Triathlete, 1 mon
    { TRAINER_ISOBEL, 34 },  // Triathlete, 1 mon
    { TRAINER_JACK, 34 },  // Swimmer M, 1 mon
    { TRAINER_JACKI_2, 34 },  // Psychic, 2 mons
    { TRAINER_JACKSON_3, 34 },  // Pkmn Ranger, 1 mon
    { TRAINER_JEFFREY_3, 34 },  // Bug Maniac, 3 mons
    { TRAINER_JENNY_1, 34 },  // Swimmer F, 1 mon
    { TRAINER_JERRY_5, 34 },  // School Kid, 3 mons
    { TRAINER_KARA, 34 },  // Swimmer F, 1 mon
    { TRAINER_KAYLEE, 34 },  // Swimmer F, 2 mons
    { TRAINER_KEVIN, 34 },  // Swimmer M, 1 mon
    { TRAINER_KIYO, 34 },  // Black Belt, 1 mon
    { TRAINER_KOJI_1, 34 },  // Black Belt, 1 mon
    { TRAINER_LAO_5, 34 },  // Ninja Boy, 4 mons
    { TRAINER_LEONARDO, 34 },  // Swimmer M, 1 mon
    { TRAINER_MADELINE_4, 34 },  // Parasol Lady, 2 mons
    { TRAINER_MARIA_4, 34 },  // Triathlete, 1 mon
    { TRAINER_MARLEY, 34 },  // Cooltrainer, 1 mon
    { TRAINER_NOLEN, 34 },  // Swimmer M, 1 mon
    { TRAINER_RICHARD, 34 },  // Swimmer M, 1 mon
    { TRAINER_RODNEY, 34 },  // Swimmer M, 1 mon
    { TRAINER_ROLAND, 34 },  // Swimmer M, 1 mon
    { TRAINER_ROSE_5, 34 },  // Aroma Lady, 3 mons
    { TRAINER_RUBEN, 34 },  // Cooltrainer, 2 mons
    { TRAINER_SHARON, 34 },  // Swimmer F, 1 mon
    { TRAINER_STAN, 34 },  // Swimmer M, 1 mon
    { TRAINER_SUSIE, 34 },  // Swimmer F, 1 mon
    { TRAINER_TALIA, 34 },  // Triathlete, 1 mon
    { TRAINER_TANYA, 34 },  // Swimmer F, 1 mon
    { TRAINER_THALIA_2, 34 },  // Beauty, 2 mons
    { TRAINER_TISHA, 34 },  // Swimmer F, 1 mon
    { TRAINER_WALTER_2, 34 },  // Gentleman, 1 mon
    { TRAINER_ANDRES_4, 35 },  // Ruin Maniac, 3 mons
    { TRAINER_BERNIE_5, 35 },  // Kindler, 2 mons
    { TRAINER_CARLEE, 35 },  // Swimmer F, 1 mon
    { TRAINER_CRISTIN_2, 35 },  // Cooltrainer, 2 mons
    { TRAINER_CYNDY_5, 35 },  // Battle Girl, 2 mons
    { TRAINER_EDWIN_5, 35 },  // Collector, 2 mons
    { TRAINER_FERNANDO_2, 35 },  // Guitarist, 3 mons
    { TRAINER_GABRIELLE_4, 35 },  // Pkmn Breeder, 6 mons
    { TRAINER_GRUNT_SEAFLOOR_CAVERN_5, 35 },  // Team Aqua, 2 mons
    { TRAINER_HARRISON, 35 },  // Swimmer M, 1 mon
    { TRAINER_ISABEL_5, 35 },  // Pokefan, 2 mons
    { TRAINER_ISAIAH_1, 35 },  // Triathlete, 1 mon
    { TRAINER_JESSICA_2, 35 },  // Beauty, 2 mons
    { TRAINER_KAREN_5, 35 },  // School Kid, 2 mons
    { TRAINER_KATELYN_1, 35 },  // Triathlete, 1 mon
    { TRAINER_LOLA_5, 35 },  // Tuber F, 2 mons
    { TRAINER_MIGUEL_4, 35 },  // Pokefan, 1 mon
    { TRAINER_ROBERT_3, 35 },  // Bird Keeper, 2 mons
    { TRAINER_STEVE_5, 35 },  // Pokemaniac, 2 mons
    { TRAINER_TONY_4, 35 },  // Swimmer M, 2 mons
    { TRAINER_VALERIE_3, 35 },  // Hex Maniac, 2 mons
    { TRAINER_WILTON_5, 35 },  // Cooltrainer, 3 mons
    { TRAINER_BENJAMIN_4, 36 },  // Triathlete, 1 mon
    { TRAINER_BENNY, 36 },  // Bird Keeper, 3 mons
    { TRAINER_BLAKE, 36 },  // Psychic, 1 mon
    { TRAINER_CATHERINE_4, 36 },  // Pkmn Ranger, 2 mons
    { TRAINER_CINDY_6, 36 },  // Lady, 1 mon
    { TRAINER_CLIFFORD, 36 },  // Gentleman, 1 mon
    { TRAINER_CORY_5, 36 },  // Sailor, 3 mons
    { TRAINER_DUSTY_5, 36 },  // Ruin Maniac, 1 mon
    { TRAINER_ERNEST_2, 36 },  // Sailor, 3 mons
    { TRAINER_GRUNT_SEAFLOOR_CAVERN_1, 36 },  // Team Aqua, 1 mon
    { TRAINER_GRUNT_SEAFLOOR_CAVERN_2, 36 },  // Team Aqua, 1 mon
    { TRAINER_GRUNT_SEAFLOOR_CAVERN_3, 36 },  // Team Aqua, 1 mon
    { TRAINER_GRUNT_SEAFLOOR_CAVERN_4, 36 },  // Team Aqua, 1 mon
    { TRAINER_HANNAH, 36 },  // Psychic, 1 mon
    { TRAINER_JEFFREY_4, 36 },  // Bug Maniac, 4 mons
    { TRAINER_KATHLEEN, 36 },  // Hex Maniac, 1 mon
    { TRAINER_MACEY, 36 },  // Psychic, 1 mon
    { TRAINER_MAURA, 36 },  // Psychic, 1 mon
    { TRAINER_NATE, 36 },  // Gentleman, 1 mon
    { TRAINER_NICHOLAS, 36 },  // Psychic, 1 mon
    { TRAINER_PRESTON, 36 },  // Psychic, 1 mon
    { TRAINER_RICKY_5, 36 },  // Tuber M, 1 mon
    { TRAINER_SAMANTHA, 36 },  // Psychic, 1 mon
    { TRAINER_SHELBY_4, 36 },  // Expert, 2 mons
    { TRAINER_SYLVIA, 36 },  // Hex Maniac, 1 mon
    { TRAINER_THALIA_3, 36 },  // Beauty, 3 mons
    { TRAINER_TIMOTHY_3, 36 },  // Expert, 1 mon
    { TRAINER_VIRGIL, 36 },  // Psychic, 1 mon
    { TRAINER_WALTER_3, 36 },  // Gentleman, 2 mons
    { TRAINER_WINSTON_5, 36 },  // Rich Boy, 1 mon
    { TRAINER_ABIGAIL_5, 37 },  // Triathlete, 1 mon
    { TRAINER_ANDRES_5, 37 },  // Ruin Maniac, 3 mons
    { TRAINER_BETHANY, 37 },  // Pokefan, 3 mons
    { TRAINER_CRISTIN_3, 37 },  // Cooltrainer, 3 mons
    { TRAINER_DYLAN_5, 37 },  // Triathlete, 1 mon
    { TRAINER_FERNANDO_3, 37 },  // Guitarist, 3 mons
    { TRAINER_GABRIELLE_5, 37 },  // Pkmn Breeder, 6 mons
    { TRAINER_JACKI_3, 37 },  // Psychic, 2 mons
    { TRAINER_JACKSON_4, 37 },  // Pkmn Ranger, 1 mon
    { TRAINER_KOJI_2, 37 },  // Black Belt, 2 mons
    { TRAINER_MADELINE_5, 37 },  // Parasol Lady, 2 mons
    { TRAINER_MARIA_5, 37 },  // Triathlete, 1 mon
    { TRAINER_NICOLAS_1, 37 },  // Dragon Tamer, 2 mons
    { TRAINER_OLIVIA, 37 },  // Beauty, 3 mons
    { TRAINER_PABLO_2, 37 },  // Triathlete, 2 mons
    { TRAINER_TERRY, 37 },  // Psychic, 1 mon
    { TRAINER_CAMERON_3, 38 },  // Psychic, 2 mons
    { TRAINER_JEFFREY_5, 38 },  // Bug Maniac, 5 mons
    { TRAINER_JENNY_2, 38 },  // Swimmer F, 1 mon
    { TRAINER_JESSICA_3, 38 },  // Beauty, 2 mons
    { TRAINER_MIGUEL_5, 38 },  // Pokefan, 1 mon
    { TRAINER_ROBERT_4, 38 },  // Bird Keeper, 2 mons
    { TRAINER_SOPHIA, 38 },  // Pkmn Ranger, 2 mons
    { TRAINER_THALIA_4, 38 },  // Beauty, 3 mons
    { TRAINER_TONY_5, 38 },  // Swimmer M, 2 mons
    { TRAINER_ANNIKA, 39 },  // Pokefan, 2 mons
    { TRAINER_BENJAMIN_5, 39 },  // Triathlete, 1 mon
    { TRAINER_CATHERINE_5, 39 },  // Pkmn Ranger, 2 mons
    { TRAINER_CRISSY, 39 },  // Lass, 2 mons
    { TRAINER_CRISTIN_4, 39 },  // Cooltrainer, 3 mons
    { TRAINER_DAPHNE, 39 },  // Lady, 2 mons
    { TRAINER_ERNEST_3, 39 },  // Sailor, 3 mons
    { TRAINER_FERNANDO_4, 39 },  // Guitarist, 3 mons
    { TRAINER_ISAIAH_2, 39 },  // Triathlete, 1 mon
    { TRAINER_JACKSON_5, 39 },  // Pkmn Ranger, 2 mons
    { TRAINER_KATELYN_2, 39 },  // Triathlete, 1 mon
    { TRAINER_KOJI_3, 39 },  // Black Belt, 3 mons
    { TRAINER_PABLO_3, 39 },  // Triathlete, 3 mons
    { TRAINER_SEBASTIAN, 39 },  // Pkmn Ranger, 1 mon
    { TRAINER_SHELBY_5, 39 },  // Expert, 2 mons
    { TRAINER_TIFFANY, 39 },  // Beauty, 2 mons
    { TRAINER_TIMOTHY_4, 39 },  // Expert, 1 mon
    { TRAINER_WALTER_4, 39 },  // Gentleman, 2 mons
    { TRAINER_ANDREA, 40 },  // Lass, 1 mon
    { TRAINER_BRIANNA, 40 },  // Lady, 1 mon
    { TRAINER_BRIDGET, 40 },  // Beauty, 1 mon
    { TRAINER_CONNIE, 40 },  // Beauty, 1 mon
    { TRAINER_DIANA_5, 40 },  // Picnicker, 3 mons
    { TRAINER_JACKI_4, 40 },  // Psychic, 2 mons
    { TRAINER_THALIA_5, 40 },  // Beauty, 3 mons
    { TRAINER_VALERIE_4, 40 },  // Hex Maniac, 2 mons
    { TRAINER_ALEXIS, 41 },  // Psychic, 2 mons
    { TRAINER_ALVARO, 41 },  // Psychic, 2 mons
    { TRAINER_CAMERON_4, 41 },  // Psychic, 2 mons
    { TRAINER_CRISTIN_5, 41 },  // Cooltrainer, 3 mons
    { TRAINER_EVERETT, 41 },  // Gentleman, 1 mon
    { TRAINER_FERNANDO_5, 41 },  // Guitarist, 3 mons
    { TRAINER_JENNY_3, 41 },  // Swimmer F, 1 mon
    { TRAINER_JESSICA_4, 41 },  // Beauty, 2 mons
    { TRAINER_JOSHUA, 41 },  // Psychic, 2 mons
    { TRAINER_KOJI_4, 41 },  // Black Belt, 3 mons
    { TRAINER_MARIELA, 41 },  // Psychic, 1 mon
    { TRAINER_NICOLAS_2, 41 },  // Dragon Tamer, 2 mons
    { TRAINER_PABLO_4, 41 },  // Triathlete, 3 mons
    { TRAINER_PATRICIA, 41 },  // Hex Maniac, 2 mons
    { TRAINER_ROBERT_5, 41 },  // Bird Keeper, 2 mons
    { TRAINER_WALTER_5, 41 },  // Gentleman, 3 mons
    { TRAINER_ERNEST_4, 42 },  // Sailor, 3 mons
    { TRAINER_ISAIAH_3, 42 },  // Triathlete, 1 mon
    { TRAINER_JULIE, 42 },  // Cooltrainer, 3 mons
    { TRAINER_KATELYN_3, 42 },  // Triathlete, 1 mon
    { TRAINER_MICHELLE, 42 },  // Cooltrainer, 3 mons
    { TRAINER_OWEN, 42 },  // Cooltrainer, 3 mons
    { TRAINER_SAMUEL, 42 },  // Cooltrainer, 3 mons
    { TRAINER_TIMOTHY_5, 42 },  // Expert, 1 mon
    { TRAINER_VALERIE_5, 42 },  // Hex Maniac, 3 mons
    { TRAINER_VITO, 42 },  // Cooltrainer, 4 mons
    { TRAINER_ALBERT, 43 },  // Cooltrainer, 2 mons
    { TRAINER_CAROLINE, 43 },  // Cooltrainer, 2 mons
    { TRAINER_DIANNE, 43 },  // Cooltrainer, 2 mons
    { TRAINER_EDGAR, 43 },  // Cooltrainer, 2 mons
    { TRAINER_FELIX, 43 },  // Cooltrainer, 2 mons
    { TRAINER_HALLE, 43 },  // Cooltrainer, 2 mons
    { TRAINER_JACKI_5, 43 },  // Psychic, 2 mons
    { TRAINER_JENNY_4, 43 },  // Swimmer F, 2 mons
    { TRAINER_KATELYNN, 43 },  // Cooltrainer, 2 mons
    { TRAINER_KOJI_5, 43 },  // Black Belt, 3 mons
    { TRAINER_LEONARD, 43 },  // Sailor, 3 mons
    { TRAINER_MITCHELL, 43 },  // Cooltrainer, 2 mons
    { TRAINER_PABLO_5, 43 },  // Triathlete, 3 mons
    { TRAINER_QUINCY, 43 },  // Cooltrainer, 2 mons
    { TRAINER_JESSICA_5, 44 },  // Beauty, 2 mons
    { TRAINER_MICAH, 44 },  // Gentleman, 2 mons
    { TRAINER_NICOLAS_3, 44 },  // Dragon Tamer, 2 mons
    { TRAINER_PHILLIP, 44 },  // Sailor, 2 mons
    { TRAINER_VINCENT, 44 },  // Cooltrainer, 3 mons
    { TRAINER_CAMERON_5, 45 },  // Psychic, 2 mons
    { TRAINER_ERNEST_5, 45 },  // Sailor, 3 mons
    { TRAINER_GARRET, 45 },  // Rich Boy, 1 mon
    { TRAINER_HOPE, 45 },  // Cooltrainer, 1 mon
    { TRAINER_ISAIAH_4, 45 },  // Triathlete, 1 mon
    { TRAINER_JENNY_5, 45 },  // Swimmer F, 3 mons
    { TRAINER_KATELYN_4, 45 },  // Triathlete, 1 mon
    { TRAINER_KEIRA, 45 },  // Cooltrainer, 2 mons
    { TRAINER_NAOMI, 45 },  // Lady, 1 mon
    { TRAINER_SHANNON, 45 },  // Cooltrainer, 1 mon
    { TRAINER_THOMAS, 45 },  // Gentleman, 1 mon
    { TRAINER_LEROY, 46 },  // Cooltrainer, 2 mons
    { TRAINER_NICOLAS_4, 46 },  // Dragon Tamer, 3 mons
    { TRAINER_ISAIAH_5, 48 },  // Triathlete, 1 mon
    { TRAINER_KATELYN_5, 48 },  // Triathlete, 1 mon
    { TRAINER_NICOLAS_5, 49 },  // Dragon Tamer, 3 mons
};

// Mini bosses: Team Aqua and Magma, sorted by average party level.
// Picked by depth like the ordinary table, because using a fixed list
// meant a floor-5 mini boss could be a mid-game grunt with a level 31
// Zubat. The leaders are included: without them the pool stopped at 38
// while the last gym dungeon asks for 45.
// 63 entries, levels 9-43.

struct RogueDungeonMiniBoss
{
    u16 trainerId;
    u16 gfxId;
    u8 avgLevel;
};

static const struct RogueDungeonMiniBoss sRogueDungeonMiniBosses[] =
{
    { TRAINER_GRUNT_PETALBURG_WOODS, OBJ_EVENT_GFX_AQUA_MEMBER_M, 9 },        // Team Aqua
    { TRAINER_GRUNT_RUSTURF_TUNNEL, OBJ_EVENT_GFX_AQUA_MEMBER_M, 11 },        // Team Aqua
    { TRAINER_GRUNT_MUSEUM_2, OBJ_EVENT_GFX_AQUA_MEMBER_M, 14 },              // Team Aqua
    { TRAINER_GRUNT_MUSEUM_1, OBJ_EVENT_GFX_AQUA_MEMBER_M, 15 },              // Team Aqua
    { TRAINER_GRUNT_MT_CHIMNEY_1, OBJ_EVENT_GFX_MAGMA_MEMBER_F, 20 },         // Team Magma
    { TRAINER_GRUNT_MT_CHIMNEY_2, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 20 },         // Team Magma
    { TRAINER_TABITHA_MT_CHIMNEY, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 20 },         // Magma Admin
    { TRAINER_GRUNT_JAGGED_PASS, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 22 },          // Team Magma
    { TRAINER_MAXIE_MT_CHIMNEY, OBJ_EVENT_GFX_MAXIE, 24 },                    // Magma Leader
    { TRAINER_GRUNT_WEATHER_INST_3, OBJ_EVENT_GFX_AQUA_MEMBER_M, 26 },        // Team Aqua
    { TRAINER_GRUNT_WEATHER_INST_1, OBJ_EVENT_GFX_AQUA_MEMBER_M, 27 },        // Team Aqua
    { TRAINER_GRUNT_WEATHER_INST_2, OBJ_EVENT_GFX_AQUA_MEMBER_M, 27 },        // Team Aqua
    { TRAINER_GRUNT_WEATHER_INST_5, OBJ_EVENT_GFX_AQUA_MEMBER_F, 27 },        // Team Aqua
    { TRAINER_GRUNT_MAGMA_HIDEOUT_4, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 28 },      // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_5, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 28 },      // Team Magma
    { TRAINER_GRUNT_SPACE_CENTER_2, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 28 },       // Team Magma
    { TRAINER_GRUNT_WEATHER_INST_4, OBJ_EVENT_GFX_AQUA_MEMBER_F, 28 },        // Team Aqua
    { TRAINER_SHELLY_WEATHER_INSTITUTE, OBJ_EVENT_GFX_AQUA_MEMBER_F, 28 },    // Aqua Admin
    { TRAINER_GRUNT_MAGMA_HIDEOUT_1, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },      // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_10, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },     // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_11, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },     // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_12, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },     // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_13, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },     // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_14, OBJ_EVENT_GFX_MAGMA_MEMBER_F, 29 },     // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_15, OBJ_EVENT_GFX_MAGMA_MEMBER_F, 29 },     // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_16, OBJ_EVENT_GFX_MAGMA_MEMBER_F, 29 },     // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_2, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },      // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_3, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },      // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_6, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },      // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_7, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },      // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_8, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },      // Team Magma
    { TRAINER_GRUNT_MAGMA_HIDEOUT_9, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },      // Team Magma
    { TRAINER_TABITHA_MAGMA_HIDEOUT, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 29 },      // Magma Admin
    { TRAINER_GRUNT_MT_PYRE_3, OBJ_EVENT_GFX_AQUA_MEMBER_M, 30 },             // Team Aqua
    { TRAINER_GRUNT_MT_PYRE_4, OBJ_EVENT_GFX_AQUA_MEMBER_F, 30 },             // Team Aqua
    { TRAINER_GRUNT_AQUA_HIDEOUT_2, OBJ_EVENT_GFX_AQUA_MEMBER_M, 31 },        // Team Aqua
    { TRAINER_GRUNT_AQUA_HIDEOUT_7, OBJ_EVENT_GFX_AQUA_MEMBER_F, 31 },        // Team Aqua
    { TRAINER_GRUNT_SPACE_CENTER_3, OBJ_EVENT_GFX_MAGMA_MEMBER_F, 31 },       // Team Magma
    { TRAINER_GRUNT_UNUSED, OBJ_EVENT_GFX_MAGMA_MEMBER_F, 31 },               // Team Magma
    { TRAINER_GRUNT_AQUA_HIDEOUT_1, OBJ_EVENT_GFX_AQUA_MEMBER_M, 32 },        // Team Aqua
    { TRAINER_GRUNT_AQUA_HIDEOUT_3, OBJ_EVENT_GFX_AQUA_MEMBER_M, 32 },        // Team Aqua
    { TRAINER_GRUNT_AQUA_HIDEOUT_4, OBJ_EVENT_GFX_AQUA_MEMBER_M, 32 },        // Team Aqua
    { TRAINER_GRUNT_AQUA_HIDEOUT_5, OBJ_EVENT_GFX_AQUA_MEMBER_F, 32 },        // Team Aqua
    { TRAINER_GRUNT_AQUA_HIDEOUT_6, OBJ_EVENT_GFX_AQUA_MEMBER_F, 32 },        // Team Aqua
    { TRAINER_GRUNT_AQUA_HIDEOUT_8, OBJ_EVENT_GFX_AQUA_MEMBER_M, 32 },        // Team Aqua
    { TRAINER_GRUNT_MT_PYRE_1, OBJ_EVENT_GFX_AQUA_MEMBER_M, 32 },             // Team Aqua
    { TRAINER_GRUNT_MT_PYRE_2, OBJ_EVENT_GFX_AQUA_MEMBER_M, 32 },             // Team Aqua
    { TRAINER_GRUNT_SPACE_CENTER_1, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 32 },       // Team Magma
    { TRAINER_GRUNT_SPACE_CENTER_4, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 32 },       // Team Magma
    { TRAINER_GRUNT_SPACE_CENTER_5, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 32 },       // Team Magma
    { TRAINER_GRUNT_SPACE_CENTER_6, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 32 },       // Team Magma
    { TRAINER_GRUNT_SPACE_CENTER_7, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 32 },       // Team Magma
    { TRAINER_MATT, OBJ_EVENT_GFX_AQUA_MEMBER_M, 34 },                        // Aqua Admin
    { TRAINER_GRUNT_SEAFLOOR_CAVERN_5, OBJ_EVENT_GFX_AQUA_MEMBER_M, 35 },     // Team Aqua
    { TRAINER_GRUNT_SEAFLOOR_CAVERN_1, OBJ_EVENT_GFX_AQUA_MEMBER_M, 36 },     // Team Aqua
    { TRAINER_GRUNT_SEAFLOOR_CAVERN_2, OBJ_EVENT_GFX_AQUA_MEMBER_M, 36 },     // Team Aqua
    { TRAINER_GRUNT_SEAFLOOR_CAVERN_3, OBJ_EVENT_GFX_AQUA_MEMBER_M, 36 },     // Team Aqua
    { TRAINER_GRUNT_SEAFLOOR_CAVERN_4, OBJ_EVENT_GFX_AQUA_MEMBER_F, 36 },     // Team Aqua
    { TRAINER_SHELLY_SEAFLOOR_CAVERN, OBJ_EVENT_GFX_AQUA_MEMBER_F, 37 },      // Aqua Admin
    { TRAINER_MAXIE_MAGMA_HIDEOUT, OBJ_EVENT_GFX_MAXIE, 38 },                 // Magma Leader
    { TRAINER_TABITHA_MOSSDEEP, OBJ_EVENT_GFX_MAGMA_MEMBER_M, 38 },           // Magma Admin
    { TRAINER_ARCHIE, OBJ_EVENT_GFX_ARCHIE, 42 },                             // Aqua Leader
    { TRAINER_MAXIE_MOSSDEEP, OBJ_EVENT_GFX_MAXIE, 43 },                      // Magma Leader
};

#endif // GUARD_CONSTANTS_ROGUE_DUNGEON_TRAINERS_H
