#ifndef GUARD_CONSTANTS_ROGUE_DUNGEON_STARTERS_H
#define GUARD_CONSTANTS_ROGUE_DUNGEON_STARTERS_H

// GENERATED by tools/rogue/gen_starters.py - do not edit by hand.
//
// The Gen 1-9 starter trios, plus the three single-partner mascots
// (Pikachu, Clefairy, Eevee), in national order. Each carries the
// elemental attack of its type so a fresh pick can actually fight.
// Index order must match RogueDungeonFloor_Starters in starters.inc,
// because the multichoice returns an index into this table.

struct RogueDungeonStarter
{
    u16 species;
    u16 move;
};

static const struct RogueDungeonStarter sRogueDungeonStarters[] =
{
    { SPECIES_BULBASAUR, MOVE_VINE_WHIP },      //  0 Bulbasaur
    { SPECIES_CHARMANDER, MOVE_EMBER },         //  1 Charmander
    { SPECIES_SQUIRTLE, MOVE_WATER_GUN },       //  2 Squirtle
    { SPECIES_PIKACHU, MOVE_THUNDER_SHOCK },    //  3 Pikachu
    { SPECIES_CLEFAIRY, MOVE_DISARMING_VOICE }, //  4 Clefairy
    { SPECIES_EEVEE, MOVE_QUICK_ATTACK },       //  5 Eevee
    { SPECIES_CHIKORITA, MOVE_VINE_WHIP },      //  6 Chikorita
    { SPECIES_CYNDAQUIL, MOVE_EMBER },          //  7 Cyndaquil
    { SPECIES_TOTODILE, MOVE_WATER_GUN },       //  8 Totodile
    { SPECIES_TREECKO, MOVE_VINE_WHIP },        //  9 Treecko
    { SPECIES_TORCHIC, MOVE_EMBER },            // 10 Torchic
    { SPECIES_MUDKIP, MOVE_WATER_GUN },         // 11 Mudkip
    { SPECIES_TURTWIG, MOVE_VINE_WHIP },        // 12 Turtwig
    { SPECIES_CHIMCHAR, MOVE_EMBER },           // 13 Chimchar
    { SPECIES_PIPLUP, MOVE_WATER_GUN },         // 14 Piplup
    { SPECIES_SNIVY, MOVE_VINE_WHIP },          // 15 Snivy
    { SPECIES_TEPIG, MOVE_EMBER },              // 16 Tepig
    { SPECIES_OSHAWOTT, MOVE_WATER_GUN },       // 17 Oshawott
    { SPECIES_CHESPIN, MOVE_VINE_WHIP },        // 18 Chespin
    { SPECIES_FENNEKIN, MOVE_EMBER },           // 19 Fennekin
    { SPECIES_FROAKIE, MOVE_WATER_GUN },        // 20 Froakie
    { SPECIES_ROWLET, MOVE_VINE_WHIP },         // 21 Rowlet
    { SPECIES_LITTEN, MOVE_EMBER },             // 22 Litten
    { SPECIES_POPPLIO, MOVE_WATER_GUN },        // 23 Popplio
    { SPECIES_GROOKEY, MOVE_VINE_WHIP },        // 24 Grookey
    { SPECIES_SCORBUNNY, MOVE_EMBER },          // 25 Scorbunny
    { SPECIES_SOBBLE, MOVE_WATER_GUN },         // 26 Sobble
    { SPECIES_SPRIGATITO, MOVE_VINE_WHIP },     // 27 Sprigatito
    { SPECIES_FUECOCO, MOVE_EMBER },            // 28 Fuecoco
    { SPECIES_QUAXLY, MOVE_WATER_GUN },         // 29 Quaxly
};

#endif // GUARD_CONSTANTS_ROGUE_DUNGEON_STARTERS_H
