	.align 2
voicegroup191::
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_drum_and_percussion_kick, 255, 0, 255, 0
	voice_directsound_no_resample 32, 74, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 127, 77, 204
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 127, 0, 188
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_48, 255, 0, 255, 210
	voice_keysplit voicegroup_trumpet_keysplit, keysplit_trumpet

