	.include "asm/macros.inc"

	.section .rodata
	.global gbs_Music_PetalburgWoods
	.align 2

@ GENERATED by tools/rogue/midi_to_gbs.py from mus_petalburg_woods.mid
@ Real GBS song data on the GBS sequencer, not an m4a song with a
@ PSG voicegroup. Expression (duty, vibrato, kit, wave sample) is
@ from the spec in that tool and is meant to be tuned by ear.

gbs_Music_PetalburgWoods:
	channel_count 4
	channel 1, Music_PetalburgWoods_Ch1
	channel 2, Music_PetalburgWoods_Ch2
	channel 3, Music_PetalburgWoods_Ch3
	channel 4, Music_PetalburgWoods_Ch4

gbs_Music_PetalburgWoods_Ch1:
	gbs_switch 0
Music_PetalburgWoods_Ch1:
	tempo 882
	volume 7, 7
	duty_cycle 2
	vibrato 12, 2, 4
	note_type 1, 10, 2
Music_PetalburgWoods_Ch1_loop:
	octave 4
	note D_, 2
	rest 2
	note As, 2
	rest 2
	note Fs, 2
	rest 2
	octave 5
	note D_, 15
	rest 5
	note Cs, 2
	note C_, 1
	octave 4
	note B_, 1
	note As, 16
	note As, 7
	rest 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	rest 16
	rest 16
	rest 16
	rest 16
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	octave 6
	note Ds, 1
	octave 5
	note G_, 1
	rest 16
	octave 6
	note D_, 2
	note Ds, 2
	note D_, 2
	rest 2
	note D_, 2
	note Ds, 2
	note D_, 2
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 10
	note Cs, 2
	note D_, 2
	note Cs, 2
	rest 2
	note Cs, 2
	note D_, 2
	note Cs, 2
	rest 6
	note D_, 2
	note Ds, 2
	octave 5
	note As, 2
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 6
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	octave 6
	note D_, 1
	octave 5
	note As, 1
	rest 16
	rest 12
	octave 4
	note D_, 2
	rest 2
	note As, 2
	rest 2
	note Fs, 2
	rest 2
	octave 5
	note D_, 15
	rest 5
	note Cs, 2
	note C_, 1
	octave 4
	note B_, 1
	note As, 16
	note As, 7
	sound_loop 0, Music_PetalburgWoods_Ch1_loop

gbs_Music_PetalburgWoods_Ch2:
	gbs_switch 1
Music_PetalburgWoods_Ch2:
	volume 7, 7
	duty_cycle 1
	vibrato 16, 1, 4
	note_type 1, 8, 3
Music_PetalburgWoods_Ch2_loop:
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 16
	rest 4
	octave 3
	note As, 4
	note As, 4
	note As, 4
	note As, 4
	note As, 4
	note As, 4
	note B_, 4
	note B_, 4
	note B_, 4
	note B_, 4
	note B_, 4
	note B_, 4
	note B_, 4
	note B_, 4
	note B_, 4
	note B_, 4
	note B_, 4
	note B_, 4
	rest 16
	rest 16
	rest 16
	rest 4
	octave 4
	note G_, 2
	rest 6
	note G_, 2
	rest 6
	note G_, 2
	rest 16
	rest 14
	octave 3
	note G_, 2
	rest 6
	note G_, 2
	rest 6
	note G_, 2
	rest 2
	note G_, 2
	rest 16
	rest 10
	note Fs, 2
	rest 6
	note Fs, 2
	rest 6
	note Fs, 2
	rest 2
	note Fs, 2
	rest 16
	rest 10
	note Fs, 2
	rest 6
	note Fs, 2
	rest 6
	note Fs, 2
	rest 2
	note Fs, 2
	rest 16
	rest 16
	rest 4
	note D_, 2
	rest 2
	note Fs, 2
	rest 2
	octave 4
	note D_, 2
	rest 2
	note As, 2
	rest 2
	note D_, 2
	rest 2
	note As, 2
	rest 2
	note D_, 2
	rest 2
	note As, 2
	rest 16
	rest 16
	rest 10
	octave 3
	note D_, 2
	rest 2
	note Fs, 2
	rest 2
	octave 4
	note D_, 2
	rest 2
	note As, 2
	rest 2
	note D_, 2
	rest 2
	note As, 2
	rest 2
	note D_, 2
	rest 2
	note As, 2
	rest 16
	rest 16
	rest 10
	octave 2
	note D_, 2
	rest 2
	note Fs, 2
	rest 2
	octave 3
	note D_, 2
	rest 2
	note As, 2
	rest 2
	note D_, 2
	rest 2
	note As, 2
	rest 2
	note D_, 2
	rest 2
	note As, 2
	rest 16
	rest 16
	rest 16
	rest 3
	sound_loop 0, Music_PetalburgWoods_Ch2_loop

gbs_Music_PetalburgWoods_Ch3:
	gbs_switch 2
Music_PetalburgWoods_Ch3:
	volume 7, 7
	note_type 2, 1, 1
Music_PetalburgWoods_Ch3_loop:
	rest 8
	octave 2
	note D_, 1
	rest 3
	note D_, 1
	rest 3
	note D_, 1
	rest 1
	note D_, 1
	rest 13
	octave 3
	note D_, 1
	rest 3
	note D_, 1
	rest 3
	note D_, 1
	rest 1
	note D_, 1
	rest 13
	octave 2
	note D_, 1
	rest 3
	note D_, 1
	rest 3
	note D_, 1
	rest 1
	note D_, 1
	rest 13
	note D_, 1
	rest 3
	note D_, 1
	rest 3
	note D_, 1
	rest 1
	note D_, 1
	rest 13
	note Ds, 1
	rest 3
	note Ds, 1
	rest 3
	note Ds, 1
	rest 1
	note Ds, 1
	rest 13
	note Ds, 1
	rest 3
	note Ds, 1
	rest 3
	note Ds, 1
	rest 1
	note Ds, 1
	rest 13
	note Ds, 1
	rest 3
	note Ds, 1
	rest 3
	note Ds, 1
	rest 1
	note Ds, 1
	rest 13
	octave 3
	note Ds, 1
	rest 3
	note Ds, 1
	rest 3
	note Ds, 1
	rest 1
	note Ds, 1
	rest 13
	note D_, 1
	rest 3
	note D_, 1
	rest 3
	note D_, 1
	rest 1
	note D_, 1
	rest 13
	note D_, 1
	rest 3
	note D_, 1
	rest 3
	note D_, 1
	rest 1
	note D_, 1
	rest 13
	octave 2
	note D_, 1
	rest 3
	note D_, 1
	rest 3
	note D_, 1
	rest 1
	note D_, 1
	rest 13
	note D_, 1
	rest 3
	note D_, 1
	rest 3
	note D_, 1
	rest 1
	note D_, 1
	rest 13
	note D_, 1
	rest 3
	note D_, 1
	rest 3
	note D_, 1
	rest 1
	note D_, 1
	rest 13
	note D_, 1
	rest 3
	note D_, 1
	rest 3
	note D_, 1
	rest 1
	note D_, 1
	rest 13
	note D_, 1
	rest 3
	note D_, 1
	rest 3
	note D_, 1
	rest 1
	note D_, 1
	rest 10
	sound_loop 0, Music_PetalburgWoods_Ch3_loop

gbs_Music_PetalburgWoods_Ch4:
	gbs_switch 3
Music_PetalburgWoods_Ch4:
	volume 7, 7
	toggle_noise 0
	drum_speed 1
Music_PetalburgWoods_Ch4_loop:
	rest 12
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 4
	drum_note 1, 4
	rest 16
	drum_note 1, 4
	drum_note 1, 4
	rest 16
	rest 3
	sound_loop 0, Music_PetalburgWoods_Ch4_loop

