// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Bulbasaur_normal[] = INCBIN_U32("graphics/portraits/bulbasaur/normal.4bpp");
static const u16 sPortraitPal_Bulbasaur_normal[] = INCBIN_U16("graphics/portraits/bulbasaur/normal.gbapal");
static const u32 sPortraitGfx_Bulbasaur_happy[] = INCBIN_U32("graphics/portraits/bulbasaur/happy.4bpp");
static const u16 sPortraitPal_Bulbasaur_happy[] = INCBIN_U16("graphics/portraits/bulbasaur/happy.gbapal");
static const u32 sPortraitGfx_Bulbasaur_pain[] = INCBIN_U32("graphics/portraits/bulbasaur/pain.4bpp");
static const u16 sPortraitPal_Bulbasaur_pain[] = INCBIN_U16("graphics/portraits/bulbasaur/pain.gbapal");
static const u32 sPortraitGfx_Bulbasaur_angry[] = INCBIN_U32("graphics/portraits/bulbasaur/angry.4bpp");
static const u16 sPortraitPal_Bulbasaur_angry[] = INCBIN_U16("graphics/portraits/bulbasaur/angry.gbapal");
static const u32 sPortraitGfx_Bulbasaur_worried[] = INCBIN_U32("graphics/portraits/bulbasaur/worried.4bpp");
static const u16 sPortraitPal_Bulbasaur_worried[] = INCBIN_U16("graphics/portraits/bulbasaur/worried.gbapal");
static const u32 sPortraitGfx_Bulbasaur_sad[] = INCBIN_U32("graphics/portraits/bulbasaur/sad.4bpp");
static const u16 sPortraitPal_Bulbasaur_sad[] = INCBIN_U16("graphics/portraits/bulbasaur/sad.gbapal");
static const u32 sPortraitGfx_Bulbasaur_crying[] = INCBIN_U32("graphics/portraits/bulbasaur/crying.4bpp");
static const u16 sPortraitPal_Bulbasaur_crying[] = INCBIN_U16("graphics/portraits/bulbasaur/crying.gbapal");
static const u32 sPortraitGfx_Bulbasaur_shouting[] = INCBIN_U32("graphics/portraits/bulbasaur/shouting.4bpp");
static const u16 sPortraitPal_Bulbasaur_shouting[] = INCBIN_U16("graphics/portraits/bulbasaur/shouting.gbapal");
static const u32 sPortraitGfx_Bulbasaur_teary_eyed[] = INCBIN_U32("graphics/portraits/bulbasaur/teary_eyed.4bpp");
static const u16 sPortraitPal_Bulbasaur_teary_eyed[] = INCBIN_U16("graphics/portraits/bulbasaur/teary_eyed.gbapal");
static const u32 sPortraitGfx_Bulbasaur_determined[] = INCBIN_U32("graphics/portraits/bulbasaur/determined.4bpp");
static const u16 sPortraitPal_Bulbasaur_determined[] = INCBIN_U16("graphics/portraits/bulbasaur/determined.gbapal");
static const u32 sPortraitGfx_Bulbasaur_joyous[] = INCBIN_U32("graphics/portraits/bulbasaur/joyous.4bpp");
static const u16 sPortraitPal_Bulbasaur_joyous[] = INCBIN_U16("graphics/portraits/bulbasaur/joyous.gbapal");
static const u32 sPortraitGfx_Bulbasaur_inspired[] = INCBIN_U32("graphics/portraits/bulbasaur/inspired.4bpp");
static const u16 sPortraitPal_Bulbasaur_inspired[] = INCBIN_U16("graphics/portraits/bulbasaur/inspired.gbapal");
static const u32 sPortraitGfx_Bulbasaur_surprised[] = INCBIN_U32("graphics/portraits/bulbasaur/surprised.4bpp");
static const u16 sPortraitPal_Bulbasaur_surprised[] = INCBIN_U16("graphics/portraits/bulbasaur/surprised.gbapal");
static const u32 sPortraitGfx_Bulbasaur_dizzy[] = INCBIN_U32("graphics/portraits/bulbasaur/dizzy.4bpp");
static const u16 sPortraitPal_Bulbasaur_dizzy[] = INCBIN_U16("graphics/portraits/bulbasaur/dizzy.gbapal");
static const u32 sPortraitGfx_Bulbasaur_special1[] = INCBIN_U32("graphics/portraits/bulbasaur/special1.4bpp");
static const u16 sPortraitPal_Bulbasaur_special1[] = INCBIN_U16("graphics/portraits/bulbasaur/special1.gbapal");
static const u32 sPortraitGfx_Bulbasaur_sigh[] = INCBIN_U32("graphics/portraits/bulbasaur/sigh.4bpp");
static const u16 sPortraitPal_Bulbasaur_sigh[] = INCBIN_U16("graphics/portraits/bulbasaur/sigh.gbapal");
static const u32 sPortraitGfx_Bulbasaur_stunned[] = INCBIN_U32("graphics/portraits/bulbasaur/stunned.4bpp");
static const u16 sPortraitPal_Bulbasaur_stunned[] = INCBIN_U16("graphics/portraits/bulbasaur/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Bulbasaur[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Bulbasaur_normal, sPortraitPal_Bulbasaur_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Bulbasaur_happy, sPortraitPal_Bulbasaur_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Bulbasaur_pain, sPortraitPal_Bulbasaur_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Bulbasaur_angry, sPortraitPal_Bulbasaur_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Bulbasaur_worried, sPortraitPal_Bulbasaur_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Bulbasaur_sad, sPortraitPal_Bulbasaur_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Bulbasaur_crying, sPortraitPal_Bulbasaur_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Bulbasaur_shouting, sPortraitPal_Bulbasaur_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Bulbasaur_teary_eyed, sPortraitPal_Bulbasaur_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Bulbasaur_determined, sPortraitPal_Bulbasaur_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Bulbasaur_joyous, sPortraitPal_Bulbasaur_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Bulbasaur_inspired, sPortraitPal_Bulbasaur_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Bulbasaur_surprised, sPortraitPal_Bulbasaur_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Bulbasaur_dizzy, sPortraitPal_Bulbasaur_dizzy },
    [PORTRAIT_FACE_SPECIAL1] = { sPortraitGfx_Bulbasaur_special1, sPortraitPal_Bulbasaur_special1 },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Bulbasaur_sigh, sPortraitPal_Bulbasaur_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Bulbasaur_stunned, sPortraitPal_Bulbasaur_stunned },
};
