// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Charmander_normal[] = INCBIN_U32("graphics/portraits/charmander/normal.4bpp");
static const u16 sPortraitPal_Charmander_normal[] = INCBIN_U16("graphics/portraits/charmander/normal.gbapal");
static const u32 sPortraitGfx_Charmander_happy[] = INCBIN_U32("graphics/portraits/charmander/happy.4bpp");
static const u16 sPortraitPal_Charmander_happy[] = INCBIN_U16("graphics/portraits/charmander/happy.gbapal");
static const u32 sPortraitGfx_Charmander_pain[] = INCBIN_U32("graphics/portraits/charmander/pain.4bpp");
static const u16 sPortraitPal_Charmander_pain[] = INCBIN_U16("graphics/portraits/charmander/pain.gbapal");
static const u32 sPortraitGfx_Charmander_angry[] = INCBIN_U32("graphics/portraits/charmander/angry.4bpp");
static const u16 sPortraitPal_Charmander_angry[] = INCBIN_U16("graphics/portraits/charmander/angry.gbapal");
static const u32 sPortraitGfx_Charmander_worried[] = INCBIN_U32("graphics/portraits/charmander/worried.4bpp");
static const u16 sPortraitPal_Charmander_worried[] = INCBIN_U16("graphics/portraits/charmander/worried.gbapal");
static const u32 sPortraitGfx_Charmander_sad[] = INCBIN_U32("graphics/portraits/charmander/sad.4bpp");
static const u16 sPortraitPal_Charmander_sad[] = INCBIN_U16("graphics/portraits/charmander/sad.gbapal");
static const u32 sPortraitGfx_Charmander_crying[] = INCBIN_U32("graphics/portraits/charmander/crying.4bpp");
static const u16 sPortraitPal_Charmander_crying[] = INCBIN_U16("graphics/portraits/charmander/crying.gbapal");
static const u32 sPortraitGfx_Charmander_shouting[] = INCBIN_U32("graphics/portraits/charmander/shouting.4bpp");
static const u16 sPortraitPal_Charmander_shouting[] = INCBIN_U16("graphics/portraits/charmander/shouting.gbapal");
static const u32 sPortraitGfx_Charmander_teary_eyed[] = INCBIN_U32("graphics/portraits/charmander/teary_eyed.4bpp");
static const u16 sPortraitPal_Charmander_teary_eyed[] = INCBIN_U16("graphics/portraits/charmander/teary_eyed.gbapal");
static const u32 sPortraitGfx_Charmander_determined[] = INCBIN_U32("graphics/portraits/charmander/determined.4bpp");
static const u16 sPortraitPal_Charmander_determined[] = INCBIN_U16("graphics/portraits/charmander/determined.gbapal");
static const u32 sPortraitGfx_Charmander_joyous[] = INCBIN_U32("graphics/portraits/charmander/joyous.4bpp");
static const u16 sPortraitPal_Charmander_joyous[] = INCBIN_U16("graphics/portraits/charmander/joyous.gbapal");
static const u32 sPortraitGfx_Charmander_inspired[] = INCBIN_U32("graphics/portraits/charmander/inspired.4bpp");
static const u16 sPortraitPal_Charmander_inspired[] = INCBIN_U16("graphics/portraits/charmander/inspired.gbapal");
static const u32 sPortraitGfx_Charmander_surprised[] = INCBIN_U32("graphics/portraits/charmander/surprised.4bpp");
static const u16 sPortraitPal_Charmander_surprised[] = INCBIN_U16("graphics/portraits/charmander/surprised.gbapal");
static const u32 sPortraitGfx_Charmander_dizzy[] = INCBIN_U32("graphics/portraits/charmander/dizzy.4bpp");
static const u16 sPortraitPal_Charmander_dizzy[] = INCBIN_U16("graphics/portraits/charmander/dizzy.gbapal");
static const u32 sPortraitGfx_Charmander_special0[] = INCBIN_U32("graphics/portraits/charmander/special0.4bpp");
static const u16 sPortraitPal_Charmander_special0[] = INCBIN_U16("graphics/portraits/charmander/special0.gbapal");
static const u32 sPortraitGfx_Charmander_special1[] = INCBIN_U32("graphics/portraits/charmander/special1.4bpp");
static const u16 sPortraitPal_Charmander_special1[] = INCBIN_U16("graphics/portraits/charmander/special1.gbapal");
static const u32 sPortraitGfx_Charmander_sigh[] = INCBIN_U32("graphics/portraits/charmander/sigh.4bpp");
static const u16 sPortraitPal_Charmander_sigh[] = INCBIN_U16("graphics/portraits/charmander/sigh.gbapal");
static const u32 sPortraitGfx_Charmander_stunned[] = INCBIN_U32("graphics/portraits/charmander/stunned.4bpp");
static const u16 sPortraitPal_Charmander_stunned[] = INCBIN_U16("graphics/portraits/charmander/stunned.gbapal");
static const u32 sPortraitGfx_Charmander_special2[] = INCBIN_U32("graphics/portraits/charmander/special2.4bpp");
static const u16 sPortraitPal_Charmander_special2[] = INCBIN_U16("graphics/portraits/charmander/special2.gbapal");
static const u32 sPortraitGfx_Charmander_special3[] = INCBIN_U32("graphics/portraits/charmander/special3.4bpp");
static const u16 sPortraitPal_Charmander_special3[] = INCBIN_U16("graphics/portraits/charmander/special3.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Charmander[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Charmander_normal, sPortraitPal_Charmander_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Charmander_happy, sPortraitPal_Charmander_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Charmander_pain, sPortraitPal_Charmander_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Charmander_angry, sPortraitPal_Charmander_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Charmander_worried, sPortraitPal_Charmander_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Charmander_sad, sPortraitPal_Charmander_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Charmander_crying, sPortraitPal_Charmander_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Charmander_shouting, sPortraitPal_Charmander_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Charmander_teary_eyed, sPortraitPal_Charmander_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Charmander_determined, sPortraitPal_Charmander_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Charmander_joyous, sPortraitPal_Charmander_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Charmander_inspired, sPortraitPal_Charmander_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Charmander_surprised, sPortraitPal_Charmander_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Charmander_dizzy, sPortraitPal_Charmander_dizzy },
    [PORTRAIT_FACE_SPECIAL0] = { sPortraitGfx_Charmander_special0, sPortraitPal_Charmander_special0 },
    [PORTRAIT_FACE_SPECIAL1] = { sPortraitGfx_Charmander_special1, sPortraitPal_Charmander_special1 },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Charmander_sigh, sPortraitPal_Charmander_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Charmander_stunned, sPortraitPal_Charmander_stunned },
    [PORTRAIT_FACE_SPECIAL2] = { sPortraitGfx_Charmander_special2, sPortraitPal_Charmander_special2 },
    [PORTRAIT_FACE_SPECIAL3] = { sPortraitGfx_Charmander_special3, sPortraitPal_Charmander_special3 },
};
