// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Chikorita_normal[] = INCBIN_U32("graphics/portraits/chikorita/normal.4bpp");
static const u16 sPortraitPal_Chikorita_normal[] = INCBIN_U16("graphics/portraits/chikorita/normal.gbapal");
static const u32 sPortraitGfx_Chikorita_happy[] = INCBIN_U32("graphics/portraits/chikorita/happy.4bpp");
static const u16 sPortraitPal_Chikorita_happy[] = INCBIN_U16("graphics/portraits/chikorita/happy.gbapal");
static const u32 sPortraitGfx_Chikorita_pain[] = INCBIN_U32("graphics/portraits/chikorita/pain.4bpp");
static const u16 sPortraitPal_Chikorita_pain[] = INCBIN_U16("graphics/portraits/chikorita/pain.gbapal");
static const u32 sPortraitGfx_Chikorita_angry[] = INCBIN_U32("graphics/portraits/chikorita/angry.4bpp");
static const u16 sPortraitPal_Chikorita_angry[] = INCBIN_U16("graphics/portraits/chikorita/angry.gbapal");
static const u32 sPortraitGfx_Chikorita_worried[] = INCBIN_U32("graphics/portraits/chikorita/worried.4bpp");
static const u16 sPortraitPal_Chikorita_worried[] = INCBIN_U16("graphics/portraits/chikorita/worried.gbapal");
static const u32 sPortraitGfx_Chikorita_sad[] = INCBIN_U32("graphics/portraits/chikorita/sad.4bpp");
static const u16 sPortraitPal_Chikorita_sad[] = INCBIN_U16("graphics/portraits/chikorita/sad.gbapal");
static const u32 sPortraitGfx_Chikorita_crying[] = INCBIN_U32("graphics/portraits/chikorita/crying.4bpp");
static const u16 sPortraitPal_Chikorita_crying[] = INCBIN_U16("graphics/portraits/chikorita/crying.gbapal");
static const u32 sPortraitGfx_Chikorita_shouting[] = INCBIN_U32("graphics/portraits/chikorita/shouting.4bpp");
static const u16 sPortraitPal_Chikorita_shouting[] = INCBIN_U16("graphics/portraits/chikorita/shouting.gbapal");
static const u32 sPortraitGfx_Chikorita_teary_eyed[] = INCBIN_U32("graphics/portraits/chikorita/teary_eyed.4bpp");
static const u16 sPortraitPal_Chikorita_teary_eyed[] = INCBIN_U16("graphics/portraits/chikorita/teary_eyed.gbapal");
static const u32 sPortraitGfx_Chikorita_determined[] = INCBIN_U32("graphics/portraits/chikorita/determined.4bpp");
static const u16 sPortraitPal_Chikorita_determined[] = INCBIN_U16("graphics/portraits/chikorita/determined.gbapal");
static const u32 sPortraitGfx_Chikorita_joyous[] = INCBIN_U32("graphics/portraits/chikorita/joyous.4bpp");
static const u16 sPortraitPal_Chikorita_joyous[] = INCBIN_U16("graphics/portraits/chikorita/joyous.gbapal");
static const u32 sPortraitGfx_Chikorita_inspired[] = INCBIN_U32("graphics/portraits/chikorita/inspired.4bpp");
static const u16 sPortraitPal_Chikorita_inspired[] = INCBIN_U16("graphics/portraits/chikorita/inspired.gbapal");
static const u32 sPortraitGfx_Chikorita_surprised[] = INCBIN_U32("graphics/portraits/chikorita/surprised.4bpp");
static const u16 sPortraitPal_Chikorita_surprised[] = INCBIN_U16("graphics/portraits/chikorita/surprised.gbapal");
static const u32 sPortraitGfx_Chikorita_dizzy[] = INCBIN_U32("graphics/portraits/chikorita/dizzy.4bpp");
static const u16 sPortraitPal_Chikorita_dizzy[] = INCBIN_U16("graphics/portraits/chikorita/dizzy.gbapal");
static const u32 sPortraitGfx_Chikorita_special0[] = INCBIN_U32("graphics/portraits/chikorita/special0.4bpp");
static const u16 sPortraitPal_Chikorita_special0[] = INCBIN_U16("graphics/portraits/chikorita/special0.gbapal");
static const u32 sPortraitGfx_Chikorita_special1[] = INCBIN_U32("graphics/portraits/chikorita/special1.4bpp");
static const u16 sPortraitPal_Chikorita_special1[] = INCBIN_U16("graphics/portraits/chikorita/special1.gbapal");
static const u32 sPortraitGfx_Chikorita_sigh[] = INCBIN_U32("graphics/portraits/chikorita/sigh.4bpp");
static const u16 sPortraitPal_Chikorita_sigh[] = INCBIN_U16("graphics/portraits/chikorita/sigh.gbapal");
static const u32 sPortraitGfx_Chikorita_stunned[] = INCBIN_U32("graphics/portraits/chikorita/stunned.4bpp");
static const u16 sPortraitPal_Chikorita_stunned[] = INCBIN_U16("graphics/portraits/chikorita/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Chikorita[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Chikorita_normal, sPortraitPal_Chikorita_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Chikorita_happy, sPortraitPal_Chikorita_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Chikorita_pain, sPortraitPal_Chikorita_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Chikorita_angry, sPortraitPal_Chikorita_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Chikorita_worried, sPortraitPal_Chikorita_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Chikorita_sad, sPortraitPal_Chikorita_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Chikorita_crying, sPortraitPal_Chikorita_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Chikorita_shouting, sPortraitPal_Chikorita_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Chikorita_teary_eyed, sPortraitPal_Chikorita_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Chikorita_determined, sPortraitPal_Chikorita_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Chikorita_joyous, sPortraitPal_Chikorita_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Chikorita_inspired, sPortraitPal_Chikorita_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Chikorita_surprised, sPortraitPal_Chikorita_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Chikorita_dizzy, sPortraitPal_Chikorita_dizzy },
    [PORTRAIT_FACE_SPECIAL0] = { sPortraitGfx_Chikorita_special0, sPortraitPal_Chikorita_special0 },
    [PORTRAIT_FACE_SPECIAL1] = { sPortraitGfx_Chikorita_special1, sPortraitPal_Chikorita_special1 },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Chikorita_sigh, sPortraitPal_Chikorita_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Chikorita_stunned, sPortraitPal_Chikorita_stunned },
};
