// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Chimchar_normal[] = INCBIN_U32("graphics/portraits/chimchar/normal.4bpp");
static const u16 sPortraitPal_Chimchar_normal[] = INCBIN_U16("graphics/portraits/chimchar/normal.gbapal");
static const u32 sPortraitGfx_Chimchar_happy[] = INCBIN_U32("graphics/portraits/chimchar/happy.4bpp");
static const u16 sPortraitPal_Chimchar_happy[] = INCBIN_U16("graphics/portraits/chimchar/happy.gbapal");
static const u32 sPortraitGfx_Chimchar_pain[] = INCBIN_U32("graphics/portraits/chimchar/pain.4bpp");
static const u16 sPortraitPal_Chimchar_pain[] = INCBIN_U16("graphics/portraits/chimchar/pain.gbapal");
static const u32 sPortraitGfx_Chimchar_angry[] = INCBIN_U32("graphics/portraits/chimchar/angry.4bpp");
static const u16 sPortraitPal_Chimchar_angry[] = INCBIN_U16("graphics/portraits/chimchar/angry.gbapal");
static const u32 sPortraitGfx_Chimchar_worried[] = INCBIN_U32("graphics/portraits/chimchar/worried.4bpp");
static const u16 sPortraitPal_Chimchar_worried[] = INCBIN_U16("graphics/portraits/chimchar/worried.gbapal");
static const u32 sPortraitGfx_Chimchar_sad[] = INCBIN_U32("graphics/portraits/chimchar/sad.4bpp");
static const u16 sPortraitPal_Chimchar_sad[] = INCBIN_U16("graphics/portraits/chimchar/sad.gbapal");
static const u32 sPortraitGfx_Chimchar_crying[] = INCBIN_U32("graphics/portraits/chimchar/crying.4bpp");
static const u16 sPortraitPal_Chimchar_crying[] = INCBIN_U16("graphics/portraits/chimchar/crying.gbapal");
static const u32 sPortraitGfx_Chimchar_shouting[] = INCBIN_U32("graphics/portraits/chimchar/shouting.4bpp");
static const u16 sPortraitPal_Chimchar_shouting[] = INCBIN_U16("graphics/portraits/chimchar/shouting.gbapal");
static const u32 sPortraitGfx_Chimchar_teary_eyed[] = INCBIN_U32("graphics/portraits/chimchar/teary_eyed.4bpp");
static const u16 sPortraitPal_Chimchar_teary_eyed[] = INCBIN_U16("graphics/portraits/chimchar/teary_eyed.gbapal");
static const u32 sPortraitGfx_Chimchar_determined[] = INCBIN_U32("graphics/portraits/chimchar/determined.4bpp");
static const u16 sPortraitPal_Chimchar_determined[] = INCBIN_U16("graphics/portraits/chimchar/determined.gbapal");
static const u32 sPortraitGfx_Chimchar_joyous[] = INCBIN_U32("graphics/portraits/chimchar/joyous.4bpp");
static const u16 sPortraitPal_Chimchar_joyous[] = INCBIN_U16("graphics/portraits/chimchar/joyous.gbapal");
static const u32 sPortraitGfx_Chimchar_inspired[] = INCBIN_U32("graphics/portraits/chimchar/inspired.4bpp");
static const u16 sPortraitPal_Chimchar_inspired[] = INCBIN_U16("graphics/portraits/chimchar/inspired.gbapal");
static const u32 sPortraitGfx_Chimchar_surprised[] = INCBIN_U32("graphics/portraits/chimchar/surprised.4bpp");
static const u16 sPortraitPal_Chimchar_surprised[] = INCBIN_U16("graphics/portraits/chimchar/surprised.gbapal");
static const u32 sPortraitGfx_Chimchar_dizzy[] = INCBIN_U32("graphics/portraits/chimchar/dizzy.4bpp");
static const u16 sPortraitPal_Chimchar_dizzy[] = INCBIN_U16("graphics/portraits/chimchar/dizzy.gbapal");
static const u32 sPortraitGfx_Chimchar_sigh[] = INCBIN_U32("graphics/portraits/chimchar/sigh.4bpp");
static const u16 sPortraitPal_Chimchar_sigh[] = INCBIN_U16("graphics/portraits/chimchar/sigh.gbapal");
static const u32 sPortraitGfx_Chimchar_stunned[] = INCBIN_U32("graphics/portraits/chimchar/stunned.4bpp");
static const u16 sPortraitPal_Chimchar_stunned[] = INCBIN_U16("graphics/portraits/chimchar/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Chimchar[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Chimchar_normal, sPortraitPal_Chimchar_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Chimchar_happy, sPortraitPal_Chimchar_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Chimchar_pain, sPortraitPal_Chimchar_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Chimchar_angry, sPortraitPal_Chimchar_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Chimchar_worried, sPortraitPal_Chimchar_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Chimchar_sad, sPortraitPal_Chimchar_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Chimchar_crying, sPortraitPal_Chimchar_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Chimchar_shouting, sPortraitPal_Chimchar_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Chimchar_teary_eyed, sPortraitPal_Chimchar_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Chimchar_determined, sPortraitPal_Chimchar_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Chimchar_joyous, sPortraitPal_Chimchar_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Chimchar_inspired, sPortraitPal_Chimchar_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Chimchar_surprised, sPortraitPal_Chimchar_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Chimchar_dizzy, sPortraitPal_Chimchar_dizzy },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Chimchar_sigh, sPortraitPal_Chimchar_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Chimchar_stunned, sPortraitPal_Chimchar_stunned },
};
