// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Clefairy_normal[] = INCBIN_U32("graphics/portraits/clefairy/normal.4bpp");
static const u16 sPortraitPal_Clefairy_normal[] = INCBIN_U16("graphics/portraits/clefairy/normal.gbapal");
static const u32 sPortraitGfx_Clefairy_happy[] = INCBIN_U32("graphics/portraits/clefairy/happy.4bpp");
static const u16 sPortraitPal_Clefairy_happy[] = INCBIN_U16("graphics/portraits/clefairy/happy.gbapal");
static const u32 sPortraitGfx_Clefairy_pain[] = INCBIN_U32("graphics/portraits/clefairy/pain.4bpp");
static const u16 sPortraitPal_Clefairy_pain[] = INCBIN_U16("graphics/portraits/clefairy/pain.gbapal");
static const u32 sPortraitGfx_Clefairy_angry[] = INCBIN_U32("graphics/portraits/clefairy/angry.4bpp");
static const u16 sPortraitPal_Clefairy_angry[] = INCBIN_U16("graphics/portraits/clefairy/angry.gbapal");
static const u32 sPortraitGfx_Clefairy_worried[] = INCBIN_U32("graphics/portraits/clefairy/worried.4bpp");
static const u16 sPortraitPal_Clefairy_worried[] = INCBIN_U16("graphics/portraits/clefairy/worried.gbapal");
static const u32 sPortraitGfx_Clefairy_sad[] = INCBIN_U32("graphics/portraits/clefairy/sad.4bpp");
static const u16 sPortraitPal_Clefairy_sad[] = INCBIN_U16("graphics/portraits/clefairy/sad.gbapal");
static const u32 sPortraitGfx_Clefairy_crying[] = INCBIN_U32("graphics/portraits/clefairy/crying.4bpp");
static const u16 sPortraitPal_Clefairy_crying[] = INCBIN_U16("graphics/portraits/clefairy/crying.gbapal");
static const u32 sPortraitGfx_Clefairy_shouting[] = INCBIN_U32("graphics/portraits/clefairy/shouting.4bpp");
static const u16 sPortraitPal_Clefairy_shouting[] = INCBIN_U16("graphics/portraits/clefairy/shouting.gbapal");
static const u32 sPortraitGfx_Clefairy_teary_eyed[] = INCBIN_U32("graphics/portraits/clefairy/teary_eyed.4bpp");
static const u16 sPortraitPal_Clefairy_teary_eyed[] = INCBIN_U16("graphics/portraits/clefairy/teary_eyed.gbapal");
static const u32 sPortraitGfx_Clefairy_determined[] = INCBIN_U32("graphics/portraits/clefairy/determined.4bpp");
static const u16 sPortraitPal_Clefairy_determined[] = INCBIN_U16("graphics/portraits/clefairy/determined.gbapal");
static const u32 sPortraitGfx_Clefairy_joyous[] = INCBIN_U32("graphics/portraits/clefairy/joyous.4bpp");
static const u16 sPortraitPal_Clefairy_joyous[] = INCBIN_U16("graphics/portraits/clefairy/joyous.gbapal");
static const u32 sPortraitGfx_Clefairy_inspired[] = INCBIN_U32("graphics/portraits/clefairy/inspired.4bpp");
static const u16 sPortraitPal_Clefairy_inspired[] = INCBIN_U16("graphics/portraits/clefairy/inspired.gbapal");
static const u32 sPortraitGfx_Clefairy_surprised[] = INCBIN_U32("graphics/portraits/clefairy/surprised.4bpp");
static const u16 sPortraitPal_Clefairy_surprised[] = INCBIN_U16("graphics/portraits/clefairy/surprised.gbapal");
static const u32 sPortraitGfx_Clefairy_dizzy[] = INCBIN_U32("graphics/portraits/clefairy/dizzy.4bpp");
static const u16 sPortraitPal_Clefairy_dizzy[] = INCBIN_U16("graphics/portraits/clefairy/dizzy.gbapal");
static const u32 sPortraitGfx_Clefairy_sigh[] = INCBIN_U32("graphics/portraits/clefairy/sigh.4bpp");
static const u16 sPortraitPal_Clefairy_sigh[] = INCBIN_U16("graphics/portraits/clefairy/sigh.gbapal");
static const u32 sPortraitGfx_Clefairy_stunned[] = INCBIN_U32("graphics/portraits/clefairy/stunned.4bpp");
static const u16 sPortraitPal_Clefairy_stunned[] = INCBIN_U16("graphics/portraits/clefairy/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Clefairy[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Clefairy_normal, sPortraitPal_Clefairy_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Clefairy_happy, sPortraitPal_Clefairy_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Clefairy_pain, sPortraitPal_Clefairy_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Clefairy_angry, sPortraitPal_Clefairy_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Clefairy_worried, sPortraitPal_Clefairy_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Clefairy_sad, sPortraitPal_Clefairy_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Clefairy_crying, sPortraitPal_Clefairy_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Clefairy_shouting, sPortraitPal_Clefairy_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Clefairy_teary_eyed, sPortraitPal_Clefairy_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Clefairy_determined, sPortraitPal_Clefairy_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Clefairy_joyous, sPortraitPal_Clefairy_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Clefairy_inspired, sPortraitPal_Clefairy_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Clefairy_surprised, sPortraitPal_Clefairy_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Clefairy_dizzy, sPortraitPal_Clefairy_dizzy },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Clefairy_sigh, sPortraitPal_Clefairy_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Clefairy_stunned, sPortraitPal_Clefairy_stunned },
};
