// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Cyndaquil_normal[] = INCBIN_U32("graphics/portraits/cyndaquil/normal.4bpp");
static const u16 sPortraitPal_Cyndaquil_normal[] = INCBIN_U16("graphics/portraits/cyndaquil/normal.gbapal");
static const u32 sPortraitGfx_Cyndaquil_happy[] = INCBIN_U32("graphics/portraits/cyndaquil/happy.4bpp");
static const u16 sPortraitPal_Cyndaquil_happy[] = INCBIN_U16("graphics/portraits/cyndaquil/happy.gbapal");
static const u32 sPortraitGfx_Cyndaquil_pain[] = INCBIN_U32("graphics/portraits/cyndaquil/pain.4bpp");
static const u16 sPortraitPal_Cyndaquil_pain[] = INCBIN_U16("graphics/portraits/cyndaquil/pain.gbapal");
static const u32 sPortraitGfx_Cyndaquil_angry[] = INCBIN_U32("graphics/portraits/cyndaquil/angry.4bpp");
static const u16 sPortraitPal_Cyndaquil_angry[] = INCBIN_U16("graphics/portraits/cyndaquil/angry.gbapal");
static const u32 sPortraitGfx_Cyndaquil_worried[] = INCBIN_U32("graphics/portraits/cyndaquil/worried.4bpp");
static const u16 sPortraitPal_Cyndaquil_worried[] = INCBIN_U16("graphics/portraits/cyndaquil/worried.gbapal");
static const u32 sPortraitGfx_Cyndaquil_sad[] = INCBIN_U32("graphics/portraits/cyndaquil/sad.4bpp");
static const u16 sPortraitPal_Cyndaquil_sad[] = INCBIN_U16("graphics/portraits/cyndaquil/sad.gbapal");
static const u32 sPortraitGfx_Cyndaquil_crying[] = INCBIN_U32("graphics/portraits/cyndaquil/crying.4bpp");
static const u16 sPortraitPal_Cyndaquil_crying[] = INCBIN_U16("graphics/portraits/cyndaquil/crying.gbapal");
static const u32 sPortraitGfx_Cyndaquil_shouting[] = INCBIN_U32("graphics/portraits/cyndaquil/shouting.4bpp");
static const u16 sPortraitPal_Cyndaquil_shouting[] = INCBIN_U16("graphics/portraits/cyndaquil/shouting.gbapal");
static const u32 sPortraitGfx_Cyndaquil_teary_eyed[] = INCBIN_U32("graphics/portraits/cyndaquil/teary_eyed.4bpp");
static const u16 sPortraitPal_Cyndaquil_teary_eyed[] = INCBIN_U16("graphics/portraits/cyndaquil/teary_eyed.gbapal");
static const u32 sPortraitGfx_Cyndaquil_determined[] = INCBIN_U32("graphics/portraits/cyndaquil/determined.4bpp");
static const u16 sPortraitPal_Cyndaquil_determined[] = INCBIN_U16("graphics/portraits/cyndaquil/determined.gbapal");
static const u32 sPortraitGfx_Cyndaquil_joyous[] = INCBIN_U32("graphics/portraits/cyndaquil/joyous.4bpp");
static const u16 sPortraitPal_Cyndaquil_joyous[] = INCBIN_U16("graphics/portraits/cyndaquil/joyous.gbapal");
static const u32 sPortraitGfx_Cyndaquil_inspired[] = INCBIN_U32("graphics/portraits/cyndaquil/inspired.4bpp");
static const u16 sPortraitPal_Cyndaquil_inspired[] = INCBIN_U16("graphics/portraits/cyndaquil/inspired.gbapal");
static const u32 sPortraitGfx_Cyndaquil_surprised[] = INCBIN_U32("graphics/portraits/cyndaquil/surprised.4bpp");
static const u16 sPortraitPal_Cyndaquil_surprised[] = INCBIN_U16("graphics/portraits/cyndaquil/surprised.gbapal");
static const u32 sPortraitGfx_Cyndaquil_dizzy[] = INCBIN_U32("graphics/portraits/cyndaquil/dizzy.4bpp");
static const u16 sPortraitPal_Cyndaquil_dizzy[] = INCBIN_U16("graphics/portraits/cyndaquil/dizzy.gbapal");
static const u32 sPortraitGfx_Cyndaquil_special1[] = INCBIN_U32("graphics/portraits/cyndaquil/special1.4bpp");
static const u16 sPortraitPal_Cyndaquil_special1[] = INCBIN_U16("graphics/portraits/cyndaquil/special1.gbapal");
static const u32 sPortraitGfx_Cyndaquil_sigh[] = INCBIN_U32("graphics/portraits/cyndaquil/sigh.4bpp");
static const u16 sPortraitPal_Cyndaquil_sigh[] = INCBIN_U16("graphics/portraits/cyndaquil/sigh.gbapal");
static const u32 sPortraitGfx_Cyndaquil_stunned[] = INCBIN_U32("graphics/portraits/cyndaquil/stunned.4bpp");
static const u16 sPortraitPal_Cyndaquil_stunned[] = INCBIN_U16("graphics/portraits/cyndaquil/stunned.gbapal");
static const u32 sPortraitGfx_Cyndaquil_special2[] = INCBIN_U32("graphics/portraits/cyndaquil/special2.4bpp");
static const u16 sPortraitPal_Cyndaquil_special2[] = INCBIN_U16("graphics/portraits/cyndaquil/special2.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Cyndaquil[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Cyndaquil_normal, sPortraitPal_Cyndaquil_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Cyndaquil_happy, sPortraitPal_Cyndaquil_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Cyndaquil_pain, sPortraitPal_Cyndaquil_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Cyndaquil_angry, sPortraitPal_Cyndaquil_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Cyndaquil_worried, sPortraitPal_Cyndaquil_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Cyndaquil_sad, sPortraitPal_Cyndaquil_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Cyndaquil_crying, sPortraitPal_Cyndaquil_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Cyndaquil_shouting, sPortraitPal_Cyndaquil_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Cyndaquil_teary_eyed, sPortraitPal_Cyndaquil_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Cyndaquil_determined, sPortraitPal_Cyndaquil_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Cyndaquil_joyous, sPortraitPal_Cyndaquil_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Cyndaquil_inspired, sPortraitPal_Cyndaquil_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Cyndaquil_surprised, sPortraitPal_Cyndaquil_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Cyndaquil_dizzy, sPortraitPal_Cyndaquil_dizzy },
    [PORTRAIT_FACE_SPECIAL1] = { sPortraitGfx_Cyndaquil_special1, sPortraitPal_Cyndaquil_special1 },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Cyndaquil_sigh, sPortraitPal_Cyndaquil_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Cyndaquil_stunned, sPortraitPal_Cyndaquil_stunned },
    [PORTRAIT_FACE_SPECIAL2] = { sPortraitGfx_Cyndaquil_special2, sPortraitPal_Cyndaquil_special2 },
};
