// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Eevee_normal[] = INCBIN_U32("graphics/portraits/eevee/normal.4bpp");
static const u16 sPortraitPal_Eevee_normal[] = INCBIN_U16("graphics/portraits/eevee/normal.gbapal");
static const u32 sPortraitGfx_Eevee_happy[] = INCBIN_U32("graphics/portraits/eevee/happy.4bpp");
static const u16 sPortraitPal_Eevee_happy[] = INCBIN_U16("graphics/portraits/eevee/happy.gbapal");
static const u32 sPortraitGfx_Eevee_pain[] = INCBIN_U32("graphics/portraits/eevee/pain.4bpp");
static const u16 sPortraitPal_Eevee_pain[] = INCBIN_U16("graphics/portraits/eevee/pain.gbapal");
static const u32 sPortraitGfx_Eevee_angry[] = INCBIN_U32("graphics/portraits/eevee/angry.4bpp");
static const u16 sPortraitPal_Eevee_angry[] = INCBIN_U16("graphics/portraits/eevee/angry.gbapal");
static const u32 sPortraitGfx_Eevee_worried[] = INCBIN_U32("graphics/portraits/eevee/worried.4bpp");
static const u16 sPortraitPal_Eevee_worried[] = INCBIN_U16("graphics/portraits/eevee/worried.gbapal");
static const u32 sPortraitGfx_Eevee_sad[] = INCBIN_U32("graphics/portraits/eevee/sad.4bpp");
static const u16 sPortraitPal_Eevee_sad[] = INCBIN_U16("graphics/portraits/eevee/sad.gbapal");
static const u32 sPortraitGfx_Eevee_crying[] = INCBIN_U32("graphics/portraits/eevee/crying.4bpp");
static const u16 sPortraitPal_Eevee_crying[] = INCBIN_U16("graphics/portraits/eevee/crying.gbapal");
static const u32 sPortraitGfx_Eevee_shouting[] = INCBIN_U32("graphics/portraits/eevee/shouting.4bpp");
static const u16 sPortraitPal_Eevee_shouting[] = INCBIN_U16("graphics/portraits/eevee/shouting.gbapal");
static const u32 sPortraitGfx_Eevee_teary_eyed[] = INCBIN_U32("graphics/portraits/eevee/teary_eyed.4bpp");
static const u16 sPortraitPal_Eevee_teary_eyed[] = INCBIN_U16("graphics/portraits/eevee/teary_eyed.gbapal");
static const u32 sPortraitGfx_Eevee_determined[] = INCBIN_U32("graphics/portraits/eevee/determined.4bpp");
static const u16 sPortraitPal_Eevee_determined[] = INCBIN_U16("graphics/portraits/eevee/determined.gbapal");
static const u32 sPortraitGfx_Eevee_joyous[] = INCBIN_U32("graphics/portraits/eevee/joyous.4bpp");
static const u16 sPortraitPal_Eevee_joyous[] = INCBIN_U16("graphics/portraits/eevee/joyous.gbapal");
static const u32 sPortraitGfx_Eevee_inspired[] = INCBIN_U32("graphics/portraits/eevee/inspired.4bpp");
static const u16 sPortraitPal_Eevee_inspired[] = INCBIN_U16("graphics/portraits/eevee/inspired.gbapal");
static const u32 sPortraitGfx_Eevee_surprised[] = INCBIN_U32("graphics/portraits/eevee/surprised.4bpp");
static const u16 sPortraitPal_Eevee_surprised[] = INCBIN_U16("graphics/portraits/eevee/surprised.gbapal");
static const u32 sPortraitGfx_Eevee_dizzy[] = INCBIN_U32("graphics/portraits/eevee/dizzy.4bpp");
static const u16 sPortraitPal_Eevee_dizzy[] = INCBIN_U16("graphics/portraits/eevee/dizzy.gbapal");
static const u32 sPortraitGfx_Eevee_sigh[] = INCBIN_U32("graphics/portraits/eevee/sigh.4bpp");
static const u16 sPortraitPal_Eevee_sigh[] = INCBIN_U16("graphics/portraits/eevee/sigh.gbapal");
static const u32 sPortraitGfx_Eevee_stunned[] = INCBIN_U32("graphics/portraits/eevee/stunned.4bpp");
static const u16 sPortraitPal_Eevee_stunned[] = INCBIN_U16("graphics/portraits/eevee/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Eevee[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Eevee_normal, sPortraitPal_Eevee_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Eevee_happy, sPortraitPal_Eevee_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Eevee_pain, sPortraitPal_Eevee_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Eevee_angry, sPortraitPal_Eevee_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Eevee_worried, sPortraitPal_Eevee_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Eevee_sad, sPortraitPal_Eevee_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Eevee_crying, sPortraitPal_Eevee_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Eevee_shouting, sPortraitPal_Eevee_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Eevee_teary_eyed, sPortraitPal_Eevee_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Eevee_determined, sPortraitPal_Eevee_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Eevee_joyous, sPortraitPal_Eevee_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Eevee_inspired, sPortraitPal_Eevee_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Eevee_surprised, sPortraitPal_Eevee_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Eevee_dizzy, sPortraitPal_Eevee_dizzy },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Eevee_sigh, sPortraitPal_Eevee_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Eevee_stunned, sPortraitPal_Eevee_stunned },
};
