// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Mudkip_normal[] = INCBIN_U32("graphics/portraits/mudkip/normal.4bpp");
static const u16 sPortraitPal_Mudkip_normal[] = INCBIN_U16("graphics/portraits/mudkip/normal.gbapal");
static const u32 sPortraitGfx_Mudkip_happy[] = INCBIN_U32("graphics/portraits/mudkip/happy.4bpp");
static const u16 sPortraitPal_Mudkip_happy[] = INCBIN_U16("graphics/portraits/mudkip/happy.gbapal");
static const u32 sPortraitGfx_Mudkip_pain[] = INCBIN_U32("graphics/portraits/mudkip/pain.4bpp");
static const u16 sPortraitPal_Mudkip_pain[] = INCBIN_U16("graphics/portraits/mudkip/pain.gbapal");
static const u32 sPortraitGfx_Mudkip_angry[] = INCBIN_U32("graphics/portraits/mudkip/angry.4bpp");
static const u16 sPortraitPal_Mudkip_angry[] = INCBIN_U16("graphics/portraits/mudkip/angry.gbapal");
static const u32 sPortraitGfx_Mudkip_worried[] = INCBIN_U32("graphics/portraits/mudkip/worried.4bpp");
static const u16 sPortraitPal_Mudkip_worried[] = INCBIN_U16("graphics/portraits/mudkip/worried.gbapal");
static const u32 sPortraitGfx_Mudkip_sad[] = INCBIN_U32("graphics/portraits/mudkip/sad.4bpp");
static const u16 sPortraitPal_Mudkip_sad[] = INCBIN_U16("graphics/portraits/mudkip/sad.gbapal");
static const u32 sPortraitGfx_Mudkip_crying[] = INCBIN_U32("graphics/portraits/mudkip/crying.4bpp");
static const u16 sPortraitPal_Mudkip_crying[] = INCBIN_U16("graphics/portraits/mudkip/crying.gbapal");
static const u32 sPortraitGfx_Mudkip_shouting[] = INCBIN_U32("graphics/portraits/mudkip/shouting.4bpp");
static const u16 sPortraitPal_Mudkip_shouting[] = INCBIN_U16("graphics/portraits/mudkip/shouting.gbapal");
static const u32 sPortraitGfx_Mudkip_teary_eyed[] = INCBIN_U32("graphics/portraits/mudkip/teary_eyed.4bpp");
static const u16 sPortraitPal_Mudkip_teary_eyed[] = INCBIN_U16("graphics/portraits/mudkip/teary_eyed.gbapal");
static const u32 sPortraitGfx_Mudkip_determined[] = INCBIN_U32("graphics/portraits/mudkip/determined.4bpp");
static const u16 sPortraitPal_Mudkip_determined[] = INCBIN_U16("graphics/portraits/mudkip/determined.gbapal");
static const u32 sPortraitGfx_Mudkip_joyous[] = INCBIN_U32("graphics/portraits/mudkip/joyous.4bpp");
static const u16 sPortraitPal_Mudkip_joyous[] = INCBIN_U16("graphics/portraits/mudkip/joyous.gbapal");
static const u32 sPortraitGfx_Mudkip_inspired[] = INCBIN_U32("graphics/portraits/mudkip/inspired.4bpp");
static const u16 sPortraitPal_Mudkip_inspired[] = INCBIN_U16("graphics/portraits/mudkip/inspired.gbapal");
static const u32 sPortraitGfx_Mudkip_surprised[] = INCBIN_U32("graphics/portraits/mudkip/surprised.4bpp");
static const u16 sPortraitPal_Mudkip_surprised[] = INCBIN_U16("graphics/portraits/mudkip/surprised.gbapal");
static const u32 sPortraitGfx_Mudkip_dizzy[] = INCBIN_U32("graphics/portraits/mudkip/dizzy.4bpp");
static const u16 sPortraitPal_Mudkip_dizzy[] = INCBIN_U16("graphics/portraits/mudkip/dizzy.gbapal");
static const u32 sPortraitGfx_Mudkip_special1[] = INCBIN_U32("graphics/portraits/mudkip/special1.4bpp");
static const u16 sPortraitPal_Mudkip_special1[] = INCBIN_U16("graphics/portraits/mudkip/special1.gbapal");
static const u32 sPortraitGfx_Mudkip_sigh[] = INCBIN_U32("graphics/portraits/mudkip/sigh.4bpp");
static const u16 sPortraitPal_Mudkip_sigh[] = INCBIN_U16("graphics/portraits/mudkip/sigh.gbapal");
static const u32 sPortraitGfx_Mudkip_stunned[] = INCBIN_U32("graphics/portraits/mudkip/stunned.4bpp");
static const u16 sPortraitPal_Mudkip_stunned[] = INCBIN_U16("graphics/portraits/mudkip/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Mudkip[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Mudkip_normal, sPortraitPal_Mudkip_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Mudkip_happy, sPortraitPal_Mudkip_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Mudkip_pain, sPortraitPal_Mudkip_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Mudkip_angry, sPortraitPal_Mudkip_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Mudkip_worried, sPortraitPal_Mudkip_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Mudkip_sad, sPortraitPal_Mudkip_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Mudkip_crying, sPortraitPal_Mudkip_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Mudkip_shouting, sPortraitPal_Mudkip_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Mudkip_teary_eyed, sPortraitPal_Mudkip_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Mudkip_determined, sPortraitPal_Mudkip_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Mudkip_joyous, sPortraitPal_Mudkip_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Mudkip_inspired, sPortraitPal_Mudkip_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Mudkip_surprised, sPortraitPal_Mudkip_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Mudkip_dizzy, sPortraitPal_Mudkip_dizzy },
    [PORTRAIT_FACE_SPECIAL1] = { sPortraitGfx_Mudkip_special1, sPortraitPal_Mudkip_special1 },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Mudkip_sigh, sPortraitPal_Mudkip_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Mudkip_stunned, sPortraitPal_Mudkip_stunned },
};
