// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Pikachu_normal[] = INCBIN_U32("graphics/portraits/pikachu/normal.4bpp");
static const u16 sPortraitPal_Pikachu_normal[] = INCBIN_U16("graphics/portraits/pikachu/normal.gbapal");
static const u32 sPortraitGfx_Pikachu_happy[] = INCBIN_U32("graphics/portraits/pikachu/happy.4bpp");
static const u16 sPortraitPal_Pikachu_happy[] = INCBIN_U16("graphics/portraits/pikachu/happy.gbapal");
static const u32 sPortraitGfx_Pikachu_pain[] = INCBIN_U32("graphics/portraits/pikachu/pain.4bpp");
static const u16 sPortraitPal_Pikachu_pain[] = INCBIN_U16("graphics/portraits/pikachu/pain.gbapal");
static const u32 sPortraitGfx_Pikachu_angry[] = INCBIN_U32("graphics/portraits/pikachu/angry.4bpp");
static const u16 sPortraitPal_Pikachu_angry[] = INCBIN_U16("graphics/portraits/pikachu/angry.gbapal");
static const u32 sPortraitGfx_Pikachu_worried[] = INCBIN_U32("graphics/portraits/pikachu/worried.4bpp");
static const u16 sPortraitPal_Pikachu_worried[] = INCBIN_U16("graphics/portraits/pikachu/worried.gbapal");
static const u32 sPortraitGfx_Pikachu_sad[] = INCBIN_U32("graphics/portraits/pikachu/sad.4bpp");
static const u16 sPortraitPal_Pikachu_sad[] = INCBIN_U16("graphics/portraits/pikachu/sad.gbapal");
static const u32 sPortraitGfx_Pikachu_crying[] = INCBIN_U32("graphics/portraits/pikachu/crying.4bpp");
static const u16 sPortraitPal_Pikachu_crying[] = INCBIN_U16("graphics/portraits/pikachu/crying.gbapal");
static const u32 sPortraitGfx_Pikachu_shouting[] = INCBIN_U32("graphics/portraits/pikachu/shouting.4bpp");
static const u16 sPortraitPal_Pikachu_shouting[] = INCBIN_U16("graphics/portraits/pikachu/shouting.gbapal");
static const u32 sPortraitGfx_Pikachu_teary_eyed[] = INCBIN_U32("graphics/portraits/pikachu/teary_eyed.4bpp");
static const u16 sPortraitPal_Pikachu_teary_eyed[] = INCBIN_U16("graphics/portraits/pikachu/teary_eyed.gbapal");
static const u32 sPortraitGfx_Pikachu_determined[] = INCBIN_U32("graphics/portraits/pikachu/determined.4bpp");
static const u16 sPortraitPal_Pikachu_determined[] = INCBIN_U16("graphics/portraits/pikachu/determined.gbapal");
static const u32 sPortraitGfx_Pikachu_joyous[] = INCBIN_U32("graphics/portraits/pikachu/joyous.4bpp");
static const u16 sPortraitPal_Pikachu_joyous[] = INCBIN_U16("graphics/portraits/pikachu/joyous.gbapal");
static const u32 sPortraitGfx_Pikachu_inspired[] = INCBIN_U32("graphics/portraits/pikachu/inspired.4bpp");
static const u16 sPortraitPal_Pikachu_inspired[] = INCBIN_U16("graphics/portraits/pikachu/inspired.gbapal");
static const u32 sPortraitGfx_Pikachu_surprised[] = INCBIN_U32("graphics/portraits/pikachu/surprised.4bpp");
static const u16 sPortraitPal_Pikachu_surprised[] = INCBIN_U16("graphics/portraits/pikachu/surprised.gbapal");
static const u32 sPortraitGfx_Pikachu_dizzy[] = INCBIN_U32("graphics/portraits/pikachu/dizzy.4bpp");
static const u16 sPortraitPal_Pikachu_dizzy[] = INCBIN_U16("graphics/portraits/pikachu/dizzy.gbapal");
static const u32 sPortraitGfx_Pikachu_special1[] = INCBIN_U32("graphics/portraits/pikachu/special1.4bpp");
static const u16 sPortraitPal_Pikachu_special1[] = INCBIN_U16("graphics/portraits/pikachu/special1.gbapal");
static const u32 sPortraitGfx_Pikachu_sigh[] = INCBIN_U32("graphics/portraits/pikachu/sigh.4bpp");
static const u16 sPortraitPal_Pikachu_sigh[] = INCBIN_U16("graphics/portraits/pikachu/sigh.gbapal");
static const u32 sPortraitGfx_Pikachu_stunned[] = INCBIN_U32("graphics/portraits/pikachu/stunned.4bpp");
static const u16 sPortraitPal_Pikachu_stunned[] = INCBIN_U16("graphics/portraits/pikachu/stunned.gbapal");
static const u32 sPortraitGfx_Pikachu_special2[] = INCBIN_U32("graphics/portraits/pikachu/special2.4bpp");
static const u16 sPortraitPal_Pikachu_special2[] = INCBIN_U16("graphics/portraits/pikachu/special2.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Pikachu[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Pikachu_normal, sPortraitPal_Pikachu_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Pikachu_happy, sPortraitPal_Pikachu_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Pikachu_pain, sPortraitPal_Pikachu_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Pikachu_angry, sPortraitPal_Pikachu_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Pikachu_worried, sPortraitPal_Pikachu_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Pikachu_sad, sPortraitPal_Pikachu_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Pikachu_crying, sPortraitPal_Pikachu_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Pikachu_shouting, sPortraitPal_Pikachu_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Pikachu_teary_eyed, sPortraitPal_Pikachu_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Pikachu_determined, sPortraitPal_Pikachu_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Pikachu_joyous, sPortraitPal_Pikachu_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Pikachu_inspired, sPortraitPal_Pikachu_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Pikachu_surprised, sPortraitPal_Pikachu_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Pikachu_dizzy, sPortraitPal_Pikachu_dizzy },
    [PORTRAIT_FACE_SPECIAL1] = { sPortraitGfx_Pikachu_special1, sPortraitPal_Pikachu_special1 },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Pikachu_sigh, sPortraitPal_Pikachu_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Pikachu_stunned, sPortraitPal_Pikachu_stunned },
    [PORTRAIT_FACE_SPECIAL2] = { sPortraitGfx_Pikachu_special2, sPortraitPal_Pikachu_special2 },
};
