// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Piplup_normal[] = INCBIN_U32("graphics/portraits/piplup/normal.4bpp");
static const u16 sPortraitPal_Piplup_normal[] = INCBIN_U16("graphics/portraits/piplup/normal.gbapal");
static const u32 sPortraitGfx_Piplup_happy[] = INCBIN_U32("graphics/portraits/piplup/happy.4bpp");
static const u16 sPortraitPal_Piplup_happy[] = INCBIN_U16("graphics/portraits/piplup/happy.gbapal");
static const u32 sPortraitGfx_Piplup_pain[] = INCBIN_U32("graphics/portraits/piplup/pain.4bpp");
static const u16 sPortraitPal_Piplup_pain[] = INCBIN_U16("graphics/portraits/piplup/pain.gbapal");
static const u32 sPortraitGfx_Piplup_angry[] = INCBIN_U32("graphics/portraits/piplup/angry.4bpp");
static const u16 sPortraitPal_Piplup_angry[] = INCBIN_U16("graphics/portraits/piplup/angry.gbapal");
static const u32 sPortraitGfx_Piplup_worried[] = INCBIN_U32("graphics/portraits/piplup/worried.4bpp");
static const u16 sPortraitPal_Piplup_worried[] = INCBIN_U16("graphics/portraits/piplup/worried.gbapal");
static const u32 sPortraitGfx_Piplup_sad[] = INCBIN_U32("graphics/portraits/piplup/sad.4bpp");
static const u16 sPortraitPal_Piplup_sad[] = INCBIN_U16("graphics/portraits/piplup/sad.gbapal");
static const u32 sPortraitGfx_Piplup_crying[] = INCBIN_U32("graphics/portraits/piplup/crying.4bpp");
static const u16 sPortraitPal_Piplup_crying[] = INCBIN_U16("graphics/portraits/piplup/crying.gbapal");
static const u32 sPortraitGfx_Piplup_shouting[] = INCBIN_U32("graphics/portraits/piplup/shouting.4bpp");
static const u16 sPortraitPal_Piplup_shouting[] = INCBIN_U16("graphics/portraits/piplup/shouting.gbapal");
static const u32 sPortraitGfx_Piplup_teary_eyed[] = INCBIN_U32("graphics/portraits/piplup/teary_eyed.4bpp");
static const u16 sPortraitPal_Piplup_teary_eyed[] = INCBIN_U16("graphics/portraits/piplup/teary_eyed.gbapal");
static const u32 sPortraitGfx_Piplup_determined[] = INCBIN_U32("graphics/portraits/piplup/determined.4bpp");
static const u16 sPortraitPal_Piplup_determined[] = INCBIN_U16("graphics/portraits/piplup/determined.gbapal");
static const u32 sPortraitGfx_Piplup_joyous[] = INCBIN_U32("graphics/portraits/piplup/joyous.4bpp");
static const u16 sPortraitPal_Piplup_joyous[] = INCBIN_U16("graphics/portraits/piplup/joyous.gbapal");
static const u32 sPortraitGfx_Piplup_inspired[] = INCBIN_U32("graphics/portraits/piplup/inspired.4bpp");
static const u16 sPortraitPal_Piplup_inspired[] = INCBIN_U16("graphics/portraits/piplup/inspired.gbapal");
static const u32 sPortraitGfx_Piplup_surprised[] = INCBIN_U32("graphics/portraits/piplup/surprised.4bpp");
static const u16 sPortraitPal_Piplup_surprised[] = INCBIN_U16("graphics/portraits/piplup/surprised.gbapal");
static const u32 sPortraitGfx_Piplup_dizzy[] = INCBIN_U32("graphics/portraits/piplup/dizzy.4bpp");
static const u16 sPortraitPal_Piplup_dizzy[] = INCBIN_U16("graphics/portraits/piplup/dizzy.gbapal");
static const u32 sPortraitGfx_Piplup_sigh[] = INCBIN_U32("graphics/portraits/piplup/sigh.4bpp");
static const u16 sPortraitPal_Piplup_sigh[] = INCBIN_U16("graphics/portraits/piplup/sigh.gbapal");
static const u32 sPortraitGfx_Piplup_stunned[] = INCBIN_U32("graphics/portraits/piplup/stunned.4bpp");
static const u16 sPortraitPal_Piplup_stunned[] = INCBIN_U16("graphics/portraits/piplup/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Piplup[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Piplup_normal, sPortraitPal_Piplup_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Piplup_happy, sPortraitPal_Piplup_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Piplup_pain, sPortraitPal_Piplup_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Piplup_angry, sPortraitPal_Piplup_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Piplup_worried, sPortraitPal_Piplup_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Piplup_sad, sPortraitPal_Piplup_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Piplup_crying, sPortraitPal_Piplup_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Piplup_shouting, sPortraitPal_Piplup_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Piplup_teary_eyed, sPortraitPal_Piplup_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Piplup_determined, sPortraitPal_Piplup_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Piplup_joyous, sPortraitPal_Piplup_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Piplup_inspired, sPortraitPal_Piplup_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Piplup_surprised, sPortraitPal_Piplup_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Piplup_dizzy, sPortraitPal_Piplup_dizzy },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Piplup_sigh, sPortraitPal_Piplup_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Piplup_stunned, sPortraitPal_Piplup_stunned },
};
