// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Squirtle_normal[] = INCBIN_U32("graphics/portraits/squirtle/normal.4bpp");
static const u16 sPortraitPal_Squirtle_normal[] = INCBIN_U16("graphics/portraits/squirtle/normal.gbapal");
static const u32 sPortraitGfx_Squirtle_happy[] = INCBIN_U32("graphics/portraits/squirtle/happy.4bpp");
static const u16 sPortraitPal_Squirtle_happy[] = INCBIN_U16("graphics/portraits/squirtle/happy.gbapal");
static const u32 sPortraitGfx_Squirtle_pain[] = INCBIN_U32("graphics/portraits/squirtle/pain.4bpp");
static const u16 sPortraitPal_Squirtle_pain[] = INCBIN_U16("graphics/portraits/squirtle/pain.gbapal");
static const u32 sPortraitGfx_Squirtle_angry[] = INCBIN_U32("graphics/portraits/squirtle/angry.4bpp");
static const u16 sPortraitPal_Squirtle_angry[] = INCBIN_U16("graphics/portraits/squirtle/angry.gbapal");
static const u32 sPortraitGfx_Squirtle_worried[] = INCBIN_U32("graphics/portraits/squirtle/worried.4bpp");
static const u16 sPortraitPal_Squirtle_worried[] = INCBIN_U16("graphics/portraits/squirtle/worried.gbapal");
static const u32 sPortraitGfx_Squirtle_sad[] = INCBIN_U32("graphics/portraits/squirtle/sad.4bpp");
static const u16 sPortraitPal_Squirtle_sad[] = INCBIN_U16("graphics/portraits/squirtle/sad.gbapal");
static const u32 sPortraitGfx_Squirtle_crying[] = INCBIN_U32("graphics/portraits/squirtle/crying.4bpp");
static const u16 sPortraitPal_Squirtle_crying[] = INCBIN_U16("graphics/portraits/squirtle/crying.gbapal");
static const u32 sPortraitGfx_Squirtle_shouting[] = INCBIN_U32("graphics/portraits/squirtle/shouting.4bpp");
static const u16 sPortraitPal_Squirtle_shouting[] = INCBIN_U16("graphics/portraits/squirtle/shouting.gbapal");
static const u32 sPortraitGfx_Squirtle_teary_eyed[] = INCBIN_U32("graphics/portraits/squirtle/teary_eyed.4bpp");
static const u16 sPortraitPal_Squirtle_teary_eyed[] = INCBIN_U16("graphics/portraits/squirtle/teary_eyed.gbapal");
static const u32 sPortraitGfx_Squirtle_determined[] = INCBIN_U32("graphics/portraits/squirtle/determined.4bpp");
static const u16 sPortraitPal_Squirtle_determined[] = INCBIN_U16("graphics/portraits/squirtle/determined.gbapal");
static const u32 sPortraitGfx_Squirtle_joyous[] = INCBIN_U32("graphics/portraits/squirtle/joyous.4bpp");
static const u16 sPortraitPal_Squirtle_joyous[] = INCBIN_U16("graphics/portraits/squirtle/joyous.gbapal");
static const u32 sPortraitGfx_Squirtle_inspired[] = INCBIN_U32("graphics/portraits/squirtle/inspired.4bpp");
static const u16 sPortraitPal_Squirtle_inspired[] = INCBIN_U16("graphics/portraits/squirtle/inspired.gbapal");
static const u32 sPortraitGfx_Squirtle_surprised[] = INCBIN_U32("graphics/portraits/squirtle/surprised.4bpp");
static const u16 sPortraitPal_Squirtle_surprised[] = INCBIN_U16("graphics/portraits/squirtle/surprised.gbapal");
static const u32 sPortraitGfx_Squirtle_dizzy[] = INCBIN_U32("graphics/portraits/squirtle/dizzy.4bpp");
static const u16 sPortraitPal_Squirtle_dizzy[] = INCBIN_U16("graphics/portraits/squirtle/dizzy.gbapal");
static const u32 sPortraitGfx_Squirtle_special1[] = INCBIN_U32("graphics/portraits/squirtle/special1.4bpp");
static const u16 sPortraitPal_Squirtle_special1[] = INCBIN_U16("graphics/portraits/squirtle/special1.gbapal");
static const u32 sPortraitGfx_Squirtle_sigh[] = INCBIN_U32("graphics/portraits/squirtle/sigh.4bpp");
static const u16 sPortraitPal_Squirtle_sigh[] = INCBIN_U16("graphics/portraits/squirtle/sigh.gbapal");
static const u32 sPortraitGfx_Squirtle_stunned[] = INCBIN_U32("graphics/portraits/squirtle/stunned.4bpp");
static const u16 sPortraitPal_Squirtle_stunned[] = INCBIN_U16("graphics/portraits/squirtle/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Squirtle[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Squirtle_normal, sPortraitPal_Squirtle_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Squirtle_happy, sPortraitPal_Squirtle_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Squirtle_pain, sPortraitPal_Squirtle_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Squirtle_angry, sPortraitPal_Squirtle_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Squirtle_worried, sPortraitPal_Squirtle_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Squirtle_sad, sPortraitPal_Squirtle_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Squirtle_crying, sPortraitPal_Squirtle_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Squirtle_shouting, sPortraitPal_Squirtle_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Squirtle_teary_eyed, sPortraitPal_Squirtle_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Squirtle_determined, sPortraitPal_Squirtle_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Squirtle_joyous, sPortraitPal_Squirtle_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Squirtle_inspired, sPortraitPal_Squirtle_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Squirtle_surprised, sPortraitPal_Squirtle_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Squirtle_dizzy, sPortraitPal_Squirtle_dizzy },
    [PORTRAIT_FACE_SPECIAL1] = { sPortraitGfx_Squirtle_special1, sPortraitPal_Squirtle_special1 },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Squirtle_sigh, sPortraitPal_Squirtle_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Squirtle_stunned, sPortraitPal_Squirtle_stunned },
};
