// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Torchic_normal[] = INCBIN_U32("graphics/portraits/torchic/normal.4bpp");
static const u16 sPortraitPal_Torchic_normal[] = INCBIN_U16("graphics/portraits/torchic/normal.gbapal");
static const u32 sPortraitGfx_Torchic_happy[] = INCBIN_U32("graphics/portraits/torchic/happy.4bpp");
static const u16 sPortraitPal_Torchic_happy[] = INCBIN_U16("graphics/portraits/torchic/happy.gbapal");
static const u32 sPortraitGfx_Torchic_pain[] = INCBIN_U32("graphics/portraits/torchic/pain.4bpp");
static const u16 sPortraitPal_Torchic_pain[] = INCBIN_U16("graphics/portraits/torchic/pain.gbapal");
static const u32 sPortraitGfx_Torchic_angry[] = INCBIN_U32("graphics/portraits/torchic/angry.4bpp");
static const u16 sPortraitPal_Torchic_angry[] = INCBIN_U16("graphics/portraits/torchic/angry.gbapal");
static const u32 sPortraitGfx_Torchic_worried[] = INCBIN_U32("graphics/portraits/torchic/worried.4bpp");
static const u16 sPortraitPal_Torchic_worried[] = INCBIN_U16("graphics/portraits/torchic/worried.gbapal");
static const u32 sPortraitGfx_Torchic_sad[] = INCBIN_U32("graphics/portraits/torchic/sad.4bpp");
static const u16 sPortraitPal_Torchic_sad[] = INCBIN_U16("graphics/portraits/torchic/sad.gbapal");
static const u32 sPortraitGfx_Torchic_crying[] = INCBIN_U32("graphics/portraits/torchic/crying.4bpp");
static const u16 sPortraitPal_Torchic_crying[] = INCBIN_U16("graphics/portraits/torchic/crying.gbapal");
static const u32 sPortraitGfx_Torchic_shouting[] = INCBIN_U32("graphics/portraits/torchic/shouting.4bpp");
static const u16 sPortraitPal_Torchic_shouting[] = INCBIN_U16("graphics/portraits/torchic/shouting.gbapal");
static const u32 sPortraitGfx_Torchic_teary_eyed[] = INCBIN_U32("graphics/portraits/torchic/teary_eyed.4bpp");
static const u16 sPortraitPal_Torchic_teary_eyed[] = INCBIN_U16("graphics/portraits/torchic/teary_eyed.gbapal");
static const u32 sPortraitGfx_Torchic_determined[] = INCBIN_U32("graphics/portraits/torchic/determined.4bpp");
static const u16 sPortraitPal_Torchic_determined[] = INCBIN_U16("graphics/portraits/torchic/determined.gbapal");
static const u32 sPortraitGfx_Torchic_joyous[] = INCBIN_U32("graphics/portraits/torchic/joyous.4bpp");
static const u16 sPortraitPal_Torchic_joyous[] = INCBIN_U16("graphics/portraits/torchic/joyous.gbapal");
static const u32 sPortraitGfx_Torchic_inspired[] = INCBIN_U32("graphics/portraits/torchic/inspired.4bpp");
static const u16 sPortraitPal_Torchic_inspired[] = INCBIN_U16("graphics/portraits/torchic/inspired.gbapal");
static const u32 sPortraitGfx_Torchic_surprised[] = INCBIN_U32("graphics/portraits/torchic/surprised.4bpp");
static const u16 sPortraitPal_Torchic_surprised[] = INCBIN_U16("graphics/portraits/torchic/surprised.gbapal");
static const u32 sPortraitGfx_Torchic_dizzy[] = INCBIN_U32("graphics/portraits/torchic/dizzy.4bpp");
static const u16 sPortraitPal_Torchic_dizzy[] = INCBIN_U16("graphics/portraits/torchic/dizzy.gbapal");
static const u32 sPortraitGfx_Torchic_special1[] = INCBIN_U32("graphics/portraits/torchic/special1.4bpp");
static const u16 sPortraitPal_Torchic_special1[] = INCBIN_U16("graphics/portraits/torchic/special1.gbapal");
static const u32 sPortraitGfx_Torchic_sigh[] = INCBIN_U32("graphics/portraits/torchic/sigh.4bpp");
static const u16 sPortraitPal_Torchic_sigh[] = INCBIN_U16("graphics/portraits/torchic/sigh.gbapal");
static const u32 sPortraitGfx_Torchic_stunned[] = INCBIN_U32("graphics/portraits/torchic/stunned.4bpp");
static const u16 sPortraitPal_Torchic_stunned[] = INCBIN_U16("graphics/portraits/torchic/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Torchic[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Torchic_normal, sPortraitPal_Torchic_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Torchic_happy, sPortraitPal_Torchic_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Torchic_pain, sPortraitPal_Torchic_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Torchic_angry, sPortraitPal_Torchic_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Torchic_worried, sPortraitPal_Torchic_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Torchic_sad, sPortraitPal_Torchic_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Torchic_crying, sPortraitPal_Torchic_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Torchic_shouting, sPortraitPal_Torchic_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Torchic_teary_eyed, sPortraitPal_Torchic_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Torchic_determined, sPortraitPal_Torchic_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Torchic_joyous, sPortraitPal_Torchic_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Torchic_inspired, sPortraitPal_Torchic_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Torchic_surprised, sPortraitPal_Torchic_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Torchic_dizzy, sPortraitPal_Torchic_dizzy },
    [PORTRAIT_FACE_SPECIAL1] = { sPortraitGfx_Torchic_special1, sPortraitPal_Torchic_special1 },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Torchic_sigh, sPortraitPal_Torchic_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Torchic_stunned, sPortraitPal_Torchic_stunned },
};
