// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Totodile_normal[] = INCBIN_U32("graphics/portraits/totodile/normal.4bpp");
static const u16 sPortraitPal_Totodile_normal[] = INCBIN_U16("graphics/portraits/totodile/normal.gbapal");
static const u32 sPortraitGfx_Totodile_happy[] = INCBIN_U32("graphics/portraits/totodile/happy.4bpp");
static const u16 sPortraitPal_Totodile_happy[] = INCBIN_U16("graphics/portraits/totodile/happy.gbapal");
static const u32 sPortraitGfx_Totodile_pain[] = INCBIN_U32("graphics/portraits/totodile/pain.4bpp");
static const u16 sPortraitPal_Totodile_pain[] = INCBIN_U16("graphics/portraits/totodile/pain.gbapal");
static const u32 sPortraitGfx_Totodile_angry[] = INCBIN_U32("graphics/portraits/totodile/angry.4bpp");
static const u16 sPortraitPal_Totodile_angry[] = INCBIN_U16("graphics/portraits/totodile/angry.gbapal");
static const u32 sPortraitGfx_Totodile_worried[] = INCBIN_U32("graphics/portraits/totodile/worried.4bpp");
static const u16 sPortraitPal_Totodile_worried[] = INCBIN_U16("graphics/portraits/totodile/worried.gbapal");
static const u32 sPortraitGfx_Totodile_sad[] = INCBIN_U32("graphics/portraits/totodile/sad.4bpp");
static const u16 sPortraitPal_Totodile_sad[] = INCBIN_U16("graphics/portraits/totodile/sad.gbapal");
static const u32 sPortraitGfx_Totodile_crying[] = INCBIN_U32("graphics/portraits/totodile/crying.4bpp");
static const u16 sPortraitPal_Totodile_crying[] = INCBIN_U16("graphics/portraits/totodile/crying.gbapal");
static const u32 sPortraitGfx_Totodile_shouting[] = INCBIN_U32("graphics/portraits/totodile/shouting.4bpp");
static const u16 sPortraitPal_Totodile_shouting[] = INCBIN_U16("graphics/portraits/totodile/shouting.gbapal");
static const u32 sPortraitGfx_Totodile_teary_eyed[] = INCBIN_U32("graphics/portraits/totodile/teary_eyed.4bpp");
static const u16 sPortraitPal_Totodile_teary_eyed[] = INCBIN_U16("graphics/portraits/totodile/teary_eyed.gbapal");
static const u32 sPortraitGfx_Totodile_determined[] = INCBIN_U32("graphics/portraits/totodile/determined.4bpp");
static const u16 sPortraitPal_Totodile_determined[] = INCBIN_U16("graphics/portraits/totodile/determined.gbapal");
static const u32 sPortraitGfx_Totodile_joyous[] = INCBIN_U32("graphics/portraits/totodile/joyous.4bpp");
static const u16 sPortraitPal_Totodile_joyous[] = INCBIN_U16("graphics/portraits/totodile/joyous.gbapal");
static const u32 sPortraitGfx_Totodile_inspired[] = INCBIN_U32("graphics/portraits/totodile/inspired.4bpp");
static const u16 sPortraitPal_Totodile_inspired[] = INCBIN_U16("graphics/portraits/totodile/inspired.gbapal");
static const u32 sPortraitGfx_Totodile_surprised[] = INCBIN_U32("graphics/portraits/totodile/surprised.4bpp");
static const u16 sPortraitPal_Totodile_surprised[] = INCBIN_U16("graphics/portraits/totodile/surprised.gbapal");
static const u32 sPortraitGfx_Totodile_dizzy[] = INCBIN_U32("graphics/portraits/totodile/dizzy.4bpp");
static const u16 sPortraitPal_Totodile_dizzy[] = INCBIN_U16("graphics/portraits/totodile/dizzy.gbapal");
static const u32 sPortraitGfx_Totodile_special1[] = INCBIN_U32("graphics/portraits/totodile/special1.4bpp");
static const u16 sPortraitPal_Totodile_special1[] = INCBIN_U16("graphics/portraits/totodile/special1.gbapal");
static const u32 sPortraitGfx_Totodile_sigh[] = INCBIN_U32("graphics/portraits/totodile/sigh.4bpp");
static const u16 sPortraitPal_Totodile_sigh[] = INCBIN_U16("graphics/portraits/totodile/sigh.gbapal");
static const u32 sPortraitGfx_Totodile_stunned[] = INCBIN_U32("graphics/portraits/totodile/stunned.4bpp");
static const u16 sPortraitPal_Totodile_stunned[] = INCBIN_U16("graphics/portraits/totodile/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Totodile[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Totodile_normal, sPortraitPal_Totodile_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Totodile_happy, sPortraitPal_Totodile_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Totodile_pain, sPortraitPal_Totodile_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Totodile_angry, sPortraitPal_Totodile_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Totodile_worried, sPortraitPal_Totodile_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Totodile_sad, sPortraitPal_Totodile_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Totodile_crying, sPortraitPal_Totodile_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Totodile_shouting, sPortraitPal_Totodile_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Totodile_teary_eyed, sPortraitPal_Totodile_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Totodile_determined, sPortraitPal_Totodile_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Totodile_joyous, sPortraitPal_Totodile_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Totodile_inspired, sPortraitPal_Totodile_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Totodile_surprised, sPortraitPal_Totodile_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Totodile_dizzy, sPortraitPal_Totodile_dizzy },
    [PORTRAIT_FACE_SPECIAL1] = { sPortraitGfx_Totodile_special1, sPortraitPal_Totodile_special1 },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Totodile_sigh, sPortraitPal_Totodile_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Totodile_stunned, sPortraitPal_Totodile_stunned },
};
