// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Treecko_normal[] = INCBIN_U32("graphics/portraits/treecko/normal.4bpp");
static const u16 sPortraitPal_Treecko_normal[] = INCBIN_U16("graphics/portraits/treecko/normal.gbapal");
static const u32 sPortraitGfx_Treecko_happy[] = INCBIN_U32("graphics/portraits/treecko/happy.4bpp");
static const u16 sPortraitPal_Treecko_happy[] = INCBIN_U16("graphics/portraits/treecko/happy.gbapal");
static const u32 sPortraitGfx_Treecko_pain[] = INCBIN_U32("graphics/portraits/treecko/pain.4bpp");
static const u16 sPortraitPal_Treecko_pain[] = INCBIN_U16("graphics/portraits/treecko/pain.gbapal");
static const u32 sPortraitGfx_Treecko_angry[] = INCBIN_U32("graphics/portraits/treecko/angry.4bpp");
static const u16 sPortraitPal_Treecko_angry[] = INCBIN_U16("graphics/portraits/treecko/angry.gbapal");
static const u32 sPortraitGfx_Treecko_worried[] = INCBIN_U32("graphics/portraits/treecko/worried.4bpp");
static const u16 sPortraitPal_Treecko_worried[] = INCBIN_U16("graphics/portraits/treecko/worried.gbapal");
static const u32 sPortraitGfx_Treecko_sad[] = INCBIN_U32("graphics/portraits/treecko/sad.4bpp");
static const u16 sPortraitPal_Treecko_sad[] = INCBIN_U16("graphics/portraits/treecko/sad.gbapal");
static const u32 sPortraitGfx_Treecko_crying[] = INCBIN_U32("graphics/portraits/treecko/crying.4bpp");
static const u16 sPortraitPal_Treecko_crying[] = INCBIN_U16("graphics/portraits/treecko/crying.gbapal");
static const u32 sPortraitGfx_Treecko_shouting[] = INCBIN_U32("graphics/portraits/treecko/shouting.4bpp");
static const u16 sPortraitPal_Treecko_shouting[] = INCBIN_U16("graphics/portraits/treecko/shouting.gbapal");
static const u32 sPortraitGfx_Treecko_teary_eyed[] = INCBIN_U32("graphics/portraits/treecko/teary_eyed.4bpp");
static const u16 sPortraitPal_Treecko_teary_eyed[] = INCBIN_U16("graphics/portraits/treecko/teary_eyed.gbapal");
static const u32 sPortraitGfx_Treecko_determined[] = INCBIN_U32("graphics/portraits/treecko/determined.4bpp");
static const u16 sPortraitPal_Treecko_determined[] = INCBIN_U16("graphics/portraits/treecko/determined.gbapal");
static const u32 sPortraitGfx_Treecko_joyous[] = INCBIN_U32("graphics/portraits/treecko/joyous.4bpp");
static const u16 sPortraitPal_Treecko_joyous[] = INCBIN_U16("graphics/portraits/treecko/joyous.gbapal");
static const u32 sPortraitGfx_Treecko_inspired[] = INCBIN_U32("graphics/portraits/treecko/inspired.4bpp");
static const u16 sPortraitPal_Treecko_inspired[] = INCBIN_U16("graphics/portraits/treecko/inspired.gbapal");
static const u32 sPortraitGfx_Treecko_surprised[] = INCBIN_U32("graphics/portraits/treecko/surprised.4bpp");
static const u16 sPortraitPal_Treecko_surprised[] = INCBIN_U16("graphics/portraits/treecko/surprised.gbapal");
static const u32 sPortraitGfx_Treecko_dizzy[] = INCBIN_U32("graphics/portraits/treecko/dizzy.4bpp");
static const u16 sPortraitPal_Treecko_dizzy[] = INCBIN_U16("graphics/portraits/treecko/dizzy.gbapal");
static const u32 sPortraitGfx_Treecko_special1[] = INCBIN_U32("graphics/portraits/treecko/special1.4bpp");
static const u16 sPortraitPal_Treecko_special1[] = INCBIN_U16("graphics/portraits/treecko/special1.gbapal");
static const u32 sPortraitGfx_Treecko_sigh[] = INCBIN_U32("graphics/portraits/treecko/sigh.4bpp");
static const u16 sPortraitPal_Treecko_sigh[] = INCBIN_U16("graphics/portraits/treecko/sigh.gbapal");
static const u32 sPortraitGfx_Treecko_stunned[] = INCBIN_U32("graphics/portraits/treecko/stunned.4bpp");
static const u16 sPortraitPal_Treecko_stunned[] = INCBIN_U16("graphics/portraits/treecko/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Treecko[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Treecko_normal, sPortraitPal_Treecko_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Treecko_happy, sPortraitPal_Treecko_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Treecko_pain, sPortraitPal_Treecko_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Treecko_angry, sPortraitPal_Treecko_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Treecko_worried, sPortraitPal_Treecko_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Treecko_sad, sPortraitPal_Treecko_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Treecko_crying, sPortraitPal_Treecko_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Treecko_shouting, sPortraitPal_Treecko_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Treecko_teary_eyed, sPortraitPal_Treecko_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Treecko_determined, sPortraitPal_Treecko_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Treecko_joyous, sPortraitPal_Treecko_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Treecko_inspired, sPortraitPal_Treecko_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Treecko_surprised, sPortraitPal_Treecko_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Treecko_dizzy, sPortraitPal_Treecko_dizzy },
    [PORTRAIT_FACE_SPECIAL1] = { sPortraitGfx_Treecko_special1, sPortraitPal_Treecko_special1 },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Treecko_sigh, sPortraitPal_Treecko_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Treecko_stunned, sPortraitPal_Treecko_stunned },
};
