// GENERATED by tools/rogue/import_portraits.py - do not edit by hand.
// Re-run the tool against the sheet to change anything here.
//
// Face names are the Sprite Repository grid order. Slots the sheet left
// empty are simply absent, and portrait selection skips them.

static const u32 sPortraitGfx_Turtwig_normal[] = INCBIN_U32("graphics/portraits/turtwig/normal.4bpp");
static const u16 sPortraitPal_Turtwig_normal[] = INCBIN_U16("graphics/portraits/turtwig/normal.gbapal");
static const u32 sPortraitGfx_Turtwig_happy[] = INCBIN_U32("graphics/portraits/turtwig/happy.4bpp");
static const u16 sPortraitPal_Turtwig_happy[] = INCBIN_U16("graphics/portraits/turtwig/happy.gbapal");
static const u32 sPortraitGfx_Turtwig_pain[] = INCBIN_U32("graphics/portraits/turtwig/pain.4bpp");
static const u16 sPortraitPal_Turtwig_pain[] = INCBIN_U16("graphics/portraits/turtwig/pain.gbapal");
static const u32 sPortraitGfx_Turtwig_angry[] = INCBIN_U32("graphics/portraits/turtwig/angry.4bpp");
static const u16 sPortraitPal_Turtwig_angry[] = INCBIN_U16("graphics/portraits/turtwig/angry.gbapal");
static const u32 sPortraitGfx_Turtwig_worried[] = INCBIN_U32("graphics/portraits/turtwig/worried.4bpp");
static const u16 sPortraitPal_Turtwig_worried[] = INCBIN_U16("graphics/portraits/turtwig/worried.gbapal");
static const u32 sPortraitGfx_Turtwig_sad[] = INCBIN_U32("graphics/portraits/turtwig/sad.4bpp");
static const u16 sPortraitPal_Turtwig_sad[] = INCBIN_U16("graphics/portraits/turtwig/sad.gbapal");
static const u32 sPortraitGfx_Turtwig_crying[] = INCBIN_U32("graphics/portraits/turtwig/crying.4bpp");
static const u16 sPortraitPal_Turtwig_crying[] = INCBIN_U16("graphics/portraits/turtwig/crying.gbapal");
static const u32 sPortraitGfx_Turtwig_shouting[] = INCBIN_U32("graphics/portraits/turtwig/shouting.4bpp");
static const u16 sPortraitPal_Turtwig_shouting[] = INCBIN_U16("graphics/portraits/turtwig/shouting.gbapal");
static const u32 sPortraitGfx_Turtwig_teary_eyed[] = INCBIN_U32("graphics/portraits/turtwig/teary_eyed.4bpp");
static const u16 sPortraitPal_Turtwig_teary_eyed[] = INCBIN_U16("graphics/portraits/turtwig/teary_eyed.gbapal");
static const u32 sPortraitGfx_Turtwig_determined[] = INCBIN_U32("graphics/portraits/turtwig/determined.4bpp");
static const u16 sPortraitPal_Turtwig_determined[] = INCBIN_U16("graphics/portraits/turtwig/determined.gbapal");
static const u32 sPortraitGfx_Turtwig_joyous[] = INCBIN_U32("graphics/portraits/turtwig/joyous.4bpp");
static const u16 sPortraitPal_Turtwig_joyous[] = INCBIN_U16("graphics/portraits/turtwig/joyous.gbapal");
static const u32 sPortraitGfx_Turtwig_inspired[] = INCBIN_U32("graphics/portraits/turtwig/inspired.4bpp");
static const u16 sPortraitPal_Turtwig_inspired[] = INCBIN_U16("graphics/portraits/turtwig/inspired.gbapal");
static const u32 sPortraitGfx_Turtwig_surprised[] = INCBIN_U32("graphics/portraits/turtwig/surprised.4bpp");
static const u16 sPortraitPal_Turtwig_surprised[] = INCBIN_U16("graphics/portraits/turtwig/surprised.gbapal");
static const u32 sPortraitGfx_Turtwig_dizzy[] = INCBIN_U32("graphics/portraits/turtwig/dizzy.4bpp");
static const u16 sPortraitPal_Turtwig_dizzy[] = INCBIN_U16("graphics/portraits/turtwig/dizzy.gbapal");
static const u32 sPortraitGfx_Turtwig_sigh[] = INCBIN_U32("graphics/portraits/turtwig/sigh.4bpp");
static const u16 sPortraitPal_Turtwig_sigh[] = INCBIN_U16("graphics/portraits/turtwig/sigh.gbapal");
static const u32 sPortraitGfx_Turtwig_stunned[] = INCBIN_U32("graphics/portraits/turtwig/stunned.4bpp");
static const u16 sPortraitPal_Turtwig_stunned[] = INCBIN_U16("graphics/portraits/turtwig/stunned.gbapal");

static const struct RoguePortraitImage sPortraitFaces_Turtwig[] =
{
    [PORTRAIT_FACE_NORMAL] = { sPortraitGfx_Turtwig_normal, sPortraitPal_Turtwig_normal },
    [PORTRAIT_FACE_HAPPY] = { sPortraitGfx_Turtwig_happy, sPortraitPal_Turtwig_happy },
    [PORTRAIT_FACE_PAIN] = { sPortraitGfx_Turtwig_pain, sPortraitPal_Turtwig_pain },
    [PORTRAIT_FACE_ANGRY] = { sPortraitGfx_Turtwig_angry, sPortraitPal_Turtwig_angry },
    [PORTRAIT_FACE_WORRIED] = { sPortraitGfx_Turtwig_worried, sPortraitPal_Turtwig_worried },
    [PORTRAIT_FACE_SAD] = { sPortraitGfx_Turtwig_sad, sPortraitPal_Turtwig_sad },
    [PORTRAIT_FACE_CRYING] = { sPortraitGfx_Turtwig_crying, sPortraitPal_Turtwig_crying },
    [PORTRAIT_FACE_SHOUTING] = { sPortraitGfx_Turtwig_shouting, sPortraitPal_Turtwig_shouting },
    [PORTRAIT_FACE_TEARY_EYED] = { sPortraitGfx_Turtwig_teary_eyed, sPortraitPal_Turtwig_teary_eyed },
    [PORTRAIT_FACE_DETERMINED] = { sPortraitGfx_Turtwig_determined, sPortraitPal_Turtwig_determined },
    [PORTRAIT_FACE_JOYOUS] = { sPortraitGfx_Turtwig_joyous, sPortraitPal_Turtwig_joyous },
    [PORTRAIT_FACE_INSPIRED] = { sPortraitGfx_Turtwig_inspired, sPortraitPal_Turtwig_inspired },
    [PORTRAIT_FACE_SURPRISED] = { sPortraitGfx_Turtwig_surprised, sPortraitPal_Turtwig_surprised },
    [PORTRAIT_FACE_DIZZY] = { sPortraitGfx_Turtwig_dizzy, sPortraitPal_Turtwig_dizzy },
    [PORTRAIT_FACE_SIGH] = { sPortraitGfx_Turtwig_sigh, sPortraitPal_Turtwig_sigh },
    [PORTRAIT_FACE_STUNNED] = { sPortraitGfx_Turtwig_stunned, sPortraitPal_Turtwig_stunned },
};
