// GENERATED by tools/rogue/gen_stubs.py -- wireless/link removal.
//
// The wireless stack and every feature that needed it are gone from the
// build. These are the symbols the REMAINING code still references. Each
// signature is copied from the header the caller was compiled against, so
// the prototypes agree -- a stub with the wrong signature links cleanly and
// then corrupts the stack at runtime.

#include "global.h"
#include "link.h"
#include "link_rfu.h"
#include "task.h"
#include "window.h"
#include "text.h"
#include "sprite.h"

// --- data ---
const u8 gCaseToggleTable[256];   // union_room_chat.h
struct RfuGameCompatibilityData gRfuPartnerCompatibilityData;   // union_room.h
struct STWIStatus *gSTWIStatus;   // librfu.h
const u8 gText_FemaleSymbol4[1];   // strings.h
const u8 gText_GenderlessSymbol[1];   // strings.h
const u8 gText_MaleSymbol4[1];   // strings.h
const struct WindowTemplate gTradeEvolutionSceneYesNoWindowTemplate;   // trade.h
const u16 gTradePlatform_Tilemap[1];   // trade.h
enum Species gUnionRoomOfferedSpecies;   // union_room.h
enum Type gUnionRoomRequestedMonType;   // union_room.h
u8 gWirelessStatusIndicatorSpriteId;   // link_rfu.h

// --- functions ---
void CB2_InitEReader(void)
{
}

void CB2_InitMysteryGift(void)
{
}

int CanRegisterMonForTradingBoard(struct RfuGameCompatibilityData player, enum Species species2, enum Species species, bool8 isModernFatefulEncounter)
{
    return 0;
}

int CanSpinTradeMon(struct Pokemon *mon, u16 monIdx)
{
    return 0;
}

void ClearLinkRfuCallback(void)
{
}

void ClearMysteryGift(void)
{
}

void CreateTask_EnterCableClubSeat(TaskFunc followupFunc)
{
}

u8 CreateTask_ListenToWireless(void)
{
    return 0;
}

u8 CreateTask_ReestablishCableClubLink(void)
{
    return 0;
}

void CreateWirelessStatusIndicatorSprite(u8 x, u8 y)
{
}

void DestroyTask_RfuIdle(void)
{
}

void DestroyWirelessStatusIndicatorSprite(void)
{
}

void DrawTextOnTradeWindow(u8 windowId, const u8 *str, u8 speed)
{
}

s32 GetGameProgressForLinkTrade(void)
{
    return 0;
}

struct RfuGameData *GetHostRfuGameData(void)
{
    return NULL;
}

bool32 GetLinkTrainerCardColor(u8 linkPlayerIndex)
{
    return 0;
}

u16 *GetQuestionnaireWordsPtr(void)
{
    return NULL;
}

u32 GetRfuRecvQueueLength(void)
{
    return 0;
}

struct WonderNewsMetadata *GetSavedWonderNewsMetadata(void)
{
    return NULL;
}

int GetUnionRoomTradeMessageId(struct RfuGameCompatibilityData player, struct RfuGameCompatibilityData partner, enum Species playerSpecies2, enum Species partnerSpecies, enum Type requestedType, enum Species playerSpecies, bool8 isModernFatefulEncounter)
{
    return 0;
}

bool32 InUnionRoom(void)
{
    return 0;
}

void InitRFU(void)
{
}

void InitRFUAPI(void)
{
}

void InitTradeSequenceBgGpuRegs(void)
{
}

void InitUnionRoomChatRegisteredTexts(void)
{
}

void IsDodrioInParty(void)
{
}

bool8 IsLinkRfuTaskFinished(void)
{
    return 0;
}

void IsPokemonJumpSpeciesInParty(void)
{
}

bool32 IsRfuRecvQueueEmpty(void)
{
    return 0;
}

bool32 IsSendingKeysToRfu(void)
{
    return 0;
}

bool32 IsSpeciesAllowedInPokemonJump(enum Species species)
{
    return 0;
}

void LinkRfu_FatalError(void)
{
}

void LinkRfu_Shutdown(void)
{
}

void LinkTradeDrawWindow(void)
{
}

void LoadTradeAnimGfx(void)
{
}

void LoadWirelessStatusIndicatorSpriteGfx(void)
{
}

u16 MysteryGift_GetCardStat(u32 stat)
{
    return 0;
}

void ResetLinkRfuGFLayer(void)
{
}

void ResetPokemonJumpRecords(void)
{
}

bool32 RfuMain1(void)
{
    return 0;
}

bool32 RfuMain2(void)
{
    return 0;
}

void RfuSetErrorParams(u32 errorInfo)
{
}

void RfuVSync(void)
{
}

u8 Rfu_GetBlockReceivedStatus(void)
{
    return 0;
}

u8 Rfu_GetLinkPlayerCount(void)
{
    return 0;
}

u8 Rfu_GetMultiplayerId(void)
{
    return 0;
}

bool32 Rfu_InitBlockSend(const u8 *src, size_t size)
{
    return 0;
}

bool8 Rfu_IsMaster(void)
{
    return 0;
}

void Rfu_ResetBlockReceivedFlag(u8 linkPlayerId)
{
}

bool8 Rfu_SendBlockRequest(u8 type)
{
    return 0;
}

void Rfu_SetBerryBlenderLinkCallback(void)
{
}

void Rfu_SetBlockReceivedFlag(u8 linkPlayerId)
{
}

void Rfu_SetCloseLinkCallback(void)
{
}

u8 Rfu_SetLinkRecovery(bool32 enable)
{
    return 0;
}

void Rfu_SetLinkStandbyCallback(void)
{
}

void SetUsingUnionRoomStartMenu(void)
{
}

void ShowDodrioBerryPickingRecords(void)
{
}

void ShowPokemonJumpRecords(void)
{
}

void StartSendingKeysToRfu(void)
{
}

void Task_LinkContest_CommunicateAppealsState(u8 taskId)
{
}

void Task_LinkContest_CommunicateCategoryRS(u8 taskId)
{
}

void Task_LinkContest_CommunicateFinalStandings(u8 taskId)
{
}

void Task_LinkContest_CommunicateLeaderIdsRS(u8 taskId)
{
}

void Task_LinkContest_CommunicateMonIdxs(u8 taskId)
{
}

void Task_LinkContest_CommunicateMonsRS(u8 taskId)
{
}

void Task_LinkContest_CommunicateMoveSelections(u8 taskId)
{
}

void Task_LinkContest_CommunicateRngRS(u8 taskId)
{
}

void Task_LinkContest_CommunicateRound1Points(u8 taskId)
{
}

void Task_LinkContest_CommunicateTurnOrder(u8 taskId)
{
}

void Task_LinkContest_Init(u8 taskId)
{
}

void Task_LinkContest_StartCommunicationEm(u8 taskId)
{
}

void Task_ReconnectWithLinkPlayers(u8 taskId)
{
}

void Task_WaitForLinkPlayerConnection(u8 taskId)
{
}

void UpdateWirelessStatusIndicatorSprite(void)
{
}

bool32 ValidateSavedWonderCard(void)
{
    return 0;
}

bool32 ValidateSavedWonderNews(void)
{
    return 0;
}

void WipeTrainerNameRecords(void)
{
}

u32 rfu_LMAN_REQBN_softReset_and_checkID(void)
{
    return 0;
}

void rfu_REQ_stopMode(void)
{
}

u16 rfu_waitREQComplete(void)
{
    return 0;
}

// --- script specials (declared only in data/specials.inc) ---
void BufferUnionRoomPlayerName(void)
{
}

void CableClubSaveGame(void)
{
}

void CleanupLinkRoomState(void)
{
}

void ColosseumPlayerSpotTriggered(void)
{
}

void CreateInGameTradePokemon(void)
{
}

void DoInGameTradeScene(void)
{
}

void ExitLinkRoom(void)
{
}

void GetInGameTradeSpeciesInfo(void)
{
}

void GetTradeSpecies(void)
{
}

void InitUnionRoom(void)
{
}

void PlayerEnteredTradeSeat(void)
{
}

void RunUnionRoom(void)
{
}

void Script_ResetUnionRoomTrade(void)
{
}

void Script_ShowLinkTrainerCard(void)
{
}

void Script_StartWiredTrade(void)
{
}

void ShowBerryCrushRankings(void)
{
}

void TryBattleLinkup(void)
{
}

void TryBecomeLinkLeader(void)
{
}

void TryBerryBlenderLinkup(void)
{
}

void TryContestEModeLinkup(void)
{
}

void TryContestGModeLinkup(void)
{
}

void TryJoinLinkGroup(void)
{
}

void TryRecordMixLinkup(void)
{
}

void TrySetBattleTowerLinkType(void)
{
}

void TryTradeLinkup(void)
{
}

void ValidateMixingGameLanguage(void)
{
}
