#include "global.h"
#include "rogue_bw_anim.h"
#include "battle.h"
#include "decompress.h"
#include "malloc.h"
#include "palette.h"
#include "pokemon.h"
#include "sprite.h"
#include "constants/species.h"
#include "variant_colours.h"

#include "data/rogue_bw_anim.h"
#include "data/rogue_bw_shiny.h"

// Bisection, not a scan. The table is nine entries today and is meant to reach
// several hundred; a linear scan runs per battler and would be the kind of cost
// that stays invisible until the roster is large enough to make it matter.
//
// emit_bw_anim.py is what guarantees the ordering this depends on, and it
// sorts by the NUMERIC species id read out of the species enum. Sorting by
// name looks equivalent and is not - it puts CLAYDOL before GEODUDE while
// their ids run the other way, and this search would then silently miss them.
const struct BwAnim *GetBwAnim(u16 species, bool32 isBack)
{
    const struct BwAnim *table;
    u32 lo, hi;

    // #if, not a runtime test on the macro: with the backs off, the guards in
    // data/rogue_bw_anim.h delete sBwAnimsBack outright, so naming it in a
    // branch the compiler folds away would still fail to compile. That is the
    // point - the switch has to remove the 386 back containers from the object
    // file, and --gc-sections cannot do it for us (see the header).
    //
    // A miss is the whole disable path: every caller already treats NULL as
    // "this species has no animation" and leaves the stock pic loaded.
#if ROGUE_BW_ANIM_BACK
    table = isBack ? sBwAnimsBack : sBwAnims;
    lo = 0;
    hi = isBack ? ARRAY_COUNT(sBwAnimsBack) : ARRAY_COUNT(sBwAnims);
#else
    if (isBack)
        return NULL;

    table = sBwAnims;
    lo = 0;
    hi = ARRAY_COUNT(sBwAnims);
#endif

    while (lo < hi)
    {
        u32 mid = (lo + hi) / 2;
        u16 got = table[mid].species;

        if (got == species)
            return &table[mid];
        if (got < species)
            lo = mid + 1;
        else
            hi = mid;
    }

    return NULL;
}

// The shiny colour map for one container, or NULL if it has none.
//
// A SEPARATE TABLE AND A SEPARATE BISECT, rather than a field on struct BwAnim.
// The two are generated by different tools - emit_bw_anim.py needs the 1,253
// gif set, which does not live in the repo, and emit_bw_shiny.py needs only
// checked-in files - so they are regenerated at different times by different
// people. Holding the map in struct BwAnim would force a full re-emit of 772
// containers to change a colour map, and coupling two generated tables BY
// POSITION would fail silently the moment one roster changed: a species would
// wear another species' shiny colours, and no build and no check would see it.
// Keying on species costs one extra bisect on a sprite load and cannot drift.
static const struct BwShinyMap *GetBwShinyMap(u16 species, bool32 isBack)
{
    const struct BwShinyMap *table;
    u32 lo, hi;

    // Same #if shape as GetBwAnim, and for the same reason: with the backs off
    // the guards in data/rogue_bw_shiny.h delete sBwShinyMapsBack outright, so
    // naming it in a branch the compiler folds away would still fail to build.
#if ROGUE_BW_ANIM_BACK
    table = isBack ? sBwShinyMapsBack : sBwShinyMaps;
    hi = isBack ? ARRAY_COUNT(sBwShinyMapsBack) : ARRAY_COUNT(sBwShinyMaps);
#else
    if (isBack)
        return NULL;

    table = sBwShinyMaps;
    hi = ARRAY_COUNT(sBwShinyMaps);
#endif
    lo = 0;

    while (lo < hi)
    {
        u32 mid = (lo + hi) / 2;
        u16 got = table[mid].species;

        if (got == species)
            return &table[mid];
        if (got < species)
            lo = mid + 1;
        else
            hi = mid;
    }

    return NULL;
}

// Build this container's SHINY palette into dst, or return FALSE and leave it
// alone. See struct BwShinyMap for what the map is and why it is a permutation
// rather than a palette.
//
// THE NON-FEMALE SHINY PALETTE, ALWAYS, and the FALSE below is load bearing.
// P_GENDER_DIFFERENCES is TRUE in this build, so GetMonSpritePalFromSpecies
// will hand back shinyPaletteFemale for a female mon - a DIFFERENT palette
// from the shiny.pal the map was computed against, whose indices mean whatever
// that artist made them mean. Applying our permutation to it would be sixteen
// confident lookups into the wrong table. The container itself is one sprite
// for both genders anyway, since the gif set has no gender variants, so there
// is nothing to be faithful to on that axis.
bool32 RogueBwAnim_BuildShinyPalette(u16 dst[16], u16 species, bool32 isBack)
{
    const struct BwShinyMap *shinyMap = GetBwShinyMap(species, isBack);
    const struct BwAnim *anim = GetBwAnim(species, isBack);
    const u16 *shiny;

    if (shinyMap == NULL || anim == NULL)
        return FALSE;

    shiny = GetMonSpritePalFromSpecies(species, TRUE, FALSE);
    if (shiny == NULL)
        return FALSE;

    // Slot 0 keeps the CONTAINER's own entry rather than taking the stock
    // sprite's. It is the transparent slot on both sides and is never drawn,
    // but the two carry different colours, and leaving the container's in
    // place keeps a normal and a shiny container byte-identical everywhere the
    // hardware does not look.
    dst[0] = anim->palette[0];

    for (u32 j = 1; j < 16; j++)
    {
        // Two slots to a byte, low nibble first - the packing emit_bw_shiny.py
        // writes. A nibble cannot exceed 15, so this cannot index off the end
        // of a 16 entry palette however wrong the table is.
        u32 idx = (j & 1) ? (shinyMap->map[j >> 1] >> 4) : (shinyMap->map[j >> 1] & 0xF);

        dst[j] = shiny[idx];
    }

    return TRUE;
}

// ---------------------------------------------------------------------------
// The battle runtime.
//
// Frames live compressed in ROM and are decoded a CHUNK at a time into a buffer
// held per battler. A chunk is four frames, so three frame changes out of four
// cost only a copy - which is why average CPU is lower than decoding one frame
// at a time would be, not higher.
//
// EITHER SIDE, but usually only the opponent. The 1,253 gif set is front
// sprites with no backs, so a species animates in the player's own slot only if
// a back sprite was sourced separately for it. Where both exist, a double
// battle can have FOUR sprites animating - which the one-decode-per-video-frame
// rule below is what makes affordable, since it caps the cost at one decode
// however many battlers want one.

// EWRAM_DATA, not a plain static: plain statics land in IWRAM, which is the one
// with no headroom - see limits-and-ram.md.
static EWRAM_DATA u8 *sBwChunkBuf[MAX_BATTLERS_COUNT] = {NULL};
static EWRAM_DATA const struct BwAnim *sBwAnim[MAX_BATTLERS_COUNT] = {NULL};

// The sprite id we have already proved is this battler's mon sprite, latched so
// the proof does not have to be repeated against a stamp that does not survive.
// See IsBattlerMonSprite.
static EWRAM_DATA u8 sBwSpriteId[MAX_BATTLERS_COUNT] = {0};

// The palette that went with the pixels last published for this battler, and the
// species it belongs to. 136 bytes of EWRAM.
//
// THIS IS A LIFETIME FIX, NOT A CACHE. The published PIXELS live in
// gMonSpritesGfxPtr, which outlives the battle screen, and at least one screen -
// the caught-mon dex page - draws from that buffer after CloseMainBattleScreen
// has run. Anything holding those pixels needs the palette that matches them, so
// the palette has to have the same lifetime as the pixels rather than the
// shorter lifetime of the animation state. See RogueBwAnim_GetPublishedPalette
// in the header for why keying on species makes that safe.
static EWRAM_DATA u16 sBwPublishedPal[MAX_BATTLERS_COUNT][16] = {0};
static EWRAM_DATA u16 sBwPublishedSpecies[MAX_BATTLERS_COUNT] = {SPECIES_NONE};

#define BW_NO_CHUNK 0xFF

static void ClearBwState(u32 battler)
{
    struct BattleSpriteInfo *info = &gBattleSpritesDataPtr->battlerData[battler];

    sBwAnim[battler] = NULL;
    sBwSpriteId[battler] = SPRITE_NONE;
    // Invalidated HERE rather than in RogueBwAnim_Free, and that placement is
    // the safety argument for a value that deliberately survives teardown. This
    // runs at the top of every OnLoadSprite, so a battler that loads a mon with
    // no animation clears the previous mon's claim on the same pass that
    // overwrites its pixels with the stock pic.
    sBwPublishedSpecies[battler] = SPECIES_NONE;
    info->bwStep = 0;
    info->bwHold = 0;
    info->bwChunk = BW_NO_CHUNK;
}

// Is gBattlerSpriteIds[battler] really this battler's mon sprite, showing this
// species?
//
// IT IS OFTEN NOT, and assuming otherwise corrupts whatever sprite it does name.
// Two ways it lies. The trainer slide code assigns
// gBattlerSpriteIds[battler] = gBattleStruct->trainerSlideSpriteIds[battler],
// so the id can be a TRAINER's - that is how a Geodude frame ended up drawn
// over Roxanne. And at the moment the pic is loaded the mon sprite does not
// exist yet: BtlController_HandleDrawTrainerPic calls BattleLoadMonSpriteGfx
// and only then CreateSprite, so the id still holds whatever was there before,
// and writing 2 KB to its tiles is what put a band of garbage through the
// player's healthbox.
//
// The engine stamps data[0] and data[2] on a battler's mon sprite the moment it
// creates one, so checking both is the discriminator, and it costs two loads.
// THE STAMP DOES NOT SURVIVE A MON ANIMATION, so it is proof of identity only
// the first time and a latch carries it afterwards. Task_HandleMonAnimation
// zeroes data[0] and data[2..7] while an animation runs and restores them from
// what it saved - but it saves data[0] as oam.paletteNum, and it saves data[2]
// from a sprite whose data another animation may already have cleared. After a
// KO animation, which is the two-frame victory animation played by the winner,
// the opponent's data[2] comes back as 1 rather than its species.
//
// That is a permanent freeze rather than a glitch: the stamp never becomes
// right again on its own, so every later frame is written into the buffer and
// none of them is copied to VRAM. Anything that recreates the sprite fixes it,
// which is why going to the Bag or the party menu appeared to restart the
// animation.
//
// Latching keeps every protection the stamp was there to provide. At load time
// the mon sprite does not exist yet and the latch is cleared, so a stale id is
// still rejected. If gBattlerSpriteIds[battler] is re-pointed at a TRAINER
// sprite - which the slide code really does - it no longer equals the latch and
// no longer matches the stamp, so that is still rejected too. Only the case
// this bug is about, the same sprite we already verified with its scratch data
// since trampled, now passes.
static bool32 IsBattlerMonSprite(u32 battler, u16 species)
{
    u32 spriteId = gBattlerSpriteIds[battler];

    if (spriteId == SPRITE_NONE || spriteId >= MAX_SPRITES)
        return FALSE;

    if (gSprites[spriteId].data[0] == (s16)battler
     && gSprites[spriteId].data[2] == (s16)species)
    {
        sBwSpriteId[battler] = spriteId;
        return TRUE;
    }

    if (spriteId != sBwSpriteId[battler])
        return FALSE;

    // THE LATCH ANSWERS "THE STAMP WAS TRAMPLED", NOT "THIS IS STILL OUR
    // SPRITE", and on its own it cannot tell those apart. A mon's sprite is
    // DESTROYED when it leaves the field and its slot is reused, while
    // gBattlerSpriteIds keeps pointing at the freed slot - so both sides of
    // the comparison above still hold the old id and whatever claimed that
    // slot next inherits permission to have 2 KB written into its tiles.
    //
    // A SPRITE ID IS A SLOT NUMBER, NOT AN IDENTITY. Slot numbers are
    // recycled, so nothing derived from the id alone can survive the sprite
    // it named being destroyed.
    //
    // Do not try to re-derive identity from the sprite's CONTENTS either. That
    // was the first attempt at this and it shipped: comparing `images` against
    // gMonSpritesGfxPtr->frameImages correctly rejects a healthbox, and does
    // NOT reject a trainer, because mon and trainer sprites come from the same
    // gMultiuseSpriteTemplate and share frameImages after AllocateMonSpritesGfx
    // - which engine-traps.md says in as many words. The healthbox garbage
    // simply became a Geodude drawn over Roxanne. The stamp is the only content
    // that ever separated the two, and the stamp is what does not survive.
    //
    // So the latch is invalidated at the SOURCE instead - see
    // RogueBwAnim_OnSpriteFreed - and all that is left here is to notice a slot
    // that has been freed and not yet reused, and drop the latch then too.
    if (!gSprites[spriteId].inUse)
    {
        sBwSpriteId[battler] = SPRITE_NONE;
        return FALSE;
    }

    return TRUE;
}

// The battler's mon sprite is being destroyed; the latch must die with it.
//
// Called from FreeMonSprite, which is the return-to-ball path. A slot freed
// here is reused almost immediately - by the next mon, or by the trainer
// sprite at the end of a battle - and the latch would otherwise still name it.
void RogueBwAnim_OnSpriteFreed(u32 battler)
{
    if (battler < MAX_BATTLERS_COUNT)
        sBwSpriteId[battler] = SPRITE_NONE;
}

// Put a frame where the engine will draw it.
//
// It goes into BOTH resident slots, and that is not redundancy. A species'
// frontAnimFrames cycles image frames 0 and 1 - ANIMCMD_FRAME(0,30),
// ANIMCMD_FRAME(1,30) - and every one of those issues its own VRAM copy out of
// whichever slot it names. Writing only the slot we request would leave the
// other holding a stale frame for the anim system to draw the moment a mon
// plays its two-frame animation. Filling both means it does not matter which
// one wins, and it costs two 2 KB copies against a 48,000 cycle decode.
//
// The VRAM copy is skipped unless the sprite is verified. Filling the buffer is
// always safe and is all that is needed at load time anyway - the sprite is
// created immediately afterwards and reads it.
static void PublishBwFrame(u32 battler, u16 species, const u8 *frame, u32 size)
{
    enum BattlerPosition position = GetBattlerPosition(battler);
    u8 *dest = gMonSpritesGfxPtr->spritesGfx[position];

    if (dest == NULL)
        return;

    CpuFastCopy(frame, dest, size);
    CpuFastCopy(frame, dest + MON_PIC_SIZE, size);

    if (IsBattlerMonSprite(battler, species))
        RequestSpriteFrameImageCopy(0, gSprites[gBattlerSpriteIds[battler]].oam.tileNum,
                                    gMonSpritesGfxPtr->frameImages[position]);
}

void RogueBwAnim_OnLoadSprite(u32 battler, u16 species, bool32 isShiny, u32 personality)
{
    const struct BwAnim *anim;
    struct BattleSpriteInfo *info;
    u32 chunk, frame;
    u16 pal[16];
    u16 shinyPal[16];
    const u16 *base;

    ClearBwState(battler);

    // Which side the battler is on decides which table to read, because it
    // decides which sprite the engine will draw. A species with a front entry
    // and no back animates as an opponent and stays static in the player's own
    // slot, which is the usual case.
    anim = GetBwAnim(species, IsOnPlayerSide(battler));
    if (anim == NULL)
        return;

    // AllocUnchecked, NOT Alloc. Alloc calls fatalf when the heap cannot
    // satisfy it and never returns NULL, so a NULL check after it is dead code
    // and a tight battle is a crash rather than a degraded one. This is the
    // allocation most likely to fail: it is the largest thing a battle asks for
    // after the 16 KB sprite buffer, and a double battle can want four.
    if (sBwChunkBuf[battler] == NULL)
        sBwChunkBuf[battler] = AllocUnchecked(GetSmolChunkSize(anim->frames));

    // Out of heap is not worth a crash. Leaving the buffer NULL means the mon
    // keeps the stock two-frame sprite the caller has already loaded, which is
    // exactly the fallback a species with no entry gets.
    if (sBwChunkBuf[battler] == NULL)
        return;

    sBwAnim[battler] = anim;
    info = &gBattleSpritesDataPtr->battlerData[battler];
    info->bwStep = 0;
    info->bwHold = anim->seq[0].hold - 1;

    frame = anim->seq[0].frame;
    chunk = GetSmolFrameChunk(anim->frames, frame);
    DecompressSmolChunk(anim->frames, sBwChunkBuf[battler], chunk);
    info->bwChunk = chunk;

    PublishBwFrame(battler, anim->species,
                   sBwChunkBuf[battler] + GetSmolFrameOffsetInChunk(anim->frames, frame),
                   GetSmolFrameSize(anim->frames));

    // The gif carries its own 15 colours, which are not the ones the shipped
    // sprite uses - so the palette has to be taken over along with the pixels
    // or the mon arrives in the right shape and the wrong colours. This
    // overwrites the LoadPalette the caller just did.
    //
    // WHICH IS WHY THE COLOUR VARIANT HAS TO BE APPLIED HERE TOO. The caller
    // hands GetMonSpritePalVariant a shifted palette and then this function
    // throws it away, so hooking only the generic getter would leave variants
    // working everywhere except the one screen anybody looks at, and only for
    // the 772 species that have a BW container - which is most of the ones a
    // run actually meets. It would have looked like the feature half worked.
    //
    // Keyed on `species` rather than anim->species so that the shift matches
    // the one the party menu and the box will compute for the same mon: this
    // palette is replacing the one the caller derived from `species`, and two
    // screens disagreeing about a mon's colour is worse than no variant.
    base = anim->palette;

    // A SHINY REPLACES THE CONTAINER'S PALETTE BEFORE THE VARIANT SEES IT, and
    // the order is the whole point. The container's palette is the gif's normal
    // one; BuildShinyPalette permutes the stock shiny palette into its slots,
    // and what comes out is what a shiny of this species is supposed to look
    // like. ApplyMonSpritePalVariantTo then returns it unchanged, because
    // VARIANT_COLOURS_SHINY is FALSE - a shiny is the one colour signal in a
    // run that has to stay recognisable, so it is deliberately not shifted.
    //
    // A miss falls through to the normal palette rather than failing. That is
    // the same fallback a species with no container gets, and it is what the
    // build did for every shiny before this existed.
    if (isShiny && RogueBwAnim_BuildShinyPalette(shinyPal, species, IsOnPlayerSide(battler)))
        base = shinyPal;

    ApplyMonSpritePalVariantTo(pal, base, species, isShiny, personality);
    LoadPalette(pal, OBJ_PLTT_ID(battler), PLTT_SIZE_4BPP);
    LoadPalette(pal, BG_PLTT_ID(8) + BG_PLTT_ID(battler), PLTT_SIZE_4BPP);

    // Kept for whoever draws these pixels next. Recorded AFTER the variant and
    // the shiny rebuild, so what is stored is exactly what went to the hardware
    // rather than the container's raw palette - a screen reusing the pixels
    // wants the mon it just saw, freckles and all.
    CpuCopy16(pal, sBwPublishedPal[battler], 16 * sizeof(u16));
    sBwPublishedSpecies[battler] = species;
}

const u16 *RogueBwAnim_GetPublishedPalette(u32 battler, u16 species)
{
    if (battler >= MAX_BATTLERS_COUNT || species == SPECIES_NONE)
        return NULL;

    if (sBwPublishedSpecies[battler] != species)
        return NULL;

    return sBwPublishedPal[battler];
}

static void TickBattler(u32 battler, bool32 *decodedThisFrame)
{
    const struct BwAnim *anim = sBwAnim[battler];
    struct BattleSpriteInfo *info = &gBattleSpritesDataPtr->battlerData[battler];
    u32 spriteId = gBattlerSpriteIds[battler];
    u32 nextStep, frame, chunk;

    if (anim == NULL || sBwChunkBuf[battler] == NULL)
        return;
    if (info->invisible || info->behindSubstitute)
        return;

    // A FAINTED BATTLER HAS NO MON SPRITE TO ANIMATE. Its sprite is torn down
    // and its slot handed to whatever comes next - the replacement mon, or the
    // trainer sprite at the end of a battle - so anything published for it
    // lands in someone else's tiles. That is what drew a Geodude over Roxanne.
    //
    // This is a semantic guard rather than another test on the sprite, and it
    // is here because sprite identity is exactly what cannot be trusted at
    // this moment. It deliberately does NOT stop the winner: the KO animation
    // is played over the loser and reads well against the winner's BW frames,
    // which is the thing the latch exists to keep working.
    if (gBattleMons[battler].hp == 0)
        return;
    if (spriteId == SPRITE_NONE || spriteId >= MAX_SPRITES || gSprites[spriteId].invisible)
        return;

    if (info->bwHold > 0)
    {
        info->bwHold--;
        return;
    }

    nextStep = info->bwStep + 1;
    if (nextStep >= anim->seqLength)
        nextStep = 0;

    frame = anim->seq[nextStep].frame;
    chunk = GetSmolFrameChunk(anim->frames, frame);

    if (chunk != info->bwChunk)
    {
        // At most one chunk decode per video frame. A decode is ~48% of a frame
        // and the budget only has room for one on top of a battle's own 8%, so
        // in a double battle the second battler waits. bwHold stays 0, so this
        // retries next frame rather than skipping the step - and a one frame
        // delay is invisible against holds that run 4 to 8 frames.
        if (*decodedThisFrame)
            return;

        DecompressSmolChunk(anim->frames, sBwChunkBuf[battler], chunk);
        info->bwChunk = chunk;
        *decodedThisFrame = TRUE;
    }

    info->bwStep = nextStep;
    info->bwHold = anim->seq[nextStep].hold - 1;
    PublishBwFrame(battler, anim->species,
                   sBwChunkBuf[battler] + GetSmolFrameOffsetInChunk(anim->frames, frame),
                   GetSmolFrameSize(anim->frames));
}

void RogueBwAnim_Tick(void)
{
    bool32 decodedThisFrame = FALSE;

    // Runs from BattleMainCB2, which is the steady state callback - setup goes
    // through CB2_InitBattleInternal, where these pointers are not valid yet.
    if (gBattleSpritesDataPtr == NULL || gBattleSpritesDataPtr->battlerData == NULL
     || gMonSpritesGfxPtr == NULL)
        return;

    for (u32 battler = 0; battler < gBattlersCount; battler++)
        TickBattler(battler, &decodedThisFrame);
}

void RogueBwAnim_Free(void)
{
    for (u32 battler = 0; battler < MAX_BATTLERS_COUNT; battler++)
    {
        if (sBwChunkBuf[battler] != NULL)
        {
            Free(sBwChunkBuf[battler]);
            sBwChunkBuf[battler] = NULL;
        }
        sBwAnim[battler] = NULL;
        sBwSpriteId[battler] = SPRITE_NONE;

        // DO NOT CLEAR sBwPublishedSpecies HERE. It looks like the obvious
        // omission and it is the point: CloseMainBattleScreen calls this
        // function and THEN shows the caught-mon dex page, which draws the
        // pixels this palette belongs to. Clearing here returns NULL at the one
        // moment the answer is needed, and the mon is scrambled again.
        // ClearBwState is what invalidates it, on the next load into this
        // battler - which is also when the pixels stop being ours.
    }
}

// Whether a frame published now would actually reach VRAM. Exists so the freeze
// this guards against is testable: the tick keeps running and the buffer keeps
// updating either way, so nothing else about a frozen sprite is observable from
// a test.
bool32 RogueBwAnim_WouldPublish(u32 battler)
{
    if (battler >= MAX_BATTLERS_COUNT || sBwAnim[battler] == NULL)
        return FALSE;

    // MIRRORS TickBattler'S FAINT GUARD, and has to. This function exists so
    // the publish decision is observable from a test, and a guard the tick
    // applies but this does not is a guard no test can see - which is how the
    // Geodude-over-Roxanne case would have shipped again.
    if (gBattleMons[battler].hp == 0)
        return FALSE;

    return IsBattlerMonSprite(battler, sBwAnim[battler]->species);
}
