# GENERATED by tools/rogue/emit_bw_trainer_anim.py - do not edit by hand.
#
# BW animated trainer front pics. One rule per trainer, because -fw
# takes the frame size in bytes and the frames per chunk, and neither
# is recoverable from the 4bpp file.
#
# Chunk size is 2, matching the species containers so one chunk
# buffer size serves both. See graphics/pokemon/bw_anim_rules.mk.

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/champion_wallace_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/champion_wallace_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/elite_four_drake_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/elite_four_drake_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/elite_four_glacia_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/elite_four_glacia_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/elite_four_phoebe_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/elite_four_phoebe_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/elite_four_sidney_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/elite_four_sidney_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_brawly_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_brawly_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_flannery_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_flannery_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_juan_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_juan_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_norman_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_norman_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_roxanne_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_roxanne_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_wattson_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_wattson_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_winona_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/leader_winona_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2

$(ASSETS_DIR_NAME)/graphics/trainers/front_pics/steven_bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/trainers/front_pics/steven_bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 2
