#ifndef GUARD_DATA_ROGUE_BW_TRAINER_ANIM_H
#define GUARD_DATA_ROGUE_BW_TRAINER_ANIM_H

// GENERATED by tools/rogue/emit_bw_trainer_anim.py - do not edit by hand.
//
// BW-style animated trainer front pics. A TRAINER_PIC listed here plays a
// frame sequence in place of its single static pic; one absent keeps the stock
// pic, so a partial roster is always a valid build.
//
// hold is in VIDEO FRAMES, converted from the source gif's milliseconds at
// emit time so nothing divides at runtime.
//
// ONE TABLE, NOT TWO. The species side needs a front and a back table because a
// species can have both and one species-sorted table would then hold duplicate
// keys. A trainer BACK pic is the player's own and is never one of these, so
// there is exactly one table here and it is keyed on TRAINER_PIC.

const u32 gBwTrainerGfx_Steven[] = INCGFX_U32("graphics/trainers/front_pics/steven_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_Steven[] = INCGFX_U16("graphics/trainers/front_pics/steven_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_EliteFourSidney[] = INCGFX_U32("graphics/trainers/front_pics/elite_four_sidney_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_EliteFourSidney[] = INCGFX_U16("graphics/trainers/front_pics/elite_four_sidney_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_EliteFourPhoebe[] = INCGFX_U32("graphics/trainers/front_pics/elite_four_phoebe_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_EliteFourPhoebe[] = INCGFX_U16("graphics/trainers/front_pics/elite_four_phoebe_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_EliteFourGlacia[] = INCGFX_U32("graphics/trainers/front_pics/elite_four_glacia_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_EliteFourGlacia[] = INCGFX_U16("graphics/trainers/front_pics/elite_four_glacia_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_EliteFourDrake[] = INCGFX_U32("graphics/trainers/front_pics/elite_four_drake_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_EliteFourDrake[] = INCGFX_U16("graphics/trainers/front_pics/elite_four_drake_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_LeaderRoxanne[] = INCGFX_U32("graphics/trainers/front_pics/leader_roxanne_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_LeaderRoxanne[] = INCGFX_U16("graphics/trainers/front_pics/leader_roxanne_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_LeaderBrawly[] = INCGFX_U32("graphics/trainers/front_pics/leader_brawly_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_LeaderBrawly[] = INCGFX_U16("graphics/trainers/front_pics/leader_brawly_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_LeaderWattson[] = INCGFX_U32("graphics/trainers/front_pics/leader_wattson_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_LeaderWattson[] = INCGFX_U16("graphics/trainers/front_pics/leader_wattson_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_LeaderFlannery[] = INCGFX_U32("graphics/trainers/front_pics/leader_flannery_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_LeaderFlannery[] = INCGFX_U16("graphics/trainers/front_pics/leader_flannery_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_LeaderNorman[] = INCGFX_U32("graphics/trainers/front_pics/leader_norman_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_LeaderNorman[] = INCGFX_U16("graphics/trainers/front_pics/leader_norman_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_LeaderWinona[] = INCGFX_U32("graphics/trainers/front_pics/leader_winona_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_LeaderWinona[] = INCGFX_U16("graphics/trainers/front_pics/leader_winona_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_LeaderJuan[] = INCGFX_U32("graphics/trainers/front_pics/leader_juan_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_LeaderJuan[] = INCGFX_U16("graphics/trainers/front_pics/leader_juan_bw_anim.png", ".gbapal");
const u32 gBwTrainerGfx_ChampionWallace[] = INCGFX_U32("graphics/trainers/front_pics/champion_wallace_bw_anim.png", ".4bpp.fsmol");
const u16 gBwTrainerPal_ChampionWallace[] = INCGFX_U16("graphics/trainers/front_pics/champion_wallace_bw_anim.png", ".gbapal");

static const struct BwAnimStep sBwTrainerSeq_Steven[] =
{
    { 0, 33 },
    { 1, 3 },
    { 2, 6 },
    { 3, 3 },
    { 4, 3 },
    { 5, 6 },
    { 6, 3 },
    { 7, 3 },
    { 8, 6 },
    { 9, 3 },
    { 10, 3 },
    { 11, 6 },
    { 12, 3 },
    { 13, 3 },
    { 14, 6 },
    { 15, 3 },
    { 16, 36 },
};

static const struct BwAnimStep sBwTrainerSeq_EliteFourSidney[] =
{
    { 0, 6 },
    { 1, 6 },
    { 2, 6 },
    { 3, 6 },
    { 4, 6 },
    { 3, 6 },
    { 2, 6 },
    { 1, 6 },
    { 0, 6 },
    { 1, 6 },
    { 2, 6 },
    { 3, 6 },
    { 4, 6 },
    { 3, 6 },
    { 2, 6 },
    { 1, 6 },
};

static const struct BwAnimStep sBwTrainerSeq_EliteFourPhoebe[] =
{
    { 0, 6 },
    { 1, 6 },
    { 2, 6 },
    { 3, 6 },
    { 4, 6 },
    { 5, 6 },
    { 6, 6 },
    { 7, 6 },
    { 8, 6 },
    { 9, 6 },
    { 10, 6 },
    { 11, 6 },
    { 12, 6 },
    { 13, 6 },
    { 14, 6 },
    { 15, 6 },
};

static const struct BwAnimStep sBwTrainerSeq_EliteFourGlacia[] =
{
    { 0, 6 },
    { 1, 6 },
    { 2, 6 },
    { 3, 6 },
    { 4, 6 },
    { 5, 6 },
    { 6, 6 },
    { 7, 6 },
    { 8, 6 },
    { 9, 6 },
    { 10, 6 },
    { 11, 6 },
    { 12, 6 },
    { 13, 6 },
    { 14, 6 },
    { 15, 6 },
};

static const struct BwAnimStep sBwTrainerSeq_EliteFourDrake[] =
{
    { 0, 6 },
    { 1, 6 },
    { 2, 6 },
    { 3, 6 },
    { 4, 6 },
    { 5, 6 },
    { 6, 6 },
    { 7, 6 },
    { 8, 6 },
    { 9, 6 },
    { 10, 6 },
    { 11, 6 },
    { 12, 6 },
    { 13, 6 },
    { 14, 6 },
    { 15, 6 },
};

static const struct BwAnimStep sBwTrainerSeq_LeaderRoxanne[] =
{
    { 0, 33 },
    { 1, 3 },
    { 2, 6 },
    { 3, 3 },
    { 4, 3 },
    { 5, 6 },
    { 6, 3 },
    { 7, 3 },
    { 8, 6 },
    { 9, 3 },
    { 10, 3 },
    { 11, 6 },
    { 12, 3 },
    { 13, 3 },
    { 14, 6 },
    { 15, 3 },
    { 16, 36 },
};

static const struct BwAnimStep sBwTrainerSeq_LeaderBrawly[] =
{
    { 0, 33 },
    { 1, 3 },
    { 2, 6 },
    { 3, 3 },
    { 4, 3 },
    { 5, 6 },
    { 6, 3 },
    { 7, 3 },
    { 8, 6 },
    { 9, 3 },
    { 10, 3 },
    { 11, 6 },
    { 12, 3 },
    { 13, 3 },
    { 14, 6 },
    { 15, 36 },
};

static const struct BwAnimStep sBwTrainerSeq_LeaderWattson[] =
{
    { 0, 6 },
    { 1, 3 },
    { 2, 3 },
    { 3, 6 },
    { 4, 3 },
    { 5, 3 },
    { 6, 6 },
    { 2, 3 },
    { 7, 3 },
    { 5, 9 },
    { 8, 3 },
    { 2, 6 },
    { 7, 3 },
    { 5, 3 },
    { 9, 6 },
    { 10, 3 },
    { 11, 3 },
    { 12, 6 },
    { 13, 3 },
    { 14, 3 },
    { 15, 6 },
    { 16, 3 },
    { 17, 3 },
    { 18, 6 },
    { 19, 36 },
};

static const struct BwAnimStep sBwTrainerSeq_LeaderFlannery[] =
{
    { 0, 21 },
    { 1, 3 },
    { 2, 6 },
    { 3, 3 },
    { 4, 3 },
    { 5, 6 },
    { 6, 3 },
    { 7, 3 },
    { 8, 6 },
    { 9, 3 },
    { 10, 3 },
    { 11, 6 },
    { 12, 3 },
    { 13, 3 },
    { 14, 6 },
    { 15, 3 },
    { 16, 3 },
    { 17, 6 },
    { 18, 3 },
    { 19, 36 },
};

static const struct BwAnimStep sBwTrainerSeq_LeaderNorman[] =
{
    { 0, 18 },
    { 1, 3 },
    { 2, 3 },
    { 3, 9 },
    { 4, 33 },
    { 5, 3 },
    { 6, 3 },
    { 7, 6 },
    { 8, 3 },
    { 9, 3 },
    { 10, 6 },
    { 11, 36 },
};

static const struct BwAnimStep sBwTrainerSeq_LeaderWinona[] =
{
    { 0, 9 },
    { 1, 3 },
    { 2, 6 },
    { 3, 3 },
    { 4, 9 },
    { 5, 3 },
    { 6, 3 },
    { 7, 6 },
    { 8, 3 },
    { 9, 3 },
    { 10, 6 },
    { 11, 3 },
    { 12, 3 },
    { 13, 6 },
    { 14, 3 },
    { 15, 3 },
    { 16, 6 },
    { 17, 3 },
    { 18, 3 },
    { 19, 6 },
    { 20, 3 },
    { 21, 3 },
    { 22, 6 },
    { 23, 3 },
    { 24, 36 },
};

static const struct BwAnimStep sBwTrainerSeq_LeaderJuan[] =
{
    { 0, 27 },
    { 1, 3 },
    { 2, 6 },
    { 3, 6 },
    { 4, 3 },
    { 5, 21 },
    { 6, 6 },
    { 7, 3 },
    { 8, 6 },
    { 9, 6 },
    { 10, 3 },
    { 11, 6 },
    { 12, 6 },
    { 13, 3 },
    { 14, 6 },
    { 15, 6 },
    { 16, 36 },
};

static const struct BwAnimStep sBwTrainerSeq_ChampionWallace[] =
{
    { 0, 24 },
    { 1, 6 },
    { 2, 3 },
    { 3, 3 },
    { 4, 6 },
    { 5, 3 },
    { 6, 3 },
    { 7, 6 },
    { 8, 3 },
    { 9, 3 },
    { 10, 6 },
    { 11, 3 },
    { 12, 3 },
    { 13, 6 },
    { 14, 3 },
    { 15, 3 },
    { 16, 6 },
    { 17, 36 },
};

// Sorted by TRAINER_PIC id - GetBwTrainerAnim bisects this.
static const struct BwTrainerAnim sBwTrainerAnims[] =
{
    {
        .trainerPic = TRAINER_PIC_STEVEN,   // 8
        .frames = gBwTrainerGfx_Steven,
        .palette = gBwTrainerPal_Steven,
        .seq = sBwTrainerSeq_Steven,
        .frameCount = 17,
        .seqLength = 17,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_ELITE_FOUR_SIDNEY,   // 47
        .frames = gBwTrainerGfx_EliteFourSidney,
        .palette = gBwTrainerPal_EliteFourSidney,
        .seq = sBwTrainerSeq_EliteFourSidney,
        .frameCount = 5,
        .seqLength = 16,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_ELITE_FOUR_PHOEBE,   // 48
        .frames = gBwTrainerGfx_EliteFourPhoebe,
        .palette = gBwTrainerPal_EliteFourPhoebe,
        .seq = sBwTrainerSeq_EliteFourPhoebe,
        .frameCount = 16,
        .seqLength = 16,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_ELITE_FOUR_GLACIA,   // 49
        .frames = gBwTrainerGfx_EliteFourGlacia,
        .palette = gBwTrainerPal_EliteFourGlacia,
        .seq = sBwTrainerSeq_EliteFourGlacia,
        .frameCount = 16,
        .seqLength = 16,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_ELITE_FOUR_DRAKE,   // 50
        .frames = gBwTrainerGfx_EliteFourDrake,
        .palette = gBwTrainerPal_EliteFourDrake,
        .seq = sBwTrainerSeq_EliteFourDrake,
        .frameCount = 16,
        .seqLength = 16,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_LEADER_ROXANNE,   // 51
        .frames = gBwTrainerGfx_LeaderRoxanne,
        .palette = gBwTrainerPal_LeaderRoxanne,
        .seq = sBwTrainerSeq_LeaderRoxanne,
        .frameCount = 17,
        .seqLength = 17,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_LEADER_BRAWLY,   // 52
        .frames = gBwTrainerGfx_LeaderBrawly,
        .palette = gBwTrainerPal_LeaderBrawly,
        .seq = sBwTrainerSeq_LeaderBrawly,
        .frameCount = 16,
        .seqLength = 16,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_LEADER_WATTSON,   // 53
        .frames = gBwTrainerGfx_LeaderWattson,
        .palette = gBwTrainerPal_LeaderWattson,
        .seq = sBwTrainerSeq_LeaderWattson,
        .frameCount = 20,
        .seqLength = 25,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_LEADER_FLANNERY,   // 54
        .frames = gBwTrainerGfx_LeaderFlannery,
        .palette = gBwTrainerPal_LeaderFlannery,
        .seq = sBwTrainerSeq_LeaderFlannery,
        .frameCount = 20,
        .seqLength = 20,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_LEADER_NORMAN,   // 55
        .frames = gBwTrainerGfx_LeaderNorman,
        .palette = gBwTrainerPal_LeaderNorman,
        .seq = sBwTrainerSeq_LeaderNorman,
        .frameCount = 12,
        .seqLength = 12,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_LEADER_WINONA,   // 56
        .frames = gBwTrainerGfx_LeaderWinona,
        .palette = gBwTrainerPal_LeaderWinona,
        .seq = sBwTrainerSeq_LeaderWinona,
        .frameCount = 25,
        .seqLength = 25,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_LEADER_JUAN,   // 58
        .frames = gBwTrainerGfx_LeaderJuan,
        .palette = gBwTrainerPal_LeaderJuan,
        .seq = sBwTrainerSeq_LeaderJuan,
        .frameCount = 17,
        .seqLength = 17,
        .width = 64,
        .height = 64,
    },
    {
        .trainerPic = TRAINER_PIC_CHAMPION_WALLACE,   // 65
        .frames = gBwTrainerGfx_ChampionWallace,
        .palette = gBwTrainerPal_ChampionWallace,
        .seq = sBwTrainerSeq_ChampionWallace,
        .frameCount = 18,
        .seqLength = 18,
        .width = 64,
        .height = 64,
    },
};

#endif // GUARD_DATA_ROGUE_BW_TRAINER_ANIM_H
