# GENERATED by tools/rogue/emit_bw_anim.py - do not edit by hand.
#
# BW animation frame containers. One rule per species, because -fw
# takes the frame size in bytes and the frames per chunk, and neither
# is recoverable from the 4bpp file.
#
# Chunk size is 4. Raising it shrinks ROM and lowers average CPU,
# since a caller holding the decoded chunk decodes once per chunk
# rather than once per frame - but it raises the one-off spike when a
# chunk does have to be decoded, and the scratch buffer with it.

$(ASSETS_DIR_NAME)/graphics/pokemon/claydol/bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/pokemon/claydol/bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 4

$(ASSETS_DIR_NAME)/graphics/pokemon/geodude/bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/pokemon/geodude/bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 4

$(ASSETS_DIR_NAME)/graphics/pokemon/lunatone/bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/pokemon/lunatone/bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 4

$(ASSETS_DIR_NAME)/graphics/pokemon/mudkip/bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/pokemon/mudkip/bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 4

$(ASSETS_DIR_NAME)/graphics/pokemon/nosepass/bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/pokemon/nosepass/bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 4

$(ASSETS_DIR_NAME)/graphics/pokemon/solrock/bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/pokemon/solrock/bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 4

$(ASSETS_DIR_NAME)/graphics/pokemon/torchic/bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/pokemon/torchic/bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 4

$(ASSETS_DIR_NAME)/graphics/pokemon/treecko/bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/pokemon/treecko/bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 4

$(ASSETS_DIR_NAME)/graphics/pokemon/xatu/bw_anim.png.4bpp.fsmol: $(ASSETS_DIR_NAME)/graphics/pokemon/xatu/bw_anim.png.4bpp
	$(SMOL) -fw $< $@ 2048 4
